### PR TITLE
SXT Airbags

### PR DESCRIPTION
**Pull request by Zarbizaure**
Not a lot of change here, just mark these two airbags as "RO-supported". I did not change the scale or anything because I think it's better to do it with tweakscale (on these parts).

### CODE REVIEW

**Comment by NathanKell** [comment]
Per our discussion on the other PR, please change the description to be RO-appopriate rather than kerbalish. Otherwise looks good! :)

**Comment by Zarbizaure** [comment]
Well, I kept them because they are fun! But that's fine, I will change them to something more realistic :)

**Comment by NathanKell** [comment]
RO does not believe in fun. It has surgically removed it from KSP.
...
...
:P

**Comment by Zarbizaure** [comment]
Trust me or not, but i find RO really fun to play (and also really rewarding...). Watching rocket explode with even more thrust and boosters is always fun.

**Comment by NathanKell** [comment]
Hence the :P -- was poking a bit of fun at the stereotype that RO sucks the fun out of KSP. No, it's that RO's fun is a different kind of fun. :)

**Pull request merged**
