### PR TITLE
BE-4 engine updates & fixes

### PR DESCRIPTION
**Pull request by PhineasFreak**
**Change Log:**

* Add some basic info and web sources to the global engine config.
* Add a default part module category.
* Add some default engine module parameters.
* ~~Tweak the minimum and maximum thrust value to correspond to a rated VAC thrust of **550000 lbf**.~~
* Update the ASL and VAC Isp values (**note 1**).
* Remove the requirement of a TEATEB resource for ignition.
* Fix the size of the VSR 2 x BE-4 engine cluster (was too small).

**Notes:**

* **Note 1:** The Isp values were calculated via the [Rocket Propulsion Analysis (RPA)](http://www.propulsion-analysis.com/index.htm) program (lite version). The throat and exhaust areas were calculated from the [BE-4 engine infographic picture](https://cdn.arstechnica.net/wp-content/uploads/2017/03/BE44.jpg). The RPA file is available from here: https://raw.githubusercontent.com/PhineasFreak/DocBin/master/DocBin/generic_files/RPA-BE-4.cfg. Updates to these values will be issued as more information becomes available.

### CODE REVIEW

**Comment by SirKeplan** [comment]
couple quick notes.

550000 lbf is actually SL thrust

later found min thrust is 30%. 

http://forum.nasaspaceflight.com/index.php?topic=10685.msg1665037#msg1665037

**Comment by PhineasFreak** [comment]
Hmm...now the thrust value explains how Vulcan can lift off without any additional SRMs. Time to bug fix the bug fix!

**Comment by SirKeplan** [comment]
Isp looks unrealistically high, are you going off of RPA's theoretical perf rather than estimated performance? Also i don't think even BO know it's real performance yet, until they do tests. maybe we should leave the Isp at spacelaunchreport's estimates.

The NSF forum link also says 5 degrees of gimbal, but that's on New Glenn, presumably Vulcan will have more as it's an Atlas successor and might take uneven SRB arrangements.

I think everything else is ok.

**Comment by PhineasFreak** [comment]
I went by the facts that it is a Methalox engine and one of the "requirements" for Vulcan is to have at least, if not better, Isp figures than the RD-180. The VAC figure might stretch it a bit, is that one that you refer as unrealistic? BTW, i used the **Altitude Peformance** values (318.42 s ASL / 354.59 s VAC).

It is also difficult to get good estimates for the throat and exhaust areas. A measurement error of just 1 px translates into almost 0.0795 m (~7.95 cm) and that is why i used an expansion area ratio of 25 (as quoted by many articles and posts). Dropping the freeze value of the area ratio at 1 instead of 3 gets a more meager 309 s ASL / 345 s VAC.

**Comment by PhineasFreak** [comment]
@SirKeplan yes, my bad. I found it out after my last post...

So, freeze the values at 305/341?

**Comment by SirKeplan** [comment]
@PhineasFreak Yes, that should be fine.

**Comment by PhineasFreak** [comment]
@SirKeplan sorry that i "broke" your current review... :worried:

**Comment by PhineasFreak** [comment]
So, are we good here?

**Pull request merged**
