### PR TITLE
Update to KSP 1.2.

### PR DESCRIPTION
**Pull request by ahmedcharles**

### CODE REVIEW

**Comment by SirKeplan** [comment]
note: this is to be merged to KSP12Update when it's ready.

**Comment by NathanKell** [comment]
EditorCrewMass can be removed entirely, the bug in 1.1 which required it is fixed in 1.2.

**Comment by stratochief66** [comment]
@NathanKell @SirKeplan if you can verify these changes are good, could you please merge?

**Comment by SirKeplan** [comment]
Thanks for this @ahmedcharles, going to close and and push commits based on this and #1469

**Pull request closed without merging**
