### PR TITLE
Fix FASA LR91 Engine Config GUI

### PR DESCRIPTION
**Pull request by SirKeplan**
There is a remaining issue with the other LR91, the vernier sometimes won't switch to Aerozine.
@NathanKell this is a RF bug correct?

### CODE REVIEW

**Comment by stratochief66** [comment]
@SirKeplan could you rebase this & eliminate the merge conflicts?

**Comment by SirKeplan** [comment]
seamed simpler to merge, and stay with master.

**Comment by NathanKell** [comment]
There's still a HEAD in there...

**Comment by SirKeplan** [comment]
fixed, was sure i'd done that already....

**Pull request merged**
