### PR TITLE
Updates to Bobcat's Mir RO Patch [CLOSE THIS PLEASE]

### PR DESCRIPTION
**Pull request by Sepehr3987**
-Create tags for easy searching in VAB
-Change the name title of Mir Core Module to Mir Core/Zvezda Modul
[RO_Mir.zip](https://github.com/KSP-RO/RealismOverhaul/files/8483446/RO_Mir.zip)

### CODE REVIEW

**Comment by DRVeyl** [comment]
Uh.  Why did you start this in the newComms branch?  This PR doesn't have any of your commits.

Please start with your fork of the repo, from the master branch.  Apply your changes as a commit [not uploading a folder in the PR message].  Then create the PR from your working branch, not a random one.

**Comment by Sepehr3987** [comment]
Hey, How can I commit new changes to my forked repo?From: DRVeylSent: Wednesday, April 13, 2022 10:01 PMTo: KSP-RO/RealismOverhaulCc: Sepehr Javeri; AuthorSubject: Re: [KSP-RO/RealismOverhaul] Updates to Bobcat's Mir RO Patch [CLOSE THIS PLEASE] (PR #2635) Uh. Why did you start this in the newComms branch? This PR doesn't have any of your commits.Please start with your fork of the repo, from the master branch. Apply your changes as a commit [not uploading a folder in the PR message]. Then create the PR from your working branch, not a random one.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Sepehr3987** [comment]
Hello,Could you please number each steps that I must do one by one?Thank you very much!From: DRVeylSent: Wednesday, April 13, 2022 10:01 PMTo: KSP-RO/RealismOverhaulCc: Sepehr Javeri; AuthorSubject: Re: [KSP-RO/RealismOverhaul] Updates to Bobcat's Mir RO Patch [CLOSE THIS PLEASE] (PR #2635) Uh. Why did you start this in the newComms branch? This PR doesn't have any of your commits.Please start with your fork of the repo, from the master branch. Apply your changes as a commit [not uploading a folder in the PR message]. Then create the PR from your working branch, not a random one.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Sepehr3987** [comment]
Hello,Could you please number each steps that I must do one by one?Thank you very much!From: DRVeylSent: Wednesday, April 13, 2022 10:01 PMTo: KSP-RO/RealismOverhaulCc: Sepehr Javeri; AuthorSubject: Re: [KSP-RO/RealismOverhaul] Updates to Bobcat's Mir RO Patch [CLOSE THIS PLEASE] (PR #2635) Uh. Why did you start this in the newComms branch? This PR doesn't have any of your commits.Please start with your fork of the repo, from the master branch. Apply your changes as a commit [not uploading a folder in the PR message]. Then create the PR from your working branch, not a random one.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Pull request closed without merging**
