### PR TITLE
RO squad engines update

### PR DESCRIPTION
**Pull request by PhineasFreak**
Note: still a WIP, do not merge yet.

* Update the Squad engines to the new centralized engine system.
* Update the global engine configs wherever required.
* Separated the LR-79 and H-1/RS-27 as per @SirKeplan (https://github.com/KSP-RO/RealismOverhaul/issues/939)
* General cleanup.

### CODE REVIEW

**Comment by SirKeplan** [comment]
Looking good, some things i noticed looking through the changes.

- ignitor resources: when i asked @NathanKell about the inconsistent use of fuel as an igniter resource on some engines, he suggested leaving them out entirely for the meantime(as the fuel consumption would depend greatly on the type and size of the engine)
- LMAE ignitions count: hmm another thing we need a source on
- What is the source on the new LMDE mass value? just averaging the two?
- Noticed you are adding helium to some hypergolic engines, not a criticism, just wondering what the rationale is.
- Crash tolerance and breaking tolerance etc(RD-253): looks like you deleted these, thid is consistent with other configs, but should we have these values specified for all engines in some way?
- do we want to include `!MODULE[ModuleJettison]{}` in the configs which you put it in, i assumed it would be better to leave this in the .cfgs for the mods?
- maybe include the ModuleAlternator bit in the NSTAR config?

Also, the Squad_Engines file is too big to review on github independently :P, though i realise we can look through the commits.

**Comment by stratochief66** [comment]
The RO_Squad_Engines.cfg changes need to be broken up, as currently there are too many changes in the one file to make it reviewable.

Personally, I am fine with the ignition data containing fuels right now, since the goal of this project at this stage is to move over what already exists in various RO configs into the new form. At a future time, we will be cleaning up ignitions and fuel amounts for restarts.

So @PhineasFreak, @SirKeplan I would say not to worry too much about getting those fuel resources for re-ignition precise, unless @NathanKell disagrees strongly with that.

**Comment by NathanKell** [comment]
It is easy enough to not copy them over, so I would say for consistency we should not use them for now, and instead let RF handle it (by starting up at low throttle/Isp). The startup resource requirement was a crutch, IIRC, to simulate low-Isp during engine start transient, but it's better to do that in RF itself.

**Comment by stratochief66** [comment]
@SirKeplan if there are too many changes to a file for it to show on the "Files Changes" page of a PR, I can't review it, so I can't merge it, simple as that.

**Comment by SirKeplan** [comment]
@NathanKell with not including fuel ignition resources, does that apply to the HTP in the RD-107 too? #934

**Comment by NathanKell** [comment]
@SirKeplan yes, no extra HTP should be spent for igniting the engine at the moment.

**Comment by PhineasFreak** [comment]
@SirKeplan good questions, let me adress them:

* I did not know that RF already covered the ignition resource situation. I will correct them as i go.
* A NASA document (see end of post) mentions that the ignition count for both LMDE and LMAE was 2. I assume that the 10 ignitions were set for game-play reasons.
* From the same document i got the inert mass. I am not sure though because different sources mention wildly different values.
* The pressure - fed engines by definition require a way for propellant pressurization. Helium is the mostly used noble gas for that application (used in way like the HTP in the soviet engines). I asked Nathan for that in the KSP forum and, judging from his reply, he agreed that we should implement that.
* Crash tolerances and breaking forces are already set by the "RealismOverhaul_Global_Config" to their respective values (or if it a copied part, from the parent one). I guess that we could specify custom ones but it should be then done for every part that RO supports and have standards for each category (engines, structural parts, ulitity, electrical etc).
* If a patch for ModuleJettison exists somewhere then i missed it and it should be removed ASAP. It glitches the engines badly...
* The NSTAR config is a bit hacky: it uses a ModuleAlternator with a negative output to simulate the electricity consumption for every throttle value. KSP cannot use ElectricCharge in a sane manner as a propellant resource (if you try then it ends like requiring absurd amounts of it).

I though that the reviewing was done via a git client and/or via a text editor. You are correct to indicate that you cannot view the changes via the web version of git but i do not know how to break it in smaller parts (that's why i was pushing them as separate PRs).

**Comment by SirKeplan** [comment]
@PhineasFreak ahah, that all makes sense then, didn't realise RealismOverhaul_Global_Config set the crash tolerances etc.

Yeah, there's no quick and simple way to split a PR, that's why i suggested doing it split into 2 or 3 before you made this one. oh well.

**Comment by NathanKell** [comment]
Apologies if I gave the impression that we should be, right now, including pressurization resource requirements for engines. We should not. Indeed, the tank masses for highly-pressurized tanks are set precisely so as to abstract the mass of pressurant. To start adding pressurant requirements to engines would mean I would need to change up RF's tank mass system.

Regarding ignition resources: I meant that RF can (it is possible) and RF should (I will do it soon) handle the low-Isp period of starting an engine. It does not do so now. But I still believe those IGNITOR_RESOURCE requirements should be removed for anything that is also a PROPELLANT.

**Comment by stratochief66** [comment]
@PhineasFreak bump, regarding turning this into multiple PRs so we can get started reviewing this?

**Comment by SirKeplan** [comment]
#967 for my edits to this.

**Pull request closed without merging**
