### PR TITLE
Sstu 0.4.31.111 updates

### PR DESCRIPTION
**Pull request by shadowmage45**
Major update pass to bring the SSTU patch set up-to-date with the most recent versions of SSTU.

Many patch details were provided by JoseEduardo as I have little knowledge about how most of these parts are setup or what most of the modules/etc actual do.

RF compatibility in SSTU is currently a little borked and will require an update to SSTU in order to function properly; this should be available here in a few hours / later today.

### CODE REVIEW

**Comment by Temeter** [comment]
Do I spot... an M1? The godliest of all engines? :O

**Comment by Temeter** [comment]
More coherent report:
Apollo CM starts with only MMH/NTO, but also needs Aerozine50 for its own thrusters.

**Comment by shadowmage45** [comment]
Please note - these are not my patches; I don't use RO and have no clue what the 'normal' setup is for these parts, I'm merely passing along a set of patch updates from someone else after cleaning up some of the more esoteric module related bits.

Have fixed reaction wheels (removed), fixed resources on Apollo/Orion parts, fixed M-1 engine definition, and cleaned up a few other miscellaneous bits for the Orion/Apollo patches.  Updated commits will be available momentarily.

The engine-mass thing appears to be a plugin-level conflict with ModuleEngineConfigs;  ModuleEngineConfigs appears to be adding mass to the part as well and I'm not sure if there is any way to turn off that feature.  Fixing that will require an update to one or both plugins (SSTU or RealFuels/ModuleEngineConfigs).

**Comment by shadowmage45** [comment]
Have also noted that the mount sizes aren't being properly calculated for the rescaled engines; this will need an update to the SSTU plugin.  Might take me a few days to get that end of things all fixed up.

**Comment by Temeter** [comment]
The stuff you do is effing amazing, just as it is that you push those RO configs. <3
Most of it works actually quite well.

Guess I'll ping the realfuels thread about those moduleengineconfigs.

**Comment by shadowmage45** [comment]
If there is not already a way with ModuleEngineConfigs to disable the mass adjustments, I should be able to add a simple config-level toggle to the SSTU module.  I think I may have had special handling for it before that got lost somewhere in the updating process.

Probably better to solve it at the SSTU module level anyhow, as ModuleEngineConfigs also deals with mass differences for the various engine variants.  Will just take me a few days to get it all updated, fixed, and tested;  until then probably best to just use the single engine parts.

**Comment by Temeter** [comment]
Alright! I'll continue to check stuff and report if I see something going wrong. ;)

**Comment by shadowmage45** [comment]
Have opened tickets on both of the problems to ensure they do not get forgotten about, you can track their progress from the links below:

Mount scaling/engine spacing - https://github.com/shadowmage45/SSTULabs/issues/317

Engine mass - https://github.com/shadowmage45/SSTULabs/issues/318

**Comment by ctiberious** [comment]
I noticed something with the Apollo and Orion CM (the versions with heat shields).  In both cases, if you attach something to their bottom attach point, fairings will appear but the fairings are too small (likely because there is no SSTUNodeFairing in your SSTU-SC-B-CM or SSTU-SC-C-CM sections).  I specifically noticed this when attaching something other than the Orion SM to the Orion CM.

**Comment by shadowmage45** [comment]
Have updated PR with fixes for the Apollo and Orion fairings as well as fixing the engine mount scaling/engine spacing problems (may require updated SSTU release for the spacing fix).

One more update to come:  Noticed that the mount sizes for the RD-107/8 and RS-68 engines do not line up properly, and that their module setup has not been updated for the single-engine-module setup.  Will hopefully have this cleaned up a bit later this evening.

Will be publishing an updated SSTU release shortly with the fixes for the mass and cleanup to engine spacing handling.

**Comment by Temeter** [comment]
Can confirm, with newest SSTU and RealFuelf multi mounts seem to have correct mass! Mount sizes also work better, getting the F1 up to 5 engines now gets the same size as the pre-made Saturn lower stage engine cluster. Awesome!
Pricing in RP-0 is still a bit off, multi-F1 stays at 5k no matter how many engines, H-1/RS-27 grows exponentially.

Another matter, since i've added SSTU to RP-0: Would you mind me adding clones of your AJ10-190 for RO's generic AJ10-Early/Medium/Advanced engines?
It's a nicer model than the only alternative, and the clustering ability would be hugely helpful in RP-0 early and lategame.

**Comment by shadowmage45** [comment]
Feel free to use the engine cluster module/plugin for whatever purposes you want;  likely a few other users that wouldn't mind easy clustering of other mods' engines.  The existing configs/patches should have all the examples you need to put them together.

Models -- as long as it is just patches for when SSTU is already installed, then sure, go for it.  If it is intended for stand-alone redistribution there are licensing concerns (CC-BY-NC-SA);  but for just a set of patches to rescale/rename things you should be good to go as-is.

**Comment by Temeter** [comment]
Thanks! :D
Nah, it's literally just a config-file for RO/Suggested/SSTU. It creates clones using the models of the 190 to be used as the generic AJ10 variants. I made them more for myself to check out if it works, but I think they might be usefull to others as well.

Just wanted to make sure you're ok with adding more stuff to the RO patch for your mod. It's visible how much work goes into that stuff, would feel a bit like a sacrilege to me to just clone parts without asking.

**Comment by ctiberious** [comment]
Not sure if you've looked at it, but SSTU_Landers.cfg has some issues.  For starters, it refers to a part labeled "SSTU_LanderCore_LC2-POD" which doesn't exist in SSTU.  Instead, that part is "SSTU-LC2-POD" (likely the result of naming convention changes).
Also, the scaling for the RCS parts, the position for RCS and Docking Ports, and the node_stack_top value on "SSTU-LC2-POD", "SSTU_LanderCore_LC3-POD", and "SSTU_LanderCore_LC5-POD" needs to be corrected.
There also seem to be a lot of parts being referenced that I can't actually find (though maybe I'm just looking in the wrong place).  Not sure if they are deprecated, simply need updated part names, or if these are "place holders" that have been temporarily been removed from SSTU.  Here's the list:
SSTU_LanderCore_LC2-DESE
SSTU_LanderCore_LC3-DESE
SSTU_LanderCore_LC5-DESE
SSTU_LanderCore_LC2-ASCE
SSTU_LanderCore_LC3-ASCE
SSTU_LanderCore_LC5-ASCE
SSTU_LanderCore_LC1-FL0-HH
SSTU_LanderCore_LC2-FL
SSTU_LanderCore_LC3-FL
SSTU_LanderCore_LC5-FL
SSTU_LanderCore_LC-DC3
SSTU_LanderCore_LC-DC5
SSTU_LanderCore_LC2-CRG
SSTU_LanderCore_LC3-CRG
SSTU_LanderCore_LC5-CRG

Finally, it looks like "SSTU_SLS_Upper_Stages.cfg" needs to be updated to account for some recent part name changes.  The file is still referencing "SSTU-SC-B-ICPS" and "SSTU-SC-B-HUS".

**Comment by shadowmage45** [comment]
I do not have the kind of time necessary to go through every file, nor do I even know how most of those parts are intended to be setup.  I was submitting this PR as a favor for another user (who got yelled at last time he tried to help through submitted a PR).

If someone else would like to pick up from here, feel free to grab the existing commits/data from the forked branch; I will not be making any further contributions.

**Comment by Theysen** [comment]
@ctiberious As far as HUS and ICPS go I already did and the changes got merged

**Comment by Temeter** [comment]
Why not just leave it open for someone to merge? Everything seems to work fine.

**Comment by shadowmage45** [comment]
I have no problem if someone wants to merge this in; but it will have to be with the foreknowledge that not everything is fixed/working 100%, and that I have no intentions of touching any of the other files (I do not use RO and have zero knowledge of how those parts are intended to be used in it).

**Comment by Temeter** [comment]
Anyway thanks for the stuff you did!

**Comment by ctiberious** [comment]
Didn't mean to rock the boat.  I just saw some issues with files you were peripherally working with and figured I'd point out what I noticed rather than submit my own PR.  I'm just as willing to setup my own PR for the SSTU_Landers.cfg issues and anything else I happen to come across that hasn't already got a PR.  No worries, @shadowmage45 I fully understand only having so much time to do stuff.  :)  At least the changes you've done here are ready to be committed.

**Comment by stratochief66** [comment]
It seems to test out as a Substantial improvement over the old configs, as SSTU has changed substantially since the current set of patches were last touched.

Thanks @shadowmage45 & @FFCJoseEduardo for the patches! We look forward to both of your future work (Shadowmage with SSTu, JoseEduardo with help on RO patches)

**Comment by stratochief66** [comment]
@ctiberious @Temeter of you want to make (Or add to) an RO 'Issue' page with the still remaining issues you noted, that would be appreciated as it would help with future RO patch improvements. Or, better yet, make a PR for them :)

**Comment by FFCJoseEduardo** [comment]
@ctiberious landers have been mostly deprecated a few releases ago due to 1.1 incompatibilities, and ICPS and HUS can be mostly re-created with the current MUS ST tank and RL-10 engines, so not exactly a #1 priority...

**Comment by Temeter** [comment]
No PR, i've got no clue how that stuff works.^^
Next thing I gonna do is fix and add the remaining plumes, add the last stuff to RP-0. Hit some issues I need to figure out there.

**Comment by ctiberious** [comment]
@FFCJoseEduardo I figured that is what happened.  I've been messing around with the Landers as a possible solution for the mars mission I'm working on in my current game (I really like the way those look).  Have to make them work in RO first, though.  Once I've validated that my adjustments work, I'll clean up SSTU_Landers.cfg and submit a PR for it.

**Pull request merged**
