### PR TITLE
Rescaled FASA IVA's for RO

### PR DESCRIPTION
**Pull request by cytosine**
FASA command pod IVA's now look good for RO.

Also fixed a few model problems with the Advanced Gemini Lunar Lander pod.  It's defined RO scale size wasn't being applied to the model and after that was fixed the scale was way too big.  Fixed the bug and then set the scale to x1.6 which looks nice.

My apologies if this FASA-RO pull request conflicts with the previous Squad-RO one I submitted.  I tried 'branching' as one of you suggested, but I think I did it wrong...

### CODE REVIEW

**Comment by NathanKell** [comment]
Can't tell from the diffs, but it looks like this might be colliding with some of the changes @ctiberious made to the Big G?

**Comment by cytosine** [comment]
Yeah, I see it now.  I must have been working off a branch just prior to his being merged is my guess?  The areas where his stuff conflicts with mine were not things I changed (at least I don't remember touching them).  What's the easiest way for me to grab his stuff and merge it with mine?

**Comment by cytosine** [comment]
Doesn't look like there are too many differences, so should I just manually update my files with his differences?

**Comment by SirKeplan** [comment]
Yeah you seem to accidentally have a lot more in this PR than should be here.

Try switching to master, pulling the latest upstream changes, then make a new branch and cherry-pick the commit that does your FASA tweaks.
```
git checkout master
git pull upstream master
git checkout -b RO-FASA-IVAs2
git cherry-pick <commit>
```

**Comment by ctiberious** [comment]
My changes were lines are in RO_FASA_BigG.cfg.  Lines (after your changes) 432 (though you adding "Big Gemini" is good), 479, 496 & 497, 503 & 504, 510 & 511, 517 & 518, 685, and 690.  And in RP_FASA_Gemini_Pod.cfg, line 470.

**Comment by cytosine** [comment]
I don't seem to have 'upstream' defined.  Am I configured properly?

**$ git pull upstream master**
fatal: 'upstream' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
**$ git remote -v**
origin	git@github.com:cytosine/RealismOverhaul.git (fetch)
origin	git@github.com:cytosine/RealismOverhaul.git (push)
**$ git status**
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean

**Comment by NathanKell** [comment]
Yeah, you'll need to manually add a remote for this repo's .git (and call it upstream, maybe). IIRC forks don't have them by default.

**Comment by jwvanderbeck** [comment]
In many cases if things get wonky I find it easier to just delete my fork and refork it.

**Comment by cytosine** [comment]
Ok, I did "git remote add upstream https://github.com/KSP-RO/RealismOverhaul.git" and will try to recover this little mess from there...

But I agree with @jwvanderbeck that the 'nuclear option' is always a friendly, safe and highly efficient solution!  heheh...  ;)

**Comment by cytosine** [comment]
@SirKeplan,

So when you say "git cherry-pick <commit>" do you mean the BigG commit from @ctiberious or the commit with my own fixes?

Thanks.

**Comment by cytosine** [comment]
All, I *think* I was able to cherry-pick my way out of this.  Created a new branch "RO-FASA-IVAs2" as @SirKeplan suggested, so I'm going to close this PR and work on a new.  (Fingers crossed!)

**Comment by SirKeplan** [comment]
@cytosine yeah i meant to cherry-pick the commit with the bits you made, make sure you do this while on a clean copy of master.

**Pull request closed without merging**
