### PR TITLE
Add Schnobs/NK suggested fairing changes

### PR DESCRIPTION
**Pull request by stratochief66**
Add Schnobs/NK suggested fairing changes

Makes a shorter version of the fairing base.

Makes fairing mass closer to 8mm aluminum instead of 20mm

### CODE REVIEW

**Comment by stratochief66** [comment]
Don't merge yet, I'm adding allthechanges.

**Comment by PhineasFreak** [comment]
Would be possible to change the pass from final to a more "mod a mod" friendly one? Like "zzzRO" or something similar?

**Comment by NathanKell** [comment]
I agree on the pass. Also we need to target the PFFE fairing/interstage bases and fairing sides. Might be worth targeting by module rather than partname.

**Comment by NathanKell** [comment]
@stratochief66 I think it's safe to go by module, although we then need to vary it for the flatter interstage I guess.

**Pull request merged**
