### PR TITLE
More WF for Raidernick's mods

### PR DESCRIPTION
**Pull request by vevladdd**
I think this mod really needs this. 
Done/To be done:

- [x] Dnepr
- [x] Zenit
- [x] R-7 family
- [x] Kosmos-2
- [x] Kosmos-3
- [x] Tsyklon
- [x] Fregats (Sound of the engine and RCS is broken. Looks like nobody knows what is wrong here (or nobody cares))
- [x] Block L 
- [x] and of course, eN ONE (N-1)

### CODE REVIEW

**Comment by siimav** [comment]
Please use a text editor that allows you to differentiate between tabs and spaces.

**Comment by vevladdd** [comment]
> Please use a text editor that allows you to differentiate between tabs and spaces.
Thanks, I'll do that

**Comment by raidernick** [comment]
Thank you for doing this. I started it a while back but RL got too busy and I don't really have time for KSP these days. So I appreciate someone doing this.

**Comment by vevladdd** [comment]
Currently on hiatus due to RL things and War Thunder (I'm sorry for the latter). I hope I'll continue soon. 

Feel free to add/change/fix smth here, if ypi want to. 

You can send the files here (I hope it is allowed by the repo rules), to the discord, or, if you have rights to do so, edit directly here.
 
I must have checked "Allow edits for maintainers".

I think that Soviet Spacecraft, (US) Probes, Stations and US Rockets can also go here.

**Pull request merged**
