### PR TITLE
RSB Engines

### PR DESCRIPTION
**Pull request by PhineasFreak**
These were already stashed before merging but i forgot to push it.

* Decrease the gross mass of the AJ-60A SRM to include the mass of the
SRM decoupling kit.

### CODE REVIEW

**Comment by PhineasFreak** [comment]
Renamed due to the addition of the F-1B and the RL10B-2 engines.

**Comment by PhineasFreak** [comment]
And again because of the RS-68 and the GEM-60.

**Comment by stratochief66** [comment]
https://github.com/KSP-RO/RealismOverhaul/pull/915/files#diff-6bb525f6473232cc4d068d711eccdc83R68

This gives them ~90 tons of fuel a piece, which is roughly 3x what they should have. Where did those numbers come from?

**Comment by PhineasFreak** [comment]
I multiplied the propellant mass instead of dividing it (by 1.77). Fixed.

**Comment by stratochief66** [comment]
i recall an engine throttling far more than I expected that it should. I don't recall offhand which one it was though. Was it possibly because of this?: 
https://github.com/KSP-RO/RealismOverhaul/pull/915/files#diff-6bb525f6473232cc4d068d711eccdc83R899

**Comment by PhineasFreak** [comment]
These are just templates, they do not do something (dummy parameters).

**Pull request merged**
