### PR TITLE
Took a stab and performing the format conversion for TACLS

### PR DESCRIPTION
**Pull request by rsparkyc**
Some minor notes: numbers should now be properly formatted (0.01 vs 0.010), and booleans start with a capital (True vs true)
This was done in response to the comment made by @PhineasFreak here: https://github.com/KSP-RO/RealismOverhaul/issues/1436

### CODE REVIEW

**Comment by PhineasFreak** [comment]
Well...that's the whole thing done i guess! Although the formatting of some of the patches is really off:

https://github.com/KSP-RO/RealismOverhaul/blob/e33506a2a219655e045a9deff3d19ba74c265dd0/GameData/RealismOverhaul/RO_SuggestedMods/CST/RO_CST_Command.cfg#L263-L310

Some of the patches use spaces and other tabs for the whitespace.

Also, i have updated the CMES parts already in their respective PRs so you can remove them from this one.

**Comment by rsparkyc** [comment]
Good catch on the formatting, I'll update my script to see if we should be tabbing or spacing the indents and update the PR.  I'll also remove the CMES parts (I'm assuming that's just RO_CMES_Hab and RO_CMES_Pod)

**Comment by PhineasFreak** [comment]
For CMES, the Hab, Pod and Structural configs are already taken care of.

Again, awesome work!

**Comment by rsparkyc** [comment]
Glad I could help.  I actually missed the Structural one, as my script didn't pick up that it needed the change due to some mixed space/tabs.  Going to give in another once over and make sure that I didn't miss anything, but I'll push up what I've fixed for now.

**Comment by rsparkyc** [comment]
Ok, the only other thing I see is in GameData/RealismOverhaul/RO_RecommendedMods/TACLS/RO_TACLS_Tanks.cfg.  There are some things there annotated with `@`, should those be updated too?

**Comment by PhineasFreak** [comment]
There are some open PRs for the TACLS parts themselves. I guess that these are OK and don't need any updates?

**Comment by rsparkyc** [comment]
Ahh, yeah, I see those now.  Looks like there's 2 different formats for the resources?
https://github.com/KSP-RO/RealismOverhaul/pull/1447/files  Some have INPUT_RESOURCE, while others have INPUT_RESOURCE[name]

**Comment by PhineasFreak** [comment]
Some of the INPUT_RESOURCE and OUTPUT_RESOURCE fields already exist so we have to just edit them (@). Others are new (more input/output resources) so we add them.

**Pull request merged**
