### PR TITLE
RO Squad Aero updates

### PR DESCRIPTION
**Pull request by PhineasFreak**
* Add RO support for the inflatable heat shield.

### CODE REVIEW

**Comment by NathanKell** [comment]
My understanding is that FAR does not support it, and therefore we do not either...

**Comment by jwvanderbeck** [comment]
Did porkjet not get that collider fixed? I remember talking to him about it.

**Comment by NathanKell** [comment]
Not in 1.1.3 to my knowledge.

**Comment by PhineasFreak** [comment]
I thought that it was supported...well, forget it then.

**Comment by NathanKell** [comment]
Sorry! :(

**Comment by PhineasFreak** [comment]
Hmm, could we include it as a patch for a future version but tag it as WIP or NON RO?

**Pull request closed without merging**
