### PR TITLE
Create RO_InfernalRobotics.cfg

### PR DESCRIPTION
**Pull request by winged7**
Support for IR parts. They don't require any changes.

### CODE REVIEW

**Comment by NathanKell** [comment]
They don't? Aren't they rather heavy for what they do?

**Comment by winged7** [comment]
I think, it's ok.

**Comment by stratochief66** [comment]
@winged7 

Could you quote some of the masses of the IR parts? I haven't personally used the mod. That would give us an idea if we should suggested the mass staying the same, or being halved, or a guideline somewhere along those lines.

**Comment by winged7** [comment]
AdjustableRailScaleable  mass = 0.2
Docking Washer mass = 0.025
Docking Washer Standard (Free Moving) mass = 0.025
Gantry Rail  mass = 0.8 ( huge part, 10meter long)
Gantry Rail Variant mass = 0.8
Closed Powered Hinge mass = 0.1
Open Powered Hinge mass = 0.1
Powered Hinge mass = 0.1
Powered Hinge 90 degrees mass = 0.1
Hydraulic Cylinder mass = 0.1
IR Rotatron mass = 0.1
IR Rotatron Mk2 mass = 0.1
VTOL Rotor Mk1 mass = 0.1
Telescopic Piston mass = 0.2

**Comment by NathanKell** [comment]
Yeah, those sound way too high for probe use...100kg is like half the mass of Ranger, where the hinges would be used for the foldout solar panels...

**Comment by winged7** [comment]
So how much they need to be lighter? 2x , 3x or 5x? :>

**Comment by NathanKell** [comment]
Depends on their size I guess. Certainly I wouldn't expect hinges sized for the RO Ranger cores to be heavier than about 5kg each, but it's worth a half-hour's google into hinge weights, probably, and also depends on how large the hinges default to (since IIRC Infernal Robotics uses TweakScale to allow resizing the hinges?)

**Comment by winged7** [comment]
yep, it uses tweakscale.

**Comment by winged7** [comment]
I will back to this topic later, closed for now.

**Pull request closed without merging**
