### PR TITLE
DECQ's Energia boosters updated to RG-1

### PR DESCRIPTION
**Pull request by LuneoLucy**
Removed kerosene and replaced it with RG-1, all thanks to previous contributor for preparing the update

### CODE REVIEW

**Comment by Capkirk123** [comment]
Have you tested if this actually works?

**Comment by LuneoLucy** [comment]
yes I did, nothing wrong for me, performances are good and tank utilization too with only a few hundred liters not used (more rcs fuel maybe?)

**Comment by NathanKell** [comment]
Please give this a proper name and description, thanks!

**Comment by LuneoLucy** [comment]
Done! 👍

**Pull request merged**
