### PR TITLE
RO Squad Wheel updates

### PR DESCRIPTION
**Pull request by PhineasFreak**
* Fix the electricity consumption of the wheels
* Tweak the electricity consumption of the landing gear lights.

### CODE REVIEW

**Comment by NathanKell** [comment]
Uh, maybe I'm confused about what the numbers mean, but is that really saying the TR-2L wheels draw less electricity than most light bulbs?

**Comment by PhineasFreak** [comment]
I could increase it even further, say like 55 - 60 W? It was 1 W before the patching though.

**Comment by NathanKell** [comment]
Yeah, I just find it super odd that a large electric motor driving a wheel draws so little. At, say, 15m/s, what do the TR-2Ls draw? And is that similar to 1/4 what a Prius draws at 15m/s / 33mph / 54kph ?

**Comment by PhineasFreak** [comment]
Testing a 4 - wheeled rover around 10 - 20 m/s i get a consumption of 90 - 100 W (as expected).

Now, to modify the top speed since it can easily exceed 50 m/s! I assume that the "wheelSpeedMax" controls the maximum speed that the wheel can reach, right?

**Comment by NathanKell** [comment]
A Chevy Volt at highway speed (~32m/s) uses ~5kW for its four wheels. So I think we need to increase by an order of magnitude. I would suggest the TR-2Ls and the medium Rovemax should be about 1kW each at ~30m/s, and the large ones probably more like 10? Dunno about them. The tiny wheels, now, for _them_ 90-100W makes sense.

**Comment by PhineasFreak** [comment]
I was thinking about cutting the top speed of the larger wheels down to 10 m/s and set the small ones to 2 - 4 m/s. Right now they do not feel exactly like "rover wheels".

The S2 wheels have similar size to the MSL wheels (0.3 m vs 0.5 m). The MSL RTG provides up to 120 W of power for all systems so 6 of these should not require more than 7 - 9 W.

**Pull request merged**
