### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by jeremy-penn**
Fixed a typo on line 678.

Nightcat on discord.

### CODE REVIEW

**Comment by PhineasFreak** [comment]
Approved the change, although you changed something in the file (line endings?) that caused GitHub to show the whole file as being modified.

**Comment by jeremy-penn** [comment]
Very much apologize for that. It will not happen again.

**Comment by raidernick** [comment]
@jeremy-penn you can still fix it, I would prefer if you did as I keep track of all pr changes and a change like this is useless as looking back on it gives no info on exactly what was changed

**Comment by jeremy-penn** [comment]
@raidernick I absolutely will fix it. Is there a way to do that in this pull request or do I need to open a new pull request with a corrected file? Notepad++ seems to have added an empty line at the end of the file I originally uploaded. I'm super sorry for messing it up.

**Comment by jonesmz** [comment]
@jeremy-penn In your git repository on your local machine, re-make your patch, and then use git commit --amend to modify the previous commit. Then "git push -f" will force-rewrite the contents of this pull request on github.

**Comment by jeremy-penn** [comment]
@jonesmz thank you for the help. I hope I have fixed it correctly now. Again, I apologize for the mistake.

**Comment by jonesmz** [comment]
@jeremy-penn I'm not sure the commit rewrite worked. 

When it's successful, you'll see all of the commits that are currently in this pull request on github go away (There are 3) and be replaced by just your one single commit.

Alternatively, you could close this pull request, and implement your change in a different branch, and try again.

It looks like your editor is changing line endings.

**Pull request closed without merging**
