### PR TITLE
RW8 Reaction Wheel Settings

### PR DESCRIPTION
**Pull request by rsparkyc**
This reaction wheel was showing 0 torque in the UI, not it shows up as having 0.1 Nm max torque

### CODE REVIEW

**Comment by stratochief66** [comment]
Newton-Metre (N*m) vs Kilonewton-meter (kN*m) ? My recollection is that the torque was listed in kN *m, just as the thrust is shown in kN. I could of course be mistaken.

**Comment by rsparkyc** [comment]
Ahh, no you are totally right. Now that i look the Reaction Wheel window has it listed in `kN` and not `Nm`.  Man, this thing is useless.

**Comment by rsparkyc** [comment]
I updated the PR to only update the data sheet, since the last one had a 404

**Comment by stratochief66** [comment]
It shows how preposterously overpowered reaction wheels are in stock. They are really just used on small-ish satellites. I wish it weren't so, but it is. Dealing with no reaction wheels seems to be one of the greater challenges of going from stock to RSS/RO.

**Comment by rsparkyc** [comment]
yeah, I would consider this a small satellite though, just a ranger III block core, some antennas, and solar panels

**Pull request merged**
