### PR TITLE
Adding the Space Transportation Main Engine to the RS-25

### PR DESCRIPTION
**Pull request by Ash19256**

### CODE REVIEW

**Comment by Ash19256** [comment]
This is just me posting this pull request for Scorpu on the RO Discord. It adds a gas generator version of the RS-25 SSME, intended for expendable rockets.

**Comment by vader111** [comment]
Theres no need to create a engine config for the STME, i have already created one that has been merged with master

**Comment by Ash19256** [comment]
One, I didn't create this, Scorpu on the RO Discord did. Two, your STME configuration appears to be in use with no parts that I am aware of - thus, this configuration edits the SSME config to add the STME as an available configuration.

**Comment by vader111** [comment]
@Ash19256 thats true, but instead of writing out a config, you just need to attach the engine config to the engine you want it on

**Comment by siimav** [comment]
Ideally someone would create a model similar to SSME but with gas generator hardware and we'd add that to ROEngines

**Comment by vader111** [comment]
even better idea, since yes it is a gas generator engine and bigger then the rs 25

**Comment by pap1723** [comment]
I don't agree with the numbers here. According to the official NASA studies on it, which can be seen here: https://www.alternatewars.com/BBOW/Space_Engines/STBE_STME-481_Details.png

It should be more like this:
Max Thrust = 2139.59
Vac ISP = 461
SL ISP = 380.4

**Comment by vader111** [comment]
@pap1723 Bit different then what i found on the engine 
https://www.alternatewars.com/BBOW/Space_Engines/STME_Data_Excerpt.pdf
http://www.astronautix.com/s/stme.html

**Pull request closed without merging**
