### PR TITLE
RO RSB Atlas V

### PR DESCRIPTION
**Pull request by PhineasFreak**
* Add RO support for the Real Scale Boosters Atlas V (only for the 401 version for now).

### CODE REVIEW

**Comment by PhineasFreak** [comment]
Please hold this a bit before merging so that i can include all the Atlas V parts.

**Comment by PhineasFreak** [comment]
And with that last patch all Atlas V parts are RO - compatible.

Note: there are some separation issues regarding the 5.4m fairings, even with the high ejection force.

**Comment by stratochief66** [comment]
Let me know when you are done adding to this so I can test it

**Comment by stratochief66** [comment]
Also, which other unmerged PRs this relies on

**Comment by PhineasFreak** [comment]
For the Atlas specifically, the only thing that is suggested (not a hard dependency) is the AJ-60A inert mass fix by https://github.com/KSP-RO/RealismOverhaul/pull/915, otherwise there are none.

**Pull request merged**
