### PR TITLE
Universal Rocket Engines

### PR DESCRIPTION
**Pull request by Capkirk123**
Add UR-200 first and second stage engines, and UR-100 first stage engines

### CODE REVIEW

**Comment by siimav** [comment]
The reliability PR caused conflicts in this one

**Comment by Capkirk123** [comment]
Conflicts resolved

**Comment by siimav** [comment]
Noticed some of the `techTransfer` lines are misaligned

**Comment by Capkirk123** [comment]
Config formatting should be fixed now

**Pull request merged**
