### PR TITLE
DRE heat shields category

### PR DESCRIPTION
**Pull request by PhineasFreak**
* Move the DeadlyReentry heat shields from the "Structural" category to the "Aero" category for better organization.

### CODE REVIEW

**Comment by PhineasFreak** [comment]
As requested by @SirKeplan: https://github.com/KSP-RO/RealismOverhaul/issues/735

**Comment by Zarbizaure** [comment]
Cool move! I suggested it somewhere on the RO github some days ago, it makes sense to have all the heat shield at the same place.
And: any idea on how we could make the procedural heat shield work with the new charred Ablator system?

**Comment by PhineasFreak** [comment]
Fixing the heat shield parameters for the new heating model is not a difficult task but setting the correct values for the mass curve and the Ablator per area might be.

**Comment by Zarbizaure** [comment]
It would be cool to have a single procedural heat shield with (or three) modes (with a switcher conttrol): LEO-rated, lunar-rated and Interplanetray-rated (a bit more resistant than the lunar one, just to be sure you can survive a mars or venus return).
Yet I have no idea how to do that.

**Comment by PhineasFreak** [comment]
I made some changes and adjusted it to match the DRE LEO - rated heat shields. This fixed the Ablator amount but it seems like it is not possible to actually add the CharredAblator without some PP code changes.

The switcher must be implemented by PP, nothing we can do from the RO side.

**Comment by PhineasFreak** [comment]
Small update to remove the 0.625m heat shield decoupler from the available parts (the DRE heat shield decouplers support TweakScale).

**Pull request merged**
