### PR TITLE
CMES Update & more

### PR DESCRIPTION
**Pull request by PhineasFreak**
Change Log:

*	[BAHA]	Added support for the BahamutoD Atlas V parts (RD-180 engine & AJ-60A, thanks A1Ch1).
*	[CMES]	Updated inflatable heat shields. They come in 10, 15 and 20 m diameters.
*	[CMES]	Each procedural fairing now has a different density (mirroring different construction materials).
*	[CMES]	Fairing bases now come in two variants: a normal PF base ring and a NovaPunch low profile base ring.
*	[CMES]	Updated some generic parts (ladders, RCS ports, struts).
*	[CMES]	Added a generic retractable radiator array (thermal capacity 1.5 kW).
*	[CMES]	Added an engine support truss for the Delta IV DCSS.
*	[CMES]	Added the solar arrays for the HTV resupply vehicle.
*	[CMES]	Updated all the Orion parts (Service Module, RCS thrusters, main engine & solar arrays.
*	[CMES]	Added the Multi - Mission Space Exploration Vehicle (MSEV) crew cabin and chassis.
*	[CMES]	Added the Common Berthing Mechanism (CBM).
*	[CMES]	Added the NASA Docking System (NDS). Compatible with the stock NDS.
*	[CMES]	Added a Surface Docking Mechanism (SDM) for landed habitation modules. Uses the "NASADockSurf" node name.
*	[CMES]	Updated the large cupola module.
*	[CMES]	Updated the configurations for the Altair lander (might still need some tweaking regarding the dry & propellant masses).
*	[CMES]	Updated the configurations for the "Altair II" Mars lander.
*	[CMES]	Updated the GEM-60 (thanks A1Ch1).
*	[CMES]	Updated the 4 & 5 - Segment RSRMs (thanks A1Ch1).
*	[CMES]	The NERVA engine now features Bimodal and Trimodal operation (BNTR and TRITON).
*	[CMES]	Added the RD-275 engine and it's variants.
*	[CMES]	Updated the RS-68 engine and it's variants.
*	[CMES]	TAC Life Support patches are now separate from the main RO configurations.
*	[FASA]	The FASA Agena engine now supports the Bell 8096 & Bell 8096-39 configurations.
*	[FASA]	Fixed the FASA Apollo CM tank volume.
*	[SXT]	Added the strongback trusses for the ASIMOV Mars Transfer Vehicle (might duplicate them for the larger diameter COPERNICUS).
*	[SQUAD]	FIxed a bug with the Squad MK3 Passenger Module node placement.

Note 1: All engines are supported by RealPlume.
Note 2: Due to a bug with the "TacGenericConverter" module, Altair ascent & descent modules start with their engines activated on launch.
Note 3: Some duplicated parts are disabled. They can be found on the top of each configuration file.

### CODE REVIEW

**Comment by stratochief66** [comment]
An absolutely MONSTER contribution, thanks!

It will take me a while to review this though. I will quite likely merge it, barring any huge bugs I find, but I will put together some notes on things that may need changing in a future PR to fine-tune this one.

**Comment by stratochief66** [comment]
In general, when a mod seeks to replicate specific complex craft, it is awesome if you can include *.craft files and or subassemblies. For instance, I couldn't figure out a nice way to connect the Altair upper and lower stages.

**Comment by stratochief66** [comment]
Altair - I notice the Altair II lower stage doesn't have enough delta-V to perform the lunar capture burn as the Altair was intended to do. This takes about 700 m/s with the combined mass of the Altair & Orion.

**Comment by stratochief66** [comment]
I noticed there were no new RealPlume configs added in this PR. They are fairly easy to do, I can help someone to get started on them sometime if you like. I made a few for CMES a while back during an abortive attempt to configure for Areas and SLS.

https://github.com/KSP-RO/RealismOverhaul/tree/master/GameData/RealismOverhaul/RealPlume_Configs/CMES

**Comment by stratochief66** [comment]
The MSEV crew cabin has a disproportionately low mass for its crew capacity and size. It is as large as the Altair upper stage or Orion, but weighs about 1/10th. I don't know what part or function this is meant to fill in or replicate, but at the very least it should weigh 5 tonnes or so?

**Comment by stratochief66** [comment]
The Orion capsules look quite good. However, the service module fairings and service module decoupler haven't been resized to fit. They appear to be at 4m max size, where they should be 5m.

The way the Orion capsules look, I would expect that the capules have the heatshield baked in. However, they don't appear to have any ablator. Have you considered baking the heatshield data in like I did for the FASA Apollo?

https://github.com/KSP-RO/RealismOverhaul/blob/master/GameData/RealismOverhaul/RO_SuggestedMods/FASA/RO_FASA_ApolloCSM.cfg#L344-L371

**Comment by stratochief66** [comment]
Core Stages: The AresV engines don't gimbal (that one broke me, I confess. I couldn't figure it out myself) The SLS core has a massive reaction wheel, and also no gimballed thrust or engines.

**Comment by stratochief66** [comment]
@A1Ch1 @PhineasFreak 

I think that is all the bugs I found while reviewing, I'm ready to merge now. Anything else you want to point out or look at before that?

Do you think you could look at a few of the things I mentioned for a future patch? All of the improvements you've included here are very substantial.

**Comment by PhineasFreak** [comment]
*  I did not think about including craft or sub-assemblies, mea culpa...
*	For the Altar Lunar Lander, i removed the built-in decoupler that originally came with CMES because it is impossible to check the available delta - V. Any decoupler will do the job, attaching it at the top node of the Altar DM (a procedural one is the best).
*	Altair II is only designed for Mars landing (and only for final braking before touchdown). I just came up with the name since it is even more "in concept" than the original Altair. It came from the "Mars in Six Pieces" Boing demonstration: http://chapters.marssociety.org/winnipeg/files/Raftery_5-14-14.pdf. It does not support anything beyond that for now. We can change that so to be possible to use it in other applications.
*	I tested the landing legs and they work. They are modeled using the legacy HLandingLeg module so it is possible that they are just buggy.
*	I was also considering replacing the TAC converter for the Altair DM with the stock ModuleResourceConverter to circumvent the TAC bug.
*	It is weird that you don't have plumes. I have made plume configurations for every engine (except from the RL-60 and the Ares V Core Stage). Are they not included?
*	The MSEV config at best is "make the best guess". I tried to keep it reasonable with the rest of the parts (the wheels and the chassis) but it still requires some more work. Source: https://www.nasa.gov/pdf/464826main_SEV_FactSheet_508.pdf
*	I have not touched yet the other Orion hardware, since some of the functionality (for now) can be replicated with PF. I will update them due time. Some parts are hollow and will require custom drag cubes, something that i have not yet mastered. 
*	I have included heat shields for Orion capsules. Each one has about 1500 Kg of ablator (just a guess). I think Nathan had reviewed them in my first PR. Link 1: https://github.com/KSP-RO/RealismOverhaul/blob/master/GameData/RealismOverhaul/RO_SuggestedMods/CMES-WIP/RO_CMES_Pod.cfg#L682-L693, Link 2: https://github.com/KSP-RO/RealismOverhaul/blob/master/GameData/RealismOverhaul/RO_SuggestedMods/CMES-WIP/RO_CMES_Pod.cfg#L900-L911
* The Ares V Core Stage broke with the 1.0.0 update, we cannot do something about that. YANFRET had the same problem with his mod.

The parts that i have not yet touched are either out of my gasp (drag cubes as i mentioned) or not used at all (all the fuel tanks). Also YANFRET will make some changes in the next version for 1.0.5 and i am holding back some more patches because of that.

Thank you very much for your time!

**Comment by stratochief66** [comment]
@PhineasFreak 

All seems good then for a merge. The Altair really should have a bit more delta V though, I am working on Altair components for SSTU so I might put in a PR later to tweak these values so it can perform the lunar insertion burn.

Thanks for the quick response! CMES is such a huge pack with so many parts, it is pretty much impossible to RO the whole thing. Your 60 odd commits bring it a long way!

**Comment by PhineasFreak** [comment]
And still there is a lot to be done! I can foresee asking for some help with some of the remaining parts...

Again, thank you very much for your help!

**Pull request merged**
