### PR TITLE
RO RSB Ariane 5

### PR DESCRIPTION
**Pull request by PhineasFreak**
* Add RO support for the Real Scale Boosters Ariane 5.

This requires the RSB engine changes (https://github.com/KSP-RO/RealismOverhaul/pull/1008) for the SRM, the HM-7 and the Vulcain engine and, optionally, the HM-7 engine config update (https://github.com/KSP-RO/RealismOverhaul/pull/1006) for the ullage and ignition simulations.

### CODE REVIEW

**Comment by PhineasFreak** [comment]
These were on the backlog for some time (had some health issues) and did not manage to get them ready in time. But they are now!

**Comment by NathanKell** [comment]
Ah! Had wondered what happened to you, hope you're doing better!!

**Comment by PhineasFreak** [comment]
Yes, i am better now, thank you! Although i feel somewhat bad because i left @SirKeplan alone to finish the mess i caused with the engines...

**Comment by SirKeplan** [comment]
Oh, heh don't worry it it @PhineasFreak , glad you are feeling better and back with us :)

**Pull request merged**
