### PR TITLE
Renaming for standardization/commonality - Other Fixes

### PR DESCRIPTION
**Pull request by RedAV8R**
Title only. One description changed for added information.

### CODE REVIEW

**Comment by NathanKell** [comment]
Um, with the Manufacturer property available why are you also adding it to the title? I thought the idea was that we'd shift Manufacturer name to the manufacturer field, and then have just the actual designation in the title...

Sorry if I missed something...

**Comment by RedAV8R** [comment]
No...didn't miss anything.

Half or more had the manufacturer in the title, half didn't. I went the way that seemed more descriptive. Manufacturer and model.

So...

Sure the manufacturer is now in the manufacturer field. In KSP basically allowed searching via manufacturer in the parts list, if a couple other things were properly set up. With FilterExtensions, that's kinda removed to a more 'per mod' basis. Which I like. Without FE, nobody could search via manufacturer. So with title including it, things were more or less sorted by manufacturer.

So. How exactly do we want things. A small title of "F404-GE-429" isn't much descriptive, and kinda wastes space in a way. And So. Surely there is something else that can be put there. Perhaps every engine could have a prefix of "TurboJet:", "TurboFan:", "Rocket:"...or something to that effect. Even go as far as put air intakes (at least dedicated ones) in the engine category with a "Air Intake:" prefix or something.

**Comment by RedAV8R** [comment]
Any thoughts?

**Comment by A1Ch1** [comment]
I rather like the convention of using manufacturer names in the titles of jet engines, while leaving them out of the titles of rocket engines, as this mirrors Wikipedia Aviation and Spaceflight article titles.

**Comment by RedAV8R** [comment]
While not always completely true with Wiki. I personally rather like having the manufacturer in the title regardless of it's type.

I'd be ok leaving it out with rocket engines, while keeping it for air breathing cousins. As rocket engine manufacturers have been a lot more 'dynamic' Aerojet, Rocketdyne, then Aerojet Rocketdyne, etc. Which of the three should be put down?

What it boils down to for me, is I'd like to see better standardized naming so that searing for a specific part isn't more of a crap shoot like it is now. I have no issues working on that. Most of the work is done, just need to form PRs to get it where they need to be. At least when it comes to the more generic/stock items.

**Comment by NathanKell** [comment]
Sorry, was a bit busy last night and today.

The way I see it, if we include a manufacturer prefix, then engines are always sorted by manufacturer; if we don't, you can sort by title alone (i.e. roughly sorting by year, for US J/F/LR or Russian RD), or by manufacturer (via Filter Extensions, though it might be worth asking how much need be done to allow non-stock manufacturers to be handled stock).

Regarding rocket engines, the consensus that was arrived at about a week ago when this came up (on IRC rather than git) was:
title is just the designations (LR91 Series, AJ10-137 Service Propulsion System, etc)
manufacturer is as it says on the tin
description is prefixed with a short role statement (i.e. Vacuum optimized, hypergolic, deeply throttleable, low TWR, mid 1960s) followed by a newline (\n) and then the long-form description.

This serves the purposes of:

1. Not stating the role in the title (some existing engines say Booster or Sustainer or Upper....); we don't want to prejudge a player's use.
2. Nonetheless we do want to provide some easy-access use-relevant data to aid in the selection of engines by those unfamiliar with rocket history.

Regarding jets, at least in the US case, turbofans and turbojets will already sort differently so a prefix isn't needed, though I can see the merit in adding a postfix.

Getting rather sleepy so I'll end there, I'll be cogitating more tomorrow...

Tagging some others involved in the aforementioned discussion (sorry if I missed anyone)
@eggrobin @ferram4 @saabstory88 @pjf

**Comment by RedAV8R** [comment]
I do like the agreement with rocket engines. I really do.

Not seeing how air-breathers will sort differently, other than that basically won't. But I'm sure ideas have been passed that will. We'll wait for ya sometime today:)

**Comment by RedAV8R** [comment]
Changed engine titles to model number/designation plus suffix.
Also Fixed issue #63

**Comment by NathanKell** [comment]
Bleh, sorry, KSP bugfixing is taking *way* more of my time and mental energy than expected.

I agree about the diameters, also for the same reasoning as above (RO is supposed to *break* one of the habit of using engines of the "right size"). For jets, I meant that US jet designations (and Russian RD designations, for those jets which used them) are roughly chronological, in that J34 comes before J57 comes before J79. They will also sort out into jet (J), turbofan (TF, later F)--that's what I meant about sorting differently, they're already segregated.

**Comment by NathanKell** [comment]
(And let me know if I should merge this in, or await further commits)

**Comment by RedAV8R** [comment]
Figure as much about the engines.

Since it'll be a long process getting names changed. Do we want to just do individual PRs as they are worked on, or just do one massive PR when it's done?

If individual, let me do a few more changes on the files currently committed and I'd go ahead and merge it. I'll post again when ready.

**Comment by RedAV8R** [comment]
Good to go. Merge at your convenience.

**Comment by NathanKell** [comment]
Cool, doing so!

Btw, @SirKeplan started a wiki entry on this stuff. https://github.com/KSP-RO/RealismOverhaul/wiki/Part-Naming

**Pull request merged**
