### PR TITLE
KVD-1 Vernier Gimbal Fix

### PR DESCRIPTION
**Pull request by alimoncul**
I tried to fix it but im not sure i did. Need more help i think :)
Phineas Freak: KVD-1: Just reverse the X-Y axes (these are used for roll control).

### CODE REVIEW

**Comment by SirKeplan** [comment]
Shouldn't the gimbalRangeX and gimbalRangeXN be set to 0 not 1, if they only gimbal in 1 plane?

**Comment by stratochief66** [comment]
@SirKeplan possibly. But we will be waiting to be able to test this in-game anyway, and both 0 and 1 should probably be tested. There may be odd or unexpected behaviour with it set to 0, so I think both are worth testing.

**Comment by PhineasFreak** [comment]
From a first look, setting the axis gimbal range to zero has no obvious ill effect (at least for the RD-855/856 engines).

**Comment by stratochief66** [comment]
I haven't seen Alim around in a bit, and 1 ~= 0 in this case. So I think it should be 'good enough' (TM!) for now.

**Pull request merged**
