### PR TITLE
SXT N-1

### PR DESCRIPTION
**Pull request by Niemand303**

### CODE REVIEW

**Comment by NathanKell** [comment]
I still say no need to clone the part, just change its patch. :)

**Comment by Niemand303** [comment]
@NathanKell done! :)

**Comment by Niemand303** [comment]
@NathanKell done!

**Comment by stratochief66** [comment]
I concure, @Niemand303 just unclone:
https://github.com/Niemand303/RealismOverhaul/commit/ae0dea0744605c96759fc9a6e4720412ef6b97c7#diff-c67bb5d231d1b37a8e2597a692758360R1359

since the part as it is doesn't serve a purpose.

**Comment by Niemand303** [comment]
But I have already uncloned that, the config for the part just moved to RO_SXT_N1.cfg

**Pull request merged**
