### PR TITLE
SNAP-19 update

### PR DESCRIPTION
**Pull request by PhineasFreak**
* Replace ModuleGenerator with ModuleResourceConverter (operate even if
vessel is on rails).
* Add core heat simulation.

### CODE REVIEW

**Comment by stratochief66** [comment]
Closed for the same reasons as 711, please resubmit with new formatting. 

https://github.com/KSP-RO/RealismOverhaul/pull/711

**Comment by PhineasFreak** [comment]
Ok, this also should be good.

**Comment by stratochief66** [comment]
@NathanKell 

"%RSSROConfig = True" if fine, I'm not 100% sure if it works both ways. (NK?)

In my experience I always see the "!mesh" before the scaling lines, is there a reason for this NK or just tradition?

NK also will have a better idea of how this ModuleResourceConverter and ModuleCoreHeat will/should behave, so I will leave the rest of this PR to him.

**Comment by PhineasFreak** [comment]
As i mentioned in the BD_Atlas PR, some of these little changes are made automatically. For the mesh & model references, it is a preference to keep them close together so that they are easy to modify while making a part configuration. I mostly follow the config structure of the stock KSP part configurations.

For the converter & core heat modules i was searching for available references on the forums and the Wiki but i did not find something. I hope that @NathanKell will be able to provide some examples for these modules.

**Comment by NathanKell** [comment]
It's best to use True when assigning a boolean field. However, RSSROConfig _requires_ capital-T True, IIRC, since it is used in a (case-sensitive) MM HAS block, rather than parsed by KSP itself.

As to ModuleResourceConverter: If at all possible this should be **avoided**. It is way, way, way slower than ModuleGenerator, and I believe it is also slower than the TAC converters.

**Comment by NathanKell** [comment]
Further, while scripts are awesome (really! They help lots), please don't add 'default' position/rotation lines to MODEL patches. That can mess up later MODEL patches which expect the lines to not exist (and then add a duplicate line, since one already existed).

**Comment by PhineasFreak** [comment]
A lot of good points here! And i did not know that the boolean flag for RSSROConfig was case - sensitive.

Now, since the major change is not considered as critical, feel free to lock the PR again.

**Pull request closed without merging**
