### PR TITLE
Fixed part ID

### PR DESCRIPTION
**Pull request by Ravenchant**
I like wild cars as much as anyone, but it broke engine support.

### CODE REVIEW

**Comment by Temeter** [comment]
cats > cars, as every true man knows

**Comment by NathanKell** [comment]
@Ravenchant did you check the base KW files? There are some typos in KW itself, and this may be one of them IIRC.

**Comment by Ravenchant** [comment]
@NathanKell KW did have a typo, but it got fixed by the community patch a day or two ago:)

**Comment by NathanKell** [comment]
Ah, ok. Welp, guess they didn't care about save compatibility?

**Comment by SirKeplan** [comment]
that's crazy... that's not the kind of typo that's meant to be fixed.... :P

**Comment by NathanKell** [comment]
Exactly.

**Comment by Temeter** [comment]
Ohhhhhh so that's why KW's RD107/8 didnt TestFlight correctly! Totally forgot the big one was also called Wildcat.

**Comment by NathanKell** [comment]
Yes, that would explain why that and everything else broke. Jeepers, _why_ do this.

**Pull request merged**
