### PR TITLE
RO R-40/R-42 global engine configs

### PR DESCRIPTION
**Pull request by PhineasFreak**
**Change log:**

* Add global engine configs for the R-40 and the R-42 series of bipropellant thrusters.

### CODE REVIEW

**Comment by stratochief66** [comment]
I'm having trouble finding it through the sources, so apologies, but where do you find data for the ignition count? 
@SirKeplan is there a point at which we should just say a high enough demonstrated ignition count can just be 'unlimitted'? Would 142 or 50000 be on the ~arbitrarily restart-able side of that divide?

**Comment by PhineasFreak** [comment]
From the AJR thruster datasheet and Alternate Wars.

**Comment by SirKeplan** [comment]
@stratochief66 that would make sense to me, it's simpler to set engines that have effectively near unlimited ignitions to infinite(as all our RCS already is). 50,000 would absolutely be on that side of the divide in my mind. 134 ignitions on the R-42 seems oddly specific though, and is probably not on the infinite side of the divide.

**Comment by stratochief66** [comment]
Just to confirm, having no ignition count makes it infinite, right? In the back of my memory, I remember the 'right way' being either 0 or -1, but that probably changed at some time in the past few years.

**Comment by PhineasFreak** [comment]
@stratochief66 Yep, and an ignition count of 0 or -1 as you said are also valid for having infinite ignitions.

**Pull request merged**
