### PR TITLE
RN ksp 1.2.2 craft update

### PR DESCRIPTION
**Pull request by raidernick**
-Fix texture change on craft files. For some reason this spontaneously
broke on ksp 1.2.2

### CODE REVIEW

**Comment by rsparkyc** [comment]
Hey @raidernick,
  Do you think we should remove the references to `EditorCrewMass` in these as well?  See the comments on https://github.com/KSP-RO/RealismOverhaul/pull/1469
```
rcaskey:~/Desktop/KSPMods/RealismOverhaul/Ships rcaskey$ grep -r EditorCrewMass ./
.//SPH/RO Bonanza V35.craft:		name = EditorCrewMass
.//VAB/RO FASA Saturn IB Apollo.craft:		name = EditorCrewMass
.//VAB/RO FASA Saturn V Apollo Lunar.craft:		name = EditorCrewMass
.//VAB/RO FASA Saturn V Apollo Lunar.craft:		name = EditorCrewMass
.//VAB/RO RN Almaz 2-3-5.craft:		name = EditorCrewMass
.//VAB/RO RN Progress 7K-TG.craft:		name = EditorCrewMass
.//VAB/RO RN Salyut 1.craft:		name = EditorCrewMass
.//VAB/RO RN Salyut 4.craft:		name = EditorCrewMass
.//VAB/RO RN Salyut 6.craft:		name = EditorCrewMass
.//VAB/RO RN Salyut 7.craft:		name = EditorCrewMass
.//VAB/RO RN Skylab.craft:		name = EditorCrewMass
.//VAB/RO RN Soyuz 7K-LOK.craft:		name = EditorCrewMass
.//VAB/RO RN Soyuz 7K-LOK.craft:		name = EditorCrewMass
.//VAB/RO RN Soyuz 7K-OK-A.craft:		name = EditorCrewMass
.//VAB/RO RN Soyuz 7K-OK-A.craft:		name = EditorCrewMass
.//VAB/RO RN Soyuz 7K-OK-P.craft:		name = EditorCrewMass
.//VAB/RO RN Soyuz 7K-OK-P.craft:		name = EditorCrewMass
.//VAB/RO RN Soyuz 7K-T-AF.craft:		name = EditorCrewMass
.//VAB/RO RN Soyuz 7K-T-AF.craft:		name = EditorCrewMass
.//VAB/RO RN Soyuz 7K-T.craft:		name = EditorCrewMass
.//VAB/RO RN Soyuz 7K-T.craft:		name = EditorCrewMass
.//VAB/RO RN TKS.craft:		name = EditorCrewMass
.//VAB/RO RN Zond 7K-L1.craft:		name = EditorCrewMass
```

**Comment by raidernick** [comment]
I don't know what difference those make in being there.

**Comment by rsparkyc** [comment]
@NathanKell said that the EditorCrewMass class in RO should be removed.  I nuked it in my PR for 1.2.2, so I think they should probably be removed from the craft files to make them compatible with what will probably be the build for 1.2.2

**Comment by raidernick** [comment]
@rsparkyc the files just need to be resaved in 1.2.2 to remove that. I'll get to it once that plume nonsense is fixed

**Pull request merged**
