### PR TITLE
RO_RN Update

### PR DESCRIPTION
**Pull request by stratochief66**
To include new Raider Nick parts.

Vostok, Voskhod, Molniya, as well as the Luna probes.

### CODE REVIEW

**Comment by stratochief66** [comment]
http://forum.kerbalspaceprogram.com/threads/88383

**Comment by Hattivat** [comment]
I don't want to be rude, but may I ask what source do you have for Vostok's TDU burning UDMH? I've always seen it listed as "amine-based fuel"*, which upon further research turned out to be the triethylamine-xylidine mixture known as TG-02, almost identical to Tonka 250.

Also, Russians pretty much never use straight IRFNA, it's always a blend with nitrogen tetroxide, a.k.a AK-insert number. Russian sources seem to be in disagreement over whether it was AK-20F or AK-27I that powered Vostok's S5.4 engine, but it was surely not straight IRFNA.*

Another thing is that you forgot about the potassium superoxide CO2 scrubbers it had.

*Example English-language sources:
http://books.google.pl/books?id=zndYLKa26wAC&printsec=frontcover#v=onepage&q&f=false
http://www.nasa.gov/pdf/636007main_RocketsPeopleVolume3-ebook.pdf

*Example Russian sources:
http://www.flightgear.ru/%D0%B2%D0%BE%D1%81%D1%82%D0%BE%D0%BA-1/
http://lpre.de/kbhm/kbhm_engines.xls
http://epizodsspace.no-ip.org/bibl/zavyalov/rabota-v-kb.pdf

All are clear on what the fuel was, especially the latter one: "Немецкое пусковое горючее ксилидин /позднее «тонка» или ТГ-02/ не требовало каких-либо конструкторских ухищрений в КС. Оно нашло применение на многих двигателях ОКБ Исаева, включая ДУ С5.4, на которой приземлялся Гагарин." ( = "German ignition fuel xylidine / later "tonka" or TG-02 / did not need any design improvements to the KS (combustion chamber). It found use in many OKB Isayev engines, including the S5.4 DU (propulsion system), which brought Gagarin back to Earth."

**Comment by stratochief66** [comment]
Well caught. I believe I borrowed the fuel mixture from the current RO for salyut or soyuz.

Following this string, I found
http://www.astronautix.com/engines/s54.htm and http://www.astronautix.com/engines/ktdu5a.htm

From the looks of this, I will switch my Luna 9/10 engine to AK27 and Tonka 250, while the Vostok/Voskhod engine will move to AK20 and Tonka 250

I might also learn a little about the TAC life support system to simulate the CO2 scrubber.

Thanks for the feedback!

**Comment by Hattivat** [comment]
Sure, I'm happy to help!
That XLS file I linked above should have pretty much every engine of this kind that you might want. It's in Russian, but since it's just a spreadsheet, all you need to know is how to read a few letters ("s", "d", "u", "g"... and I think that's it).

Concerning Vostok, it puzzled me why you did not just copy the relevant portion of the already existing RO config for Vostok & Voskhod (coincidentally made by me :P), that's why I asked for exact sources on the off chance you had better ones. I don't claim it to be perfect, and improvements are certainly welcome, provided that they are actually improvements. You know, as they say around here, if your are trying to reinvent the wheel, at least make it rounder ;)

**Comment by stratochief66** [comment]
I was fighting with the demon of the TAC LS phantom energy use for a while there. I have tested copying the code of yours for the engine of the Vostok / Voskhod TDU. Now, I am going to do some calculations to adjust the Luna 9/10 propulsion core appropriately.

**Pull request merged**
