### PR TITLE
KK Launchers Atlas V

### PR DESCRIPTION
**Pull request by A1Ch1**
Adjust mass, rename boosters to AJ-60A, add RL10C-1, adjust STAR-5F sep motor

### CODE REVIEW

**Comment by raidernick** [comment]
Your isp values are wrong. The RL10A-4-2 is 446.4 and the RL10-C1 is 458

**Comment by A1Ch1** [comment]
Source? Everything I've read shows C-1 has lower Isp since it is a converted B-2 with the extension removed. The origMass value is needed because the C-1 is higher mass than the A-4-2.

http://ntrs.nasa.gov/archive/nasa/casi.ntrs.nasa.gov/20110015783.pdf RL10C-1 448.5
http://www.astronautix.com/engines/rl10a42.htm RL10A-4-2 451

**Comment by raidernick** [comment]
astronautix is 100% wrong 100$ of the time, never use them for anything unless you have no other choice. This is what pretty much all of the RO guys for for isp values. http://www.b14643.de/Spacerockets/Diverse/U.S._Rocket_engines/engines.htm

**Comment by A1Ch1** [comment]
What about the AR website itself: http://www.rocket.com/rl10-engine

Specific impulse in vacuum 444.4–451.0 sec; mixture ratio: 5.1–5.5:1

451 at optimal mixture ratio

**Comment by A1Ch1** [comment]
b14543 is a nice site, but those numbers are calculated rather than actual data.

**Comment by raidernick** [comment]
the mixture ratio is going to change the isp, if you are going to change the isp, change the mix rate then also, otherwise don't change the isp

**Comment by raidernick** [comment]
Looks good now. I agree with all the other changes too. NK should double check and it should be good to go.

**Pull request merged**
