### PR TITLE
CMES Propulsion updates (part III)

### PR DESCRIPTION
**Pull request by PhineasFreak**
Updates and fixes for the CMES "Propulsion" parts. Third pass.

Changelog:

* Update all engiine parts to use the new global engine configuration system.
* Remove invalid part modules from many parts.
* Add an active radiator module to the Orion SM.
* Upgrade the BNTR RTG generator module to the new ModuleResourceConverter.
* Fix the volumes of the DCSS 4 and 5 LH2 tanks.
* Explicitly set the part categories (and use the new KSP 1.2 ones).
* Balance inert and gross mass values against real sources and/or other parts.
* Adjust some insane max temperature values.
* Update the part titles and the descriptions.
* Fix formatting (tabs, false spacing).

[Alternate diff ignoring whitespace changes](https://github.com/KSP-RO/RealismOverhaul/pull/1466/files?w=1)

### CODE REVIEW

**Comment by stratochief66** [comment]
Yeah... it appears like Git is unhappy with the remaining II, III, and IV propulsion PRs. I suppose because they all edit the same file, and accepting any of them puts the starting state of the file in conflict with the state of the repo?
Are there any clear or easy ways to resolve that from your end @PhineasFreak ?

**Comment by PhineasFreak** [comment]
Damn, i hoped that these would not occur...give me some time to try and find an easy way to deal with it.

**Comment by stratochief66** [comment]
If that ends up being the best way to deal with it, fair enough. You could also have the content in different files, as the RO_CMES_Propulsion.cfg one is particularly large.
I promise to review and deal with the PRs quickly, to save you as much hassle I can.

**Comment by PhineasFreak** [comment]
I will probably make a lot of successive PRs in order to also add any new parts in the process. That way it will not be needed to create separate PRs for old and brand new configs.

Sorry about that :(

**Comment by PhineasFreak** [comment]
Closing due to extensive merge conflicts.

**Pull request closed without merging**
