### PR TITLE
Improve Tantares Venera descriptions

### PR DESCRIPTION
**Pull request by stratochief66**
I also noticed that the experiments are the opposite of how I would expect (all in the antenna, none in the lander core)

Should this be reversed?

### CODE REVIEW

**Comment by SirKeplan** [comment]
Description doesn't look quite right. it seems Venera 2MV was a much earlier Venera than Venera 9 (4V-1) onwards

**Comment by stratochief66** [comment]
Shallow information on astronautix & Gunters is ambiguous:

http://www.astronautix.com/craft/mars2mv3.htm

http://space.skyrocket.de/doc_sdat/venera-2mv-1.htm

They refer to 'soft landing' and 'venus lander', which I've only seen this design for.

**Comment by SirKeplan** [comment]
The earlier Venera landers looked more like this http://www.russianspaceweb.com/images/venera7_sa_200.jpg

http://www.russianspaceweb.com/3mv.html

**Comment by stratochief66** [comment]
Ahh! Alright then. Write a description change you would suggest, and I will
modify the PR.

**Comment by SirKeplan** [comment]
"Represents the Venera 9 (4V-1) through Venera 14 (4V-1M) landers. First human made object to successfully return images from another planetary body."

**Pull request merged**
