### PR TITLE
Add Support for DECQ Buran, standardize space shuttles

### PR DESCRIPTION
**Pull request by Capkirk123**
- Add support for DECQ Buran.
- Adjust CoM offset, wing offset, and CoL offset on SSS, SOCK, and DECQ Buran so the CoM is in the correct position according to Shuttle Aerodynamic Design Data Book.
- Adjust aero so SOCK, SSS and DECQ Buran can perform a type 1 reentry according to the Shuttle Aerodynamic Design Data Book (I did not test the more complex reentry profiles)
- Fix SOCK front landing gear so it can steer
- Adjust thermal values to be more realistic (greatly drop max temp, greatly increase insulation)
Issues:
- Buran docking port doesn't work and is left unconfigured. I'm not sure if I'm configuring it wrong or if it's just broken
- Buran has some serious CoM shift issues, due to carrying more propellant than the shuttle. I added fuel tanks in the nose to help, not sure if it actually had them
- SOCK front landing gear steering doesn't animate
- No Waterfall configs for DECQ Buran or SSS
- The rest of Energia is left unconfigured for now

### CODE REVIEW

**Comment by NathanKell** [comment]
Has a conflict?

**Comment by Capkirk123** [comment]
Conflicts resolved

**Comment by MyNameIsBorat** [comment]
it has a lot of unresolved issues. check out my config which is included with the mod, it is working properly.

**Comment by Capkirk123** [comment]
> This config has a lot of unresolved issues. check out my config which is included with the mod, it is working properly. Maybe you can merge both of the configs. Plus, having multiple configs is not ideal. let me know when both are merged and I will exclude config from the mod.

What unresolved issues are there?

**Comment by MyNameIsBorat** [comment]
As stated in the original comment. I didn't check these configs yet, but I have energia configured. You can integrate that into these configs so that I can safely remove the configs I release with the mod.

**Comment by MyNameIsBorat** [comment]
There are a few things found to be inaccurate.

1. Crew capacity is 12. It is meant to be four.

2. Mass seems to have been copied from space shuttle directly. Buran is lighter than the shuttle with launch mass of 105t and payload capacity of 30t.

I have taken data in my configs from reliable sources pls look into astronautix buran website

**Comment by Capkirk123** [comment]
> There are a few things found to be inaccurate.
> 
> 1. Crew capacity is 12. It is meant to be four.
> 2. Mass seems to have been copied from space shuttle directly. Buran is lighter than the shuttle with launch mass of 105t and payload capacity of 30t.
> 
> I have taken data in my configs from reliable sources pls look into astronautix buran website

Crew capacity of 12 is with seats installed in the mid-deck. The Buran orbiter never had those installed, but they were planned for future orbiters

The mass has not been copied from the space shuttle, the Buran orbiter weights around 60 tons dry. Astronautix is not a good source, it is often inaccurate. I have taken my data from buran.ru and energia-buran.com, particularly the memiors of Boris Ivanovich Gubanov, chief designer of universal space rocket transport system Energiya.

**Comment by MyNameIsBorat** [comment]
Please check out this video which shows buran in its last state. It shows the area inside the cockpit.

https://youtu.be/zmBBSrxGfPQ

I have calculated the mass from the sources mentioned by you and astronautix and wikipedia. Buran should be lighter than the space shuttle, if it is of similar mass, then either buran or shuttle's mass needs to be changed. Accordingly, I will review the rest of the config soon and let you know if any more changes are required.

**Comment by Capkirk123** [comment]
> Please check out this video which shows buran in its last state. It shows the area inside the cockpit.
> 
> https://youtu.be/zmBBSrxGfPQ
> 
> I have calculated the mass from the sources mentioned by you and astronautix and wikipedia. Buran should be lighter than the space shuttle, if it is of similar mass, then either buran or shuttle's mass needs to be changed. Accordingly, I will review the rest of the config soon and let you know if any more changes are required.

Yes. Buran is lighter than the shuttle. Buran also has the option to mount passenger seats on the mid-deck. These were never installed.

**Comment by MyNameIsBorat** [comment]
So let's keep it to the configuration it flew in. We don't know how feasible was it to sustain 12 person crew on buran for a 28 day mission.

**Comment by Capkirk123** [comment]
That's the player's problem. If they can't load enough life support for 12 crewmembers, then they won't bring 12 crewmembers. Buran doesn't have to do a 28 day mission either.

**Comment by MyNameIsBorat** [comment]
Same could be said for the space shuttle. But we don't see it happening realistically. Plus the model has only 4 iva seats. You could technically fill both to the brim like a japanese commuter train but there is a reason we don't see that because engineers couldn't fit more crew safely. They would have, if they could and I think they are much more qualified about the topic than you or me. I am only telling you that it seems like common sense to have the model, engineer's recommendations and real life prototype match what is shown in the config rather than some future planned expansion. I have said enough about the seats, rest is your decision.

**Comment by leorjorge** [comment]
Why don't you keep your configs in the mod and we have RO patching it for RO according to our sourcing and config policy? It's not common for mods to have no configs for parts when installed with stock

**Comment by leudaimon** [comment]
Why don't you keep your configs in the mod and we have RO patching it for RO according to our sourcing and config policy? It's not common for mods to have no configs for parts when installed with stock

**Pull request merged**
