### PR TITLE
CMES Configs - First Pass

### PR DESCRIPTION
**Pull request by Saabstory88**
Refreshed repo for this pull request. First playable configs for CMES.

### CODE REVIEW

**Comment by jwvanderbeck** [comment]
Is this ready to go @Saabstory88 or is more coming?

**Comment by Saabstory88** [comment]
More will come in the future. It's playable. Certainly better than just having the stuff rescaled. Still some cleanup needed. Going to back-burner this until CMES and RO are 1.x compatible.

**Comment by NathanKell** [comment]
@Saabstory88 whew, just caught in time--can you do it into KSP10 not master?

**Comment by NathanKell** [comment]
@Saabstory88  now that we merged KSP10 into master, can you rebase this? Then we can merge away :)

**Comment by stratochief66** [comment]
#450 Recovers as much as possible from this PR.

**Pull request closed without merging**
