### PR TITLE
Add a RSRM part based on stock's kickback

### PR DESCRIPTION
**Pull request by lpgagnon**
Because it's weird for RO to provide a "default" RSRMV but no RSRM.
Only tested with restock.

### CODE REVIEW

**Comment by DRVeyl** [comment]
Any interest in sorting this out for VSR and stock-only models?

**Comment by lpgagnon** [comment]
how about we pretend I didn't write the TODO, nobody noticed there might be extra work needed for non-restock installs, this gets merged, and _then_ somebody complains about whatever turns out to be broken and it gets fixed?

**Comment by StonesmileGit** [comment]
Tested with VSR; pair of RSRM on the left, RSRMV on the right.
VSR to the left in each pair, reDIRECT to the right in each pair
image

**Comment by lpgagnon** [comment]
"TODO try with ven's" removed, stonesmile's comparison looks close enough to me. Good to merge?

**Comment by StonesmileGit** [comment]
LGTM, will hold until my current work on the RSRM is done

**Pull request merged**
