### PR TITLE
SSTU Orion Service Module fix

### PR DESCRIPTION
**Pull request by DocRockwell**
fixed bug causing GUI to freeze

### CODE REVIEW

**Comment by Theysen** [comment]
this leads to ModuleManager Errors, but I didn't see anything gamebreaking so far. I guess they are related to the MM 3.x changes?

**Comment by DocRockwell** [comment]
Fixed pyrolysisLossFactor and ablationTempThreshvalue on Orion CM ablator. Not sure about the lossConst or lossExp values, left them unchanged.

**Comment by raidernick** [comment]
@Theysen does this still cause mm errors or is it good to merge?

**Comment by Theysen** [comment]
good to go, shoot.

**Pull request merged**
