### PR TITLE
H-1/RS-27

### PR DESCRIPTION
**Pull request by A1Ch1**
Just reforked and copy/pasted to resolve edit conflict

### CODE REVIEW

**Comment by NathanKell** [comment]
Closes #218.

**Comment by NathanKell** [comment]
Just waiting on @jwvanderbeck okaying the config name changes.
Ah, and there's one more little thing, sorry--the H-1s should all be defaulting to configuration H-1-SaturnIB not SaturnI, since of the people liable to be using it, that's the one they'll most likely use (it saves on users saying "why doesn't my Saturn IB work?" and us saying "did you change engine configs?" :) )

**Comment by A1Ch1** [comment]
Done and done. Thanks for being helpful :)

**Comment by NathanKell** [comment]
Hey, thank *you* for being helpful! Who's the one who's adding all the PRs? :)

**Comment by jwvanderbeck** [comment]
I don't actually have defs for the H-1 yet in TF, so not a huge deal for me :)  I think the naming is a bit ugly, but since I don't have anything else to suggest I will keep my mouth shut on that :)

**Comment by A1Ch1** [comment]
As far as I can tell, the closest Rocketdyne and NASA got to naming the H-1 versions was H-1 165K, H-1 188K, H-1 200K, and H-1 205K (http://www.alternatewars.com/BBOW/Space_Engines/H-1C-D_Manual.pdf)

**Pull request merged**
