### PR TITLE
Adding RO config for my NK33 mod

### PR DESCRIPTION
**Pull request by Mad-Rocket-Scientist**
Forum link here: http://forum.kerbalspaceprogram.com/index.php?/topic/155876-nk-33-engine-now-with-pre-release/

I think this is the right way to add support for my mod in RO, but I'm very new to github, so apologies if it isn't.

### CODE REVIEW

**Comment by stratochief66** [comment]
Looks pretty good, I'll have to test it in game to check the scaling.

Did you mean to leave this line commented out? If so, why include it?
https://github.com/KSP-RO/RealismOverhaul/pull/1540/files#diff-21934597b7b57c95e3a7c088188b26ecR5

**Comment by Mad-Rocket-Scientist** [comment]
Thanks!  

That was a mistake, I was modifying the Bobcat config and I left that in there.  Is there a way to change it or do I need to make a new pull request?

**Comment by stratochief66** [comment]
Whichever you find easier. If you click on 'Files changed' at the top of this page, then the pencil icon to edit the file, just delete that line, describe the change in the Update/Description boxes, and Commit to that branch.

**Comment by Mad-Rocket-Scientist** [comment]
Done!  Thanks.

**Comment by stratochief66** [comment]
@Mad-Rocket-Scientist I should get around to testing this soon. Can you rename the file so that it ends in .cfg, like the other RO config files?

**Comment by Mad-Rocket-Scientist** [comment]
Fixed that, thanks.

**Comment by stratochief66** [comment]
One last thing; in testing, the engine lacks a plume. To confirm that there wasn't anything complicated going wrong, I just stole the plume for another NK33 and had it apply to this part. It was 'good enough' in position, it could do with some tweaking if you're interested in doing that, or just duplicate.

https://github.com/KSP-RO/RealismOverhaul/blob/master/GameData/RealismOverhaul/RealPlume_Configs/BobCat/NK33.cfg

That is what I used. If you create a folder in RealPlume_Configs for NK33 just like you did for the RO config, that'll be where you want to put it.

**Comment by Mad-Rocket-Scientist** [comment]
I just made a new pull request with that.  I also made one for my own fork of RO, oops.
https://github.com/KSP-RO/RealismOverhaul/pull/1548

**Pull request merged**
