### PR TITLE
SRM Configs: KW

### PR DESCRIPTION
**Pull request by A1Ch1**
Configs for SRMs found in KW. Separate PR for KW itself

### CODE REVIEW

**Comment by SirKeplan** [comment]
ah, cool!

**Comment by SirKeplan** [comment]
Eh, sorry @A1Ch1 your going to have to change `:FOR[RO-EngineConfigs]:BEFORE[RealPlume]` To `:FOR[RealismOverhaulEngines]` in your PRs
NathanKell showed me i was using ModuleManager slightly wrong, what i had before before worked fine, but this is safer/more robust.

**Comment by A1Ch1** [comment]
Alright :) I finally got around to putting together a program to automatically extract thrust curve data, so I'm taking the opportunity to go through the thrust curves again anyway.

**Comment by stratochief66** [comment]
Looks good, one things I've noticed.

Should we include " !MODULE[ModuleEngineConfigs] {} " near the beginning of the templates?

@SirKeplan as well.

**Comment by SirKeplan** [comment]
@stratochief66 why does that need to be included for these configs? i mean i see no harm adding that line for the solids. unless you mean in general, then that would cause issues with verniers i guess.

**Comment by NathanKell** [comment]
We need to be careful about our clones then, if it's not included.

**Comment by NathanKell** [comment]
To clarify further, there are two cases we need to worry about:
Case 1: The engine config is being applied to a part that was (a) cloned from an existing RO part after it has been RO-patched, and (b) that existing part is not using the new engine config system. In this case, we need to remove any existing ModuleEngineConfigs.
Case 2: The engine part has multiple engines on it. This will necessitate *not* destroying any prior ModuleEngineConfigs.

I would suggest that the best approach is to make sure Case 1 never exists, and then we will never need to worry about !MODULEing.

**Comment by SirKeplan** [comment]
@NathanKell agreed, should be pretty easy to ensure Case 1 doesn't happen i believe.

**Comment by A1Ch1** [comment]
In this case, the clones are all cloned from parts with engineType, so %engineType was sufficient. I did test the parts with !ModuleEngineConfigs just in case, to verify nothing changed.

**Comment by stratochief66** [comment]
What is the state of this PR, good to go?

It might be good to cite which RO file you took the thrust curve from, and if you have found any disagreements/discrepancies between different implementations of these parts.

**Comment by A1Ch1** [comment]
These are good to go :) Added thrust curve sources where I've gone back and re-verified (the Castor and GEMs). There are no discrepancies yet since they're only for KW parts so far.

**Pull request merged**
