### PR TITLE
RO Squad Engines updates/fixes

### PR DESCRIPTION
**Pull request by PhineasFreak**
* Separate the VSR passes from the main RO configs for better clarity.
* Make sure that ant new parts (+PART) are created before any RO changes are applied to the source part (@PART).
* Remove redundant attachment rules (taken care by the global RO patches).
* Decrease the crash tolerances and the maximum temperatures. Engines now can be destroyed when deorbited.
* Start to move the "ModuleEnginesRF" from the RealPlume pass to the main RO pass.
* Remove some redundant modules (taken care by the global engine configs).
* Remove leftover IGNITOR{} blocks (taken care by the global engine configs).
* Remove some VSR "tankbutt" nodes (not applicable unfortunately for all the engines).
* Comment each patch for easier search/identification.
* Remove some old engine FX configs (taken care by RealPlume).
* Fix some model removals (!MODEL).
* Replace the Altair - II model with the same model as Altair.
* Merge the two RAPIER patches into one.
* Fix the KVD-1 and the RD-0105/0109 models.
* Fix the KVD-1 verniers (ullage, ignitions, gimballing).
* Fix the attachment node sizes and placements of some parts.
* Simplify RESOURCE removal from any parts that require it.
* Add a STAR 37 SRM.
* Fix the size of the STAR 48B SRM.

NOTE 1: Due to an issue with RealPlume the KVD-1 main engine plume will not appear.
NOTE 2: The NSTAR ion engine still uses the old workaround for setting the ElectricCharge consumption. This will be fixed in a future update.

### CODE REVIEW

**Comment by NathanKell** [comment]
Uh...please test your changes in future. This killed gimbal on the LR79, LR89, and H-1. Those gimbal MODULE patches do need to be there, otherwise the transform is not set properly.

**Comment by PhineasFreak** [comment]
The engines had gimbal modules but VSR changes the transform name to be "Nozzle". This is a not valid gimbal transform though with the latest versions.

**Comment by NathanKell** [comment]
All three engines use our own model, not VSR's new model, and therefore they need to have their gimbal transform set to what our model uses...

**Comment by PhineasFreak** [comment]
Damn, i went with the part module name and forgot the actual part model...mea culpa.

**Comment by NathanKell** [comment]
It happens, no worries. :) Just do please try to test a change like "removing the gimbal patch" ;)

**Comment by NathanKell** [comment]
Also we leave minThrust at 0 for solids, so that you can configure the thrust limiter in the VAB (to represent the different shapings and grains that could be used).

**Pull request merged**
