### PR TITLE
Add KSPWheel configs to all Stock landing gear/legs if KSPWheel is installed

### PR DESCRIPTION
**Pull request by lukecologne**
All credit for the configs goes to ShadowMage, slightly modified from the KerbalFoundries2 Repo.

Landing gear is tested, landing legs not yet.

### CODE REVIEW

**Comment by lukecologne** [comment]
Small and medium landing leg seem to work correctly, the large one does not. Searchin for a fix.

**Comment by raidernick** [comment]
Can a 3rd party please test this before merging it, I don't have the time currently.

**Comment by lpgagnon** [comment]
Tested takeoff on 4 existing .craft (collectively using the 4 smallest stock landing gear parts); all worked as well or better than without this PR. At least one had noticeably less tendency to swerve off course.

Did NOT test landing.

**Comment by siimav** [comment]
Don't tell me you landed on chutes

**Pull request merged**
