### PR TITLE
RealEngines heat production fix

### PR DESCRIPTION
**Pull request by PhineasFreak**
Change log:

* Increase the heat production to make the heat animations show up.
* Fix a bad heat production value on the NK-43 engine.

**Note:** the rest of the heat animation fixes will be part of the RealEngines pack itself.

### CODE REVIEW

**Comment by Temeter** [comment]
Correct me if I'm wrong, but isn't heat production determined by the RO's general Engine_Configs? They certainly have a field for heat production.

Also seems to be a general problem; seeing the same emissives not activating on all engines of RO, stock and FASA. See https://github.com/KSP-RO/RealismOverhaul/issues/1547#issuecomment-279713499

**Comment by PhineasFreak** [comment]
No, you are correct, these should be fixed at the global config. Still, i wanted to update them to fix the typo that i found but it is not a big deal.

**Comment by Temeter** [comment]
I see, it was zero. Can't hurt to fix that!

**Comment by PhineasFreak** [comment]
Note that this PR will be deprecated soon, as i am preparing the RO configs for the new RealEngines release(s).

**Pull request merged**
