### PR TITLE
CMES Real Plume updates

### PR DESCRIPTION
**Pull request by PhineasFreak**
Updates and fixes for the CMES Real Plume configs.

Change log:

* Update all Real Plume configs to fix various visual bugs.
* Add Real Plume configs to the new engine parts.

~~**Note 1:** the Ares V Core Stage plume config will be removed in the future as the part does not exist anymore.~~
**Note 2:** each successive PR refers to a single part only to simplify diffs.

[Alternate diff ignoring whitespace changes](https://github.com/KSP-RO/RealismOverhaul/pull/1463/files?w=1)

### CODE REVIEW

**Comment by stratochief66** [comment]
As in #1483, these will have to use the MODEL_MULTI_SHURIKEN_PERSIST. I can't resolve all the conflicts through the web editor, can you sort those out with Find-Replace @PhineasFreak, or some way?

**Comment by rsparkyc** [comment]
I bet the conflicts are only due to the line ending changes that was in my (merged) PR.  @PhineasFreak, if I get a chance I'll submit a PR against your repo resolving the conflicts.

**Comment by rsparkyc** [comment]
Ok @PhineasFreak, if you merge https://github.com/PhineasFreak/RealismOverhaul/pull/1 in, it should resolve the conflicts and have `MODEL_MULTI_SHURIKEN_PERSIST`

**Comment by PhineasFreak** [comment]
@rsparkyc i though that you saw that i had taken care of the CMES configs. But whatever. At this point it is easier to close and reopen it (dealing with conflicts is a major PITA).

**Pull request closed without merging**
