### PR TITLE
Tantares configs

### PR DESCRIPTION
**Pull request by Niemand303**
Two files are ready for both Tantares and TantaresLV

### CODE REVIEW

**Comment by Felger** [comment]
@Niemand303, checking on the status of this PR, is it still a WIP, or is it ready to move out of REWORK into the RO_Supported folder?

**Comment by Niemand303** [comment]
Finished the configs for the newest version of Tantares and TantaresLV mods. Ready to go.

**Comment by NathanKell** [comment]
@Niemand303 uh looks like the files are duplicated? I.e. there's both copies in REWORK and in RO_Suggested. Can you delete the ones in REWORK?

Thanks for all the work and sorry for the miscommunications...

**Comment by Niemand303** [comment]
Fixed!

**Pull request merged**
