### PR TITLE
Global NK-9 and NK-9V config

### PR DESCRIPTION
**Pull request by SirKeplan**
give NathanKells NK9s a global config files

### CODE REVIEW

**Comment by NathanKell** [comment]
<3

**Comment by NathanKell** [comment]
Ah, this shows I had a missed line in the original config. NK-31 can relight, AFAIK. That's presumably why it's heavier. Don't know about ignition count though, something like 2-5?

**Comment by SirKeplan** [comment]
Ah, ignitions. so the NK-31 is basically an upgraded NK-21 for the N-1F. now the 1st and second stage engines where upgraded to support multiple firings for testing purposes for the N-1F, but i'm not so sure about the 3rd and 4th stages.

and i don't know whether the the NK-21 ever supported multiple firings, i assume it would, but other contemporary engines didn't, and 1 ignition is all you technically need if the 3rd stage puts you in a good LEO.

**Comment by NathanKell** [comment]
Ya NK-39 was the third stage version.  NK-31 was the fourth (TLI) stage
engine.  I did read it was explicitly built for multiple ignitions.

Sent by my thumbs, slowly.

**Comment by SirKeplan** [comment]
Added an NK-39.

Another thing is the NK-19/39 would have had throttling capability, as the 3rd stage used differential throttling instead of gimbaling, that might mean the NK-21/31 could throttle too.

**Comment by stratochief66** [comment]
PR looks good to me. Since @NathanKell already commented here, I assume this is good to merge then? (As good as it can when I'm too busy/lazy to test in game)

**Comment by SirKeplan** [comment]
Yeah, i don't think there can be any issues as it is, we can make mods to these engines later if we have more info.

**Comment by NathanKell** [comment]
Heh. Was just about to respond. :)
AFAIK the 19 and 21, vs the 31 and 39, are reversed: the NK-21 was the single-engine variant, but the NK-39 was the single engine variant (and restartable, where the 31 was not).

**Pull request merged**
