### PR TITLE
RO Constellation Essentials

### PR DESCRIPTION
**Pull request by PhineasFreak**
Add RO support for the BahamutoD Constellation Essentials pack.

### CODE REVIEW

**Comment by PhineasFreak** [comment]
This was in the backlog for some time but it is finally here! And because someone asked for it in it's KSP forum thread...

**Comment by winged7** [comment]
Awesome! I've found that you're working on them and I already made (a couple of months ago)  RP-0 config for all parts.

**Comment by PhineasFreak** [comment]
I was very pleased to boot KSP after making the configs and finding out that they were already supported by RP-0 (how did i missed that?).

Something that is bothering me is that there are two versions of the pack, the original from Bahamuto (that these configs target) and another from KSP forum user MeCripp, who re-distributes it with changes to be compatible with KSP 1.0.5. If the second release is used then hell will break loose...

**Comment by stratochief66** [comment]
https://github.com/KSP-RO/RealismOverhaul/pull/878/files#diff-5abe9455de2bb217d53a3f3b206841b7R7

Does this quoted fuel/oxidizer ratio (5.37 (TRITON)) translate into this KSP mixing ratio? It looks suspect to me because it is so round and simple 3:1

**Comment by PhineasFreak** [comment]
I calculated the actual O/F ratio with the wrong way. The correct ratio should be 0.1571/0.8429.

**Comment by stratochief66** [comment]
No worry, that is what PR review and testing is for :)

**Comment by PhineasFreak** [comment]
True, a clear mind can do wonders on a wall of text that seems perfect to the one that wrote it. And i thank you for that!

**Comment by stratochief66** [comment]
I see two versions here, will it matter which one the users downloads?

http://forum.kerbalspaceprogram.com/index.php?/topic/69581-rssro-constellation-essentials-v131-trusses-engines-adapters-apr21/

**Comment by stratochief66** [comment]
New rule: If a mod isn't available on CKAN, please place a link to the place to download it in the PR :P

**Comment by stratochief66** [comment]
https://github.com/KSP-RO/RealismOverhaul/pull/878/files#diff-1157b11afaabc91fb9c18113d0de507dR186

Where does the nuclear fuel come from? Perhaps you mean to change the name to EnrichedUranium?

So this engine will generate 5 EC/s at all times?

**Comment by stratochief66** [comment]
From the picture on the forum page for this mod, it looks like the engine mount should have 3 nodes for holding 3 engines?
https://github.com/KSP-RO/RealismOverhaul/pull/878/files#diff-1157b11afaabc91fb9c18113d0de507dR19

**Comment by PhineasFreak** [comment]
Yep, error on my end. Fixed.

Since Bahamuto has a stockalike and an RSS version, only the RSS version is supported (the stockalike is missing the Six Way Engine Mount).

Originally, there were 3 nodes, a top node for tank attachment, a middle one used for some unknown reason to me and the bottom one (for generic attachment). The engines were and are surface attachable.

**Comment by stratochief66** [comment]
yeah, I think I figured out from the comments that he means "RSS compatible", not RO.

does he use different part names for one version or the other? what are consequences if someone tries to use this patch with the wrong version?

also, I just finished testing this, the only suggestion I have (not a realism one, just usabiliity) would be to add a tiny amount of 'gimballing' to the NTR engines. I would hope they would plan to do that in the real thing, or else you would have to burn a goodly amount of other fuels to correct for even slightly off centre masses during the ejection burn.

**Comment by PhineasFreak** [comment]
No changes in the part names, only the missing RS-68 engine adapter for an Ares V - like launch vehicle. As i mentioned, MeCripp has repackaged the mod and even then the changes are centered around the removal of the old ModuleEngineConfigs that were included with the base parts and some changes to the resource names. That would break things so i should probably just delete the contents of the engine parts and recreate them to be on the safe side.

I though about engine gimbaling but i did not find any source that would indicate that these engines can gimbal, only that the original NERVA design had two vernier engines using waste Hydrogen from the pump.

**Comment by stratochief66** [comment]
what are consequences if someone tries to use this patch with the wrong version?

**Comment by PhineasFreak** [comment]
They will be stuck on the loading screen.

**Comment by PhineasFreak** [comment]
And it should not be an issue anymore with the latest patch!

**Comment by stratochief66** [comment]
Thanks for the fix. Compatibility is good :)

**Pull request merged**
