### PR TITLE
New Raptor and RVac MECs

### PR DESCRIPTION
**Pull request by SkyPhoenix999**
- Updated Specs for Raptor
- Split off RVac into separate Config
- Changed to support Raptor 1, Raptor 2, and Raptor 3.

### CODE REVIEW

**Comment by SkyPhoenix999** [comment]
Requires [Subcooled Methane Pull](https://github.com/KSP-RO/RealismOverhaul/pull/2981) to work

**Review by Capkirk123 — CHANGES_REQUESTED** [review]
No spaces in config names, it makes them a lot harder to patch and messes with RP-1

**Comment by SkyPhoenix999** [comment]
> No spaces in config names, it makes them a lot harder to patch and messes with RP-1

Added Dashes to all config names instead of spaces

**Review by Capkirk123 — CHANGES_REQUESTED** [review]
Did you intend to alter the Cryoengines configs in this PR?

**Comment by Capkirk123** [comment]
resolves https://github.com/KSP-RO/RealismOverhaul/issues/2995

**Comment by SkyPhoenix999** [comment]
I didn't originally intend to but I already had the configs for it for testing, so it's just one less PR that needs to be made

**Review by Capkirk123 — APPROVED** [review]

**Pull request merged**
