### PR TITLE
Tweak Gloster Meteor cockpit temp limits

### PR DESCRIPTION
**Pull request by aw1621107**
Change temp limits to match those of the other starting cockpits

### CODE REVIEW

**Comment by NathanKell** [comment]
I'd like to keep the Meteor cockpit's skin max temp higher, since it's the only starting jet cockpit. But maybe that's silly gameplay?

**Comment by aw1621107** [comment]
How much higher?

**Comment by NathanKell** [comment]
I'd say 450 would be good, should let you get to Mach 1.5 or even 2.0 in steady state?

**Comment by aw1621107** [comment]
Done!

**Pull request merged**
