### PR TITLE
DCSS cfgs

### PR DESCRIPTION
**Pull request by FennexFox**
Is it done properly now?

### CODE REVIEW

**Comment by jwvanderbeck** [comment]
Looks good to me, though since it is a lot of changes i'm going to leave it open for @NathanKell to peek at the contents.  But you got the right branch this time :)

**Comment by NathanKell** [comment]
@FennexFox  on IRC you said you didn't want this merged, only checked? Or did I misunderstand?

**Comment by FennexFox** [comment]
Oh, I didn`t want a "real" investigation whether the configs are sound or not at that time, since unconfident on this config. I want it to be merged in case it`s sound, of course! That`s my honor.

**Comment by NathanKell** [comment]
Ah, ok. Let me take a look and then assuming all goes well I'll merge it in. I assume you've tried it out ingame and it works well?

**Comment by FennexFox** [comment]
Play-wise, no problem. Real-wise, some parts need more investigation and some parts are not working I intended. I added notes everywhere  where need more works I think.

**Pull request closed without merging**
