### PR TITLE
New Naming Standardization - Remove TweakScale

### PR DESCRIPTION
**Pull request by RedAV8R**

### CODE REVIEW

**Comment by RedAV8R** [comment]
Hold off on merge for a little bit until I finish please. I'll notify when ready.

**Comment by NathanKell** [comment]
Ok, gonna see if I can merge this in manually.

**Comment by stratochief66** [comment]
RO-Mk1Fuselage and RO-Mk1FuselagePres no longer appear to exist? (?) which might break some craft.

Tweakscale no longer removed from a few parts: (GrapplingDevice, LaunchEscapeSystem)
https://github.com/KSP-RO/RealismOverhaul/pull/698/files#diff-f91911984759792c41baa745e7c13b56L12

SolidFuel no longer removed?
https://github.com/KSP-RO/RealismOverhaul/pull/698/files#diff-f91911984759792c41baa745e7c13b56L41
https://github.com/KSP-RO/RealismOverhaul/pull/698/files#diff-f91911984759792c41baa745e7c13b56L110

Wasn't one of the specs for the new naming scheme supposed to include the size being in the description?
https://github.com/KSP-RO/RealismOverhaul/pull/698/files#diff-f91911984759792c41baa745e7c13b56L97
https://github.com/KSP-RO/RealismOverhaul/pull/698/files#diff-f91911984759792c41baa745e7c13b56L341

**Comment by NathanKell** [comment]
Looking through, to make this merge right, I've also noticed that parts like wings and decouplers no longer have unique names. That will make it very hard for people to talk about what parts they're using, for example. I can well understand going from Wing Connector A to Wing - Rectangular - A, for example, but just calling them all the same thing period seems counterproductive. Am I missing something?

**Comment by stratochief66** [comment]
Can the size be included in the description? (either Size3 or in metres) XXXL isn't functionally description, in my opinion.

**Comment by stratochief66** [comment]
https://github.com/KSP-RO/RealismOverhaul/wiki/Part-Naming

**Comment by stratochief66** [comment]
A number of parts no longer modified:

https://github.com/KSP-RO/RealismOverhaul/pull/698/files#diff-006242d4815a96dae5eb79b60e93312eL100

**Comment by NathanKell** [comment]
Also, on my part apologies for the delay! Was a busy couple weeks before/after Thanksgiving.

**Comment by RedAV8R** [comment]
"Hold off on merge for a little bit until I finish please. I'll notify when ready."

KInda why I put this up in the first place, I wasn't ready to merge this.

**Comment by NathanKell** [comment]
Ah, whoops. <sheepish>

**Comment by RedAV8R** [comment]
Go directly to jail, do not pass go, do not collect $200.

**Comment by RedAV8R** [comment]
@stratochief66 : To cover a few things...kinda in order of things brought up.

1. Yeah, caught that I removed those old cockpits, those I'll get back in. Initial pass thought too small, but then have thought otherwise.
2. We are removing TweakScale support as discussed before.
3. Size in the description, sure, that's more along the lines of 'not done yet'. Not the title though.
4. @NathanKell - Still more a WIP, so yeah, needs some polish on a few names.
5. The XXXL is actually more xxxL, as in how many L the tank can hold.
6. Your bit about parts not modified, actually they are...just individually, rather than as a group as before.

**Pull request closed without merging**
