### PR TITLE
Making History Engines

### PR DESCRIPTION
**Pull request by smartdummies**
Configs for the engines in Making History expansion pack

### CODE REVIEW

**Comment by raidernick** [comment]
dude I was JUST about to hit release for the new RO version and this pops up. I can't even test this I don't have the DLC and now it's holding up the next release.... Someone who has the DLC needs to test this pretty much right now. @Bornholio @Theysen @pap1723 @PhineasFreak

**Comment by Bornholio** [comment]
loading

**Comment by smartdummies** [comment]
@Bornholio which engine did not come up? There should be the LR-91, LR-87, AJ10-137, J2, F1, RD107, RD108, and the verniers for the RD107/108

**Comment by raidernick** [comment]
no...

**Comment by smartdummies** [comment]
OK. I just wanted to ask as that would simplify things on this end as most of you do not have the expansion it would remove any expansion related items and issues from the releases.

**Comment by smartdummies** [comment]
I have the command pods ready. Do you want that in a separate pull request or added into this one?

**Comment by smartdummies** [comment]
Command Pods added

**Pull request merged**
