### PR TITLE
Combine RS-25 configs, update RMM

### PR DESCRIPTION
**Pull request by Capkirk123**
Combine the RS-25 configs into one config, add SSBE/LRBE configs, and update RMM mod support.

### CODE REVIEW

**Comment by NathanKell** [comment]
Has conflicts - also does it depend on ROE?

**Comment by Capkirk123** [comment]
Conflicts resolved. This does not strictly require the PR from ROE, it will allow alternate nozzle configs to be selected, but nothing will break. The ROE PR does require this though.

**Comment by NathanKell** [comment]
Ugh I failed at merging it at the time and now it's conflicted again...

**Comment by Capkirk123** [comment]
Should be fixed now

**Pull request merged**
