### PR TITLE
Deprecate the Engine Pre-cooler and Engine Nacelle.

### PR DESCRIPTION
**Pull request by arrowmaster**
These parts only function as fuel tanks and have incorrect descriptions implying they have functions that they do not. Lets hide these noob traps.

### CODE REVIEW

**Comment by arrowmaster** [comment]
I didn't notice when making these that they do actually have an intake configuration. That intake configuration is being stripped out somewhere as everyone reports these parts do not have an intake in game. The parts should either be deprecated or the both the intake configuration needs fixed to not be stripped out AND the descriptions need updated to remove false information about such as precooling air that make it sound like they do more than just function as an intake.

**Comment by Capkirk123** [comment]
Does this rely on https://github.com/KSP-RO/RealismOverhaul/pull/2790?

**Comment by arrowmaster** [comment]
> Does this rely on #2790?

No this uses the existing deprecation behavior. If this PR gets merged then #2790 will need updated to change these to use its new behavior.

**Comment by arrowmaster** [comment]
Updated to be compatible with #2790

**Pull request merged**
