### PR TITLE
RO SXT Command updates/fixes

### PR DESCRIPTION
**Pull request by PhineasFreak**
* Add RO support for the new probe core (Probodobodyne QUBC "Warbler").
* Fix some typos.

### CODE REVIEW

**Comment by NathanKell** [comment]
Is it a nearly spherical solar panel coverage? If so, does it use solar panel type SPHERICAL?

**Comment by PhineasFreak** [comment]
This probe core is a "hacked together" one: it does not have built - in solar panels but it uses instead MODEL{} nodes to add 4 stock surface - attachable ones (zoom inside the part while in the editor(s) and you will see). I had no idea how to correctly set up these panels but i assume that the spherical model could work?

**Comment by NathanKell** [comment]
Ah, yup! A single MODEL'd in solar panel, with SPHERICAL. The transform direction shouldn't matter, just position.

**Comment by NathanKell** [comment]
How is this coming? I'd really like to release a final RO before 1.1.3 comes out.

**Comment by PhineasFreak** [comment]
I did not manage to get it to work...

**Pull request merged**
