### PR TITLE
TACLS Sabatier Reactor Large updated to new system

### PR DESCRIPTION
**Pull request by alimoncul**
Sabatier Reactor Large updated to new system

### CODE REVIEW

**Comment by stratochief66** [comment]
@alimoncul I ~think~ most of these PRs of your are covered by #1413, but I may be wrong. I will keep your PRs open until I've compared them all to ensure I'm not losing anything.

**Comment by alimoncul** [comment]
@stratochief66 roger that 👍  @PhineasFreak gave this task to me, i didn't check previous pull request 😄

**Comment by PhineasFreak** [comment]
@alimoncul i assumed that you checked what parts of the TACLS were already covered by other PRs.

**Comment by alimoncul** [comment]
@PhineasFreak ups nope

**Comment by stratochief66** [comment]
Yeah, fair enough.

I believe anything that uses a TACLS module, like FASA LS parts will require TACLS config changes. I'm going to start a new Issue so I can keep track of odd bugs I find while testing 1.2 with FASA, so I can go back and correct them.

**Comment by PhineasFreak** [comment]
@stratochief66 thankfully our own @rsparkyc did most (all?) of the work required to update the TACLS modules: #1468

**Pull request closed without merging**
