### PR TITLE
Bahamuto Adjustable Landing Gear

### PR DESCRIPTION
**Pull request by winged7**

### CODE REVIEW

**Comment by NathanKell** [comment]
As with the B9 Pwings--though I don't recall whether I did this RO side or RP-0 side, it's been a while--I think it's worth having different-cost, different-mass versions of these for different temperature ranges. No need to pay the mass and cost for spaceplane-level shielding if you're building an X-1 (and no reason you should have 2500 K capable landing gear from the starting node). I _think_ 

Ah, quick check says I did it here. I'd suggest giving these the same treatment that I gave the B9 pwings - does the plugin used allow variable mass multipliers?

With that all done we should probably move to RP-0 recommending these, same as it recommends B9 Pwings.

**Comment by winged7** [comment]
So one early for subsonic planes, one for supersonic and one type for spaceplanes?

**Comment by NathanKell** [comment]
Yep, with appropriate changes in mass if possible, and also strength if possible maybe? I dunno.

**Comment by winged7** [comment]
Strength? I can't see anything like that, only max temp and mass.



Here is full config for one of the landing gears:

PART
{
    // --- general parameters ---
    name = BD_Adj_LG_Side
    module = Part
    author = BahamutoD

    // --- asset parameters ---
     MODEL
    {
        model = AdjustableLandingGear/Parts/bdAdjustableLandingGear/model
        texture = texture, AdjustableLandingGear/Parts/bdAdjustableLandingGear/texture
    }
    rescaleFactor = 1

    // --- node definitions ---
    node_attach = 0, 0, 0, 0.0, 1.0, 0.0, 3

    // --- editor parameters ---
    TechRequired = landing
    entryCost = 3300
    cost = 550
    category = Utility
    subcategory = 0
    title = Adjustable Landing Gear (Small)
    manufacturer = BahamutoDynamics
    description = An adjustable landing gear with a single wheel.

    // attachment rules: stack, srfAttach, allowStack, allowSrfAttach, allowCollision
    attachRules = 0,1,0,1,1

    // --- standard part parameters ---
    mass = 0.09
    thermalMassModifier = 4.0
    dragModelType = default
    maximum_drag = 0.3
    minimum_drag = 0.2
    angularDrag = 1
    maxTemp = 2000

    crashTolerance = 60
    breakingForce = 100
    breakingTorque = 100
    bulkheadProfiles = srf
    PhysicsSignificance = 1
	
	EFFECTS
    {
        brakes
        {
            AUDIO
            {
                channel = Ship
                clip = AdjustableLandingGear/Sounds/wheelBrakes
                volume = 0.0 0.0
                volume = 1.0 0.8
                pitch = 0.0 0.7
                pitch = 1.0 1.0
                loop = true
            }
        }
        touchdown
        {
            AUDIO
            {
                channel = Ship
                clip = AdjustableLandingGear/Sounds/tireScreech
                volume = 0.0 0.0
                volume = 1.0 1.0
                pitch = 0.0 0.85
                pitch = 1.0 1.0
                loop = false
            }
        }
        gearRetract
        {
            AUDIO
            {
                channel = Ship
                clip = AdjustableLandingGear/Sounds/gearDeploy
                volume = 0.0 0.0
                volume = 1.0 1.0
                pitch = 0.0 0.0
                pitch = 1.0 1.0
                loop = false
            }
        }
    }

	MODULE
	{
		name = BDAdjustableLandingGear
		animationName = emptyAnimation
		baseMass = 0.09
		boundsCollider = bounds
		
		//doors
		transformsToMirror = RearDoorHolder
		doors1 = Cube_001,Cube_003          //doors open and close on deploy
		doors2 = Cube_002                   //doors stay open on deploy
		doorSpeed = 70
		
		//tilt transforms
		tiltTransformName = tiltAxis
		tiltTargetTransformName = tiltTarget
		tiltRetractTargetTransformName = tiltRetractTarget
		
		//deploy transforms
		deployTransformName = holder
		deployTargetTransformName = deployTarget
		retractTargetTransformName = retractTarget
		
		//wheel transforms
		wheelHingeTransformName = Wheel
		retractedWheelTargetTransformName = retractedWheelTarget
		deployedWheelTargetTransformName = deployedWheelTarget
		
		wheelColliderTargetName = WheelHolder
		
		mirrorDeployedWheel = true

		maxTilt = 30
		minTilt = -30
		minHeight = 0.2
		maxHeight = 0.8
		
		maxWheelAngle = 60
		
		stageNormTime = 0.45
		
		suspensionSpring = 32
        suspensionDamper = 8
		
		wheelRadius = 0.305
		
		//steering
		steeringTransformName = WheelHolder
		steeringRotationRate = 60
		maxSteerAngle = 25
		
		//brakes
		brakeTorque = 55
		maxBrakeTorque = 125
		
	}
	
	
	MODULE
	{
		name = BDModuleLookAtConstraint
		
		targetName = SupportBarCyl
		rotatorsName = SupportBar
		upAxis = y
			
	}
	
	MODULE
	{
		name = BDModuleLookAtConstraint
		
		targetName = Piston
		rotatorsName = CylinderHolder
		upAxis = y
			
	}
	
	MODULE
	{
		name = BDModuleLookAtConstraint
		
		targetName = Cylinder
		rotatorsName = Piston
		upAxis = y
			
	}
	
	MODULE
	{
		name = BDModuleLookAtConstraint
		
		targetName = SupportBar
		rotatorsName = SupportBarCyl
		upAxis = y
			
	}
	
	MODULE
    {
        name = FSBDwheel
        wheelColliderName = wheelCollider
        //boundsCollider = bounds
        wheelMeshName = WheelModel
        suspensionParentName = Wheel
        disableColliderWhenRetracted = True
        disableColliderWhenRetracting = True
        disableColliderAtAnimTime = 0.5
        animationName = emptyAnimation
        rotationAdjustment = -5.2
        deployedDrag = 0.2
		brakeTorque = 55

        // wheel motor settings
        motorEnabled = false
        motorTorque = 20
        maxSpeed = 10
        resourceConsumptionRate = 0.05
		reverseMotorSet = true

        // brake emissive
        brakeEmissiveObjectName = SupportBarTarget
        onEmissiveColor = 1, 0.3, 0
        offEmissiveColor = 0, 0, 0
        deployingEmissiveColor = 0.1, 0.55, 1.0
        disabledEmissiveColor = 0, 0, 0

        // wheel collider
        overrideModelFrictionValues = True
        overrideModelSpringValues = False
        overrideModelSuspensionDistance = False

        forwardsStiffness = 1
        forwardsExtremumSlip = 0.6
        forwardsExtremumValue = 500
        forwardsAsymptoteSlip = 2
        forwardsAsymptoteValue = 400

        sidewaysStiffness = 1
        sidewaysExtremumSlip = 0.6
        sidewaysExtremumValue = 60
        sidewaysAsymptoteSlip = 20
        sidewaysAsymptoteValue = 1

        //wheelColliderRadius = 0.305
        //suspensionSpring = 32
        //suspensionDamper = 9
        suspensionTargetPosition = 0

        // FX
        useCustomParticleFX = true
        smokeFXtextureName = AdjustableLandingGear/Parts/bdAdjustableLandingGear/particleTexture
        startRetractEffect = gearRetract
        startDeployEffect = gearRetract
    }
	
	MODULE
    {
        name = FSwheelAlignment
    }
	

	
	MODULE
    {
        name = BDTextureSwitch
        moduleID = 0
        objectNames = Cube_002;Cube_001;Cube_003
        textureRootFolder = AdjustableLandingGear/Parts/bdAdjustableLandingGear/
        textureNames = texture;textureBlack
        textureDisplayNames = Unshielded;Shielded
        nextButtonText = Toggle Heat Shielding
        statusText = Heat Shielding
        switchableInFlight = false
        //showPreviousButton = false
    }



}

**Comment by winged7** [comment]
I've made some changes (see below) but soon I realized that it destroyed some functionalities like scaling mass with size ( mass is not scaling with size) so I decided to left it as it is.


@PART[BD_Adj_LG_Side]:FOR[RealismOverhaul]
{
	%RSSROConfig = True
	//%maxTemp = 2273.15
	%skinMaxTemp = 2500
	@mass = 0.1
}
+PART[BD_Adj_LG_Side]:AFTER[RealismOverhaul]
{
	@name = BD_Adj_LG_Side_Early
	@temp = 300 // total guess 
	@mass = 0.06 
}

+PART[BD_Adj_LG_Side]:AFTER[RealismOverhaul]
{
	@name = BD_Adj_LG_Side_Supesonic
	@temp = 800
	@mass = 0.08
}



@PART[BD_Adj_LG_Medium]:FOR[RealismOverhaul]
{
	%RSSROConfig = True
	//%maxTemp = 2273.15
	%skinMaxTemp = 2500
	@mass = 0.15
}
+PART[BD_Adj_LG_Medium]:AFTER[RealismOverhaul]
{
	@name = BD_Adj_LG_Medium_Early
	@temp = 300 // total guess 
	@mass = 0.09 
}

+PART[BD_Adj_LG_Medium]:AFTER[RealismOverhaul]
{
	@name = BD_Adj_LG_Medium_Supersonic
	@temp = 800
	@mass = 0.12

}



@PART[BD_Adj_LG_Large]:FOR[RealismOverhaul]
{
	%RSSROConfig = True
	//%maxTemp = 2273.15
	%skinMaxTemp = 2500
	@mass = 0.2
}
+PART[BD_Adj_LG_Large]:AFTER[RealismOverhaul]
{
	@name = BD_Adj_LG_Medium_Early
	@temp = 300 // total guess 
	@mass = 0.12
}

+PART[BD_Adj_LG_Large]:AFTER[RealismOverhaul]
{
	@name = BD_Adj_LG_Medium_Supersonic
	@temp = 800
	@mass = 0.16
}

**Comment by NathanKell** [comment]
Ok, so just 300 and 800 maxtemps seem fine then.

**Comment by winged7** [comment]
Nathan but as I said before I decided to left it as it is, I mean the first version without dividing it into early, supersonic, spaceplanes. As I said earlier dividing it creates some serious issues with stock funcionalities

**Comment by NathanKell** [comment]
Why does dividing it and just changing max temperatures make any difference to functionality?

**Comment by winged7** [comment]
I think that parameter: "baseMass = 0.09" is involved here.

**Comment by NathanKell** [comment]
Right. So like I said, ignore changing mass for now, and just have the three different max temperature versions, otherwise identical. That alone should be enough for cost and technode differentiation.

**Comment by winged7** [comment]
Updated  - now without any issues.

**Comment by NathanKell** [comment]
Um you seem to be setting a 'temp' field, but that doesn't exist.
Did you maybe mean maxSkinTemp ?

**Comment by winged7** [comment]
updated

**Comment by NathanKell** [comment]
Um, I still think skinMaxTemp would be better than maxTemp--right now you've changed some of them to have new skinMaxTemp values, but others to have new maxTemp values?

**Comment by winged7** [comment]
updated

**Pull request merged**
