### PR TITLE
Split X-405H proposals

### LINKED ISSUE #1819: X-405-H - adjustments and upgrades
Been doing a bit of research on the canceled X-405-H engine intended for the Vega upper stage of Atlas

Sources:
1) [Space Launch Report](http://www.spacelaunchreport.com/atlasnot.html) (Ed Kyle's site, I believe we've considered this to be reliable in the past)
2) [Alternate Wars](http://www.alternatewars.com/BBOW/Space_Engines/GE_Engines.htm) (Big Book of Warfare / Space Engine Encyclopedia)
3) [_History of Liquid Propellant Rocket Engines_](https://books.google.com/books?id=s1C9Oo2I4VYC&q=vega#v=snippet&q=vega&f=false) (book by George Paul Sutton)

Current stats in RO:
* Thrust: 156.3 kN
* Isp: 311s
* Ignitions: 2
* Burn time: 195s

1) Stats from Space Launch Report
* Engine Name: 405H-2
* Thrust: 156.3 kN
* Isp: 311s

2) Stats from Alternate Wars
* Engine Name: 405H
* Thrust: 150.5 kN
* Isp: 300s
* Expansion ratio: 25
* Burn time/ignitions: design conditions not specified, but was ground tested at 2000s and 12 ignitions

3) Stats from _History of Liquid Propellant Rocket Engines_
* Engine Name: 405H
* Thrust: 150.5 kN
* Isp: 300s
* Expansion ratio: 25
* Ignitions: 3 (using hypergolic ignition fluid)

There are definitely two sets of thrust/Isp numbers.  So this either means that one set is wrong, or that there was more than one variant.  The multiple variants hypothesis seems more plausible to me for 3 reasons:
* Both sets of numbers correspond to about the same fuel flow, ~51 kg/s (i.e. turbomachinery is the same with a different nozzle)
* Space Launch Report refers to the engine as 405H-2, which suggests a variant
* Pictures I can find do seem to show two nozzle variants: [#1](http://www.alternatewars.com/BBOW/Space_Engines/GE_Vega_Engine.png) and [#2](http://www.b14643.de/Spacerockets_2/United_States_4/Atlas-Vega/Gallery/Vega_1.jpg)

I think it makes sense to up the base ignitions from 2 to 3 given that (3) states specifically that this was the number of ignitions.

But would it be reasonable to have both variants in RO?  It seems like any changes happened before the planned first flight in 1960, but it does seem like both actually existed at some point in time.

If so, would it make sense to change any stats besides the thrust and Isp?  The static test suggests that the engine could have burned longer and with more ignitions but (a) The rated stats probably wouldn't have affected that (b) Ignitions would have been limited by onboard ignition fluid and (c) We don't really currently have a way to specify what the overburn penalty is (it's hard-coded currently).

And if we did have two variants, what nodes would they unlock in?  Source (1) suggests that the Atlas-Vega program both started and ended in 1959

### PR DESCRIPTION
**Pull request by Capkirk123**
Split X-405H proposals into one config without restart, and one with restart. Also adjust mass a bit based on Convair documents.

After rereading the Convair final report, it seems that while restart was eliminated from Atlas-Vega due to the presence of the third stage, the engine still possessed the capability, and there was still interest in a two-stage Atlas-Vega with restart capability. I split the X-405H into two configs, the basic X-405H without restart as was to be flown on the first Atlas-Vega launches, and the X-405H-2 with restart, with mass guesstimated based on mass breakdowns of the 3-stage and 2-stage proposals.

Fixes #1819

### CODE REVIEW

**Review by DRVeyl — APPROVED** [review]
Looks good to me.  Is slightly breaking in that things using X-405H expecting the re-ignitions now don't have it.

**Comment by DRVeyl** [comment]
Should this close <https://github.com/KSP-RO/RealismOverhaul/issues/1819>?

**Comment by Capkirk123** [comment]
Assuming the Convair Final Report is accurate (which it appears to be), then yes. The question of ignitions and engine performance are answered there.

**Comment by Capkirk123** [comment]
Closing this, since I broke something with git

**Pull request closed without merging**
