### PR TITLE
RO Squad Utility Updates/Fixes

### PR DESCRIPTION
**Pull request by PhineasFreak**
* Add RT range and power descriptions for all antennae.
* Fix the size of the Communotron HG-55.

NOTE: the power consumption entry is a temporary measure until RT implements the stock value display system.

### CODE REVIEW

**Comment by NathanKell** [comment]
What is the size reasoning for the HG-55, out of curiosity?

**Comment by PhineasFreak** [comment]
Someone had tried to rescale but because of VSR it failed. Not a personal reason, just because i saw it: https://github.com/KSP-RO/RealismOverhaul/pull/1290/files#diff-b293827331c2c4b24d3c7f33e6c552eaL9

**Comment by NathanKell** [comment]
Ah, gotcha. In that case I'm inclined to leave it at the existing size then. That size seems to fit well.

**Comment by PhineasFreak** [comment]
OK, give me a sec to make the required changes.

**Comment by NathanKell** [comment]
Ah, this may be a 1.9.2 / 1.9.4 thing. I see in 1.9.2 it's the right size with rescale 0.5, is it different in 1.9.4?

**Comment by NathanKell** [comment]
OH I get this now. It's because there were two HighGainAntenna nodes from the AsteroidDay mess. 0.5 does appear to be the correct scale in the end. Sorry for the mess!

**Pull request merged**
