### PR TITLE
Fuel crossfeed, CMES patches & Lionhead solar panels

### PR DESCRIPTION
**Pull request by PhineasFreak**
* [RO] Import CrossfeedEnabler patches into RO.
* [CMES] Add requirement for Helium pressurization for Altair Ascent module & AJ10-190 engine.
* [LH] Add RO support for the Lionhead Aerospace circular solar panels.

### CODE REVIEW

**Comment by NathanKell** [comment]
Looks good, except see #671 - 1.0.5 no longer needs ModuelCrossFeed. If there are some parts you want ingame *toggleable* crossfeed on, then add ModuleToggleCrossfeed (look at 1.0.5's stock decouplers)

**Comment by PhineasFreak** [comment]
Yes, i made the stock radial RCS and Ore tanks, along with some other parts toggle-able, as of commit https://github.com/PhineasFreak/RealismOverhaul/commit/4dc0c42addd81b89a2908decc4b4db115b80783e

**Comment by NathanKell** [comment]
Apologies, I went off the description rather than reading the committed files. :]

**Comment by NathanKell** [comment]
tagging @stratochief66 so he can have a look too :)

**Comment by PhineasFreak** [comment]
I will do a better job commenting my changes in the future, sorry for the misunderstanding.

**Comment by PhineasFreak** [comment]
Also, feel free to delete some of the RS-25 configs. I included them because it felt incomplete not having them all, even if some have +/- 5 kN difference in thrust.

**Comment by NathanKell** [comment]
@stratochief66 repoke :)

**Comment by stratochief66** [comment]
@PhineasFreak 

Could you please stop adding commits to this PR, it makes it nearly impossible to really review it at this point.

As things stand, it looks Merge-able, but with a few changes either in this PR or on a small follow-up.

Many of the lines 'changes', like in the below example are going from rough formatting to other rough formatting, which makes it hard to see what lines were actually changing.
https://github.com/PhineasFreak/RealismOverhaul/commit/f54e6244cab623282527d9c5f040f3a8ef765c88

See this file as an example (I just cite it because I'm pretty familiar with) of how best to format RO files. Both space-tab or tab formats are fine. @NathanKell can probably cite or describe the actual standard better.
https://github.com/KSP-RO/RealismOverhaul/blob/master/GameData/RealismOverhaul/RO_SuggestedMods/FASA/RO_FASA_ApolloCSM.cfg

I only noticed a few material issues in the PR (Kudos on the excellent work, but the formatting & formatting changes make our job much harder to do)

See the link below, it appears you have the FuelCell burning hypergolics. It should burn LOX and LH2, please see the FASA SM as a decent reference for how much and in what ratios.
https://github.com/PhineasFreak/RealismOverhaul/commit/0bc3314203c1410e71b3fc6592720273f016b56d#diff-fcd30c22c9bd4035b3465e237f8f84a1R391

NathanKell pointed out that by not using the ModuleFuelTank this will not be subject to boiloff, which it should be.
https://github.com/PhineasFreak/RealismOverhaul/commit/f54e6244cab623282527d9c5f040f3a8ef765c88



Please look into making these changes and put new commits/ changes beyond these in a new PR. We really appreciate it.

**Comment by NathanKell** [comment]
Echoing stratochief here: as of now, it's very hard to tell what's a change and what's not. In fact, if you're willing, I'd suggest just making your changes over a fresh copy of HEAD, to make clear exactly what the changes are. Apologies for not mentioning this earlier, only had time for some quick spot-checks before.

**Comment by PhineasFreak** [comment]
Sorry, i am still a newbie when it comes to GitHub, i did not know how to separate PRs (since changes are added automatically to an open PR).

For the rough formatting: either GitHub is a bit retarded (sorry for the word) or something is really wrong with Notepad++. Check the following screenshot and you will understand: https://github.com/PhineasFreak/PicBin/blob/master/PicBin/sample.png

I have NO idea why GitHub does that...and i have been writing part configurations with Notepad++ since forever. It is the first time that u have a problem with indentation.

And the last two commits are not mine. These are just updates merged into my PRs when updating my master from RO master. When i check my changed files, i do not see them.

Thank you for your time!

**Comment by NathanKell** [comment]
That's weird!

Tell you what--let me check this out locally and diff it with the existing files to try to figure out what's actually changed.

**Comment by stratochief66** [comment]
@PhineasFreak We were all there once, and we are more than willing to help :)

The desktop Git client is very powerful for managing branches and commits, I highly recommend it! NathanKell helped me along in learning it.

In your screenshot I notice your visible settings for Notepad++ are different than mine. I'm not sure if it will help, but I will share my current settings. I have UNIX where you have DOS/Windows, and I have UTF-8 w/o BOM where you have UTF-8.

**Comment by PhineasFreak** [comment]
@stratochief66  No, the UTF encoding is not the problem but it was something else: i have to a) write my configuration in Notepad++ and b) select the option "TAB to Space" under "Edit/Blank Operations". That takes care of this problem (although i have to do it for each file separately and i have to edit every patch i ever made and submitted).

The second problem: that one...i blame my stupidity. Yes, i have the default GitHub Desktop client but even then i think i have f!@#ed up big time by using it...

**Comment by NathanKell** [comment]
For now, cherry-picking the Size3 tanks and the crew cabin.

**Comment by PhineasFreak** [comment]
@NathanKell  I left you a note at KSP forum but i should better post it here. If it is possible, delete this PR and any changes i included in it. I will make new PRs in the future for the rest (LH solar panels & generic CMES fixes).

**Comment by NathanKell** [comment]
I responded on the forum, but I'll respond here too. :) Will do, and thank you very much! :)

**Pull request closed without merging**
