### PR TITLE
Let ignoreMass, massOffset, etc work for bimodal engines

### LINKED ISSUE #2794: EngineVariants_Config.cfg doesn't support bimodal engines
[EngineVariants_Config.cfg](https://github.com/KSP-RO/RealismOverhaul/blob/master/GameData/RealismOverhaul/Engine_Configs/EngineVariants_Config.cfg) applies a bunch of patches to ModuleEngineConfigs, and is unaware that there are ModuleBimodalEngineConfigs now.

Haven't gone looking whether any existing parts are impacted; hopefully not. But will be confusing to anyone trying to use these features with bimodal engines in the future.

I'll be fixing the massOffset bit because I'm poking at it; but won't be touching the rest.

### PR DESCRIPTION
**Pull request by lpgagnon**
fixes #2794

### CODE REVIEW

**Comment by al2me6** [comment]
IMO you should just change the original patch to target `Module*EngineConfigs` instead.

**Comment by lpgagnon** [comment]
I'd worry about that catching things it shouldn't, but whatever maintainers think is best.

**Comment by Capkirk123** [comment]
I also support converting everything to Module*EngineConfigs, all of those patches should be safe to run on ModuleBimodalEngineConfigs.

**Comment by lpgagnon** [comment]
I can change them all in this PR, but I won't test anything beyond what I've already tested

**Comment by lpgagnon** [comment]
done. https://github.com/KSP-RO/ROEngines/pull/188 still works with the switchover; no further testing done

**Comment by Capkirk123** [comment]
Tested, nothing obviously breaks. Should be good to go.

**Pull request merged**
