### PR TITLE
OLDD Saturn V

### PR DESCRIPTION
**Pull request by PhineasFreak**
Resubmitted because of merge conflicts.

### CODE REVIEW

**Comment by stratochief66** [comment]
commit#2:
This sources gives a min mass for the LMA of 3943lbs, which is 1.9715 tons.
http://history.nasa.gov/SP-4029/Apollo_18-19_Ground_Ignition_Weights.htm
This sources (which looks to ahve some unit issues, listing ft instead of lb in many places) lists 6871 or 3.4355 tons.
http://history.nasa.gov/SP-4029/Apollo_18-12_Launch_Vehicle-Spacecraft_Key_Facts.htm

while the FASA variant has a mass of 0.651T, which is probably low, but currently works.
http://history.nasa.gov/SP-4029/Apollo_18-12_Launch_Vehicle-Spacecraft_Key_Facts.htm

If you could discuss what brought you to 1.8T I would appreciate it. :)

**Comment by stratochief66** [comment]
With so many changes, this probably needs to be reviewed in-game as well. Could you please provide me a craft file to go along with this PR?

**Comment by stratochief66** [comment]
commit#1:
This source did not link through for me.
https://github.com/PhineasFreak/RealismOverhaul/commit/e94fcaebd058bec04056b1633ab55f8487ada061#diff-a602d59da70009e7364b7899ed890f97R7

**Comment by PhineasFreak** [comment]
Frack, i forgot to add the craft file from the previous PR. Yes, it has extensive changes because the previous configs were hardly compatible with the current RO and i had some problems with nullrefs from some launch clamp modules. In the end, i just deleted them all and started from scratch...

**Comment by PhineasFreak** [comment]
Weird, i just tested the link and it worked...

**Comment by stratochief66** [comment]
I deleted my comment, as the 4th time I tried, it worked :)

**Comment by stratochief66** [comment]
commit#1:
https://github.com/PhineasFreak/RealismOverhaul/commit/e94fcaebd058bec04056b1633ab55f8487ada061#diff-a602d59da70009e7364b7899ed890f97R30

could you just use % on the previous line, as there will only ever be one minimum_drag?

**Comment by PhineasFreak** [comment]
Yes, a typing error on my end. Fixed.

**Comment by PhineasFreak** [comment]
And for the SLA: the Launch Vehicle Spacecraft Key Facts only mentions the size of it, not the mass and so the units are correct. The SLA mass is the average of all Apollo flights.

**Comment by stratochief66** [comment]
Unless the original part definition has multiple CoMOffsets (and I can't imagine why it would) I don't see why this would be necessary:
https://github.com/PhineasFreak/RealismOverhaul/commit/e94fcaebd058bec04056b1633ab55f8487ada061#diff-a602d59da70009e7364b7899ed890f97R39

**Comment by PhineasFreak** [comment]
Unfortunately, it has one near the top of the original .cfg and one where i replaced it:

CoMOffset = 0, 0, 0
CoMOffset = 0, 1, 0

**Comment by stratochief66** [comment]
So, craft file?

**Comment by PhineasFreak** [comment]
Here, i uploaded yesterday: https://github.com/PhineasFreak/RealismOverhaul/commit/9f250309f04e0bb807938d49580629efeceb3461

**Comment by stratochief66** [comment]
And to boot, I can't find a link to download the OLDD Saturn V mod itself. Do you have one?

**Comment by PhineasFreak** [comment]
Took me a bit because it was buried in the KSP forum thread OP but here it is (dropbox link): https://www.dropbox.com/s/85gipo5xt80piy7/SATURN-V-APOLLO%20%28v.1.4.%29.zip

**Comment by stratochief66** [comment]
Thankee.

Tried a quick test launch, the retros on the first stage reported having insufficient resources to ignite. I will test it a bit more thoroughly later.

**Comment by PhineasFreak** [comment]
No, the electricity requirement was for the "initial" start, like the real ones. Can you do me a favor and check the S-IC for ElectricCharge? It should have about 35 units, enough for the F-1 ignitions and for the S-IC flight time.

**Comment by stratochief66** [comment]
It has 15, but that gets drained away well before S-IC burnout, probably due to resource flow. @NathanKell, is there a flow mode might stop the EC from flowing out of the S-IC but would allow the surface attached retros to take it? I don't imagine one exists...

**Comment by PhineasFreak** [comment]
Damn, in my tests it was enough...we could increase the electricity capacity though.

Let me do another quick patch.

**Comment by stratochief66** [comment]
Beyond that, it tested well. Good to merge?

**Comment by PhineasFreak** [comment]
Except from some mass values in the comments section that i would like to correct, it is good to go.

**Comment by stratochief66** [comment]
Correct away, no rush. I will come back and merge it only after you've given me the thumbs up in the comments here.

**Comment by PhineasFreak** [comment]
OK, now my OCD is satisfied! @stratochief66 you are ready to proceed.

**Pull request merged**
