### PR TITLE
SSTU boosters and upper stages

### PR DESCRIPTION
**Pull request by A1Ch1**
Add plumes to 2 and 3-segment RSRMs and 2 and 3 engine RS-25s

RSRMs:
Add thrust curves to 2 and 3-segment motors
Adjust RSRM Isp values (different expansion ratios) and mass (no recovery hardware)
Add to descriptions of RSRM and RSRMV
Adjust manufacturers
Adjust thrust tail off of RSRM and RSRMV

Upper stages:
Add to ICPS volume (LH2 tank stretch of 18 inches) and slightly increase dry mass
Change ICPS engine to RL10C-2 (stats remain the same)
Change EUS engine to RL10C-1 (baselined engine at POD, could change in PDR but has been no sign so far)
Adjust EUS to 130 t propellant (POD figure)

### CODE REVIEW

**Comment by A1Ch1** [comment]
Hold off on merge until I fix 3-segment - thrust curve changed in Orbital ATK catalog

**Comment by stratochief66** [comment]
@A1Ch1 Thanks for the tweaks! We should be approaching pretty good accuracy as better data comes out about what they are building.

Could you please link your sources? I want to add them to mine.

**Comment by A1Ch1** [comment]
Yes, the thrust curves for the 2 and 3 segments are in the Orbital ATK product guide linked at the bottom of the config: https://www.orbitalatk.com/flight-systems/propulsion-systems/launch-abort-motor/docs/orbital_atk_motor_catalog_(2012).pdf

The EUS and ICPS information are from NASASpaceflight L2, which is paywalled so I can't directly quote. But it is a summary of the EUS configuration at POD (Point Of Departure) along with further comments indicating the configuration is still the one being looked at, and a description of the ICPS as of CDR.

**Comment by A1Ch1** [comment]
Thrust curve for 3-segment:
https://docs.google.com/spreadsheets/d/103e6zXcCBJiEdr69XsDDqqeTsZqOWJgZ8wVrfV3Cj6Q/edit?usp=sharing

rsrm3k
rsrm3

**Comment by stratochief66** [comment]
Can you add that curve as a commit, then we can merge?

**Comment by A1Ch1** [comment]
Yes there were a couple of other changes I noticed needed to be made to the two segment booster. I will commit after work

**Comment by A1Ch1** [comment]
Adjusted thrust tail off and propellant mass for 2-segment. Added curve to 3-segment. Added plumes to remaining RSRMs and RS-25 clusters. Good to go

**Pull request merged**
