### PR TITLE
RO RSB Delta IV

### PR DESCRIPTION
**Pull request by PhineasFreak**
* Add RO support for the Real Scale Boosters Delta IV launch vehicle family.

### CODE REVIEW

**Comment by stratochief66** [comment]
These PRs are really becoming a mess @PhineasFreak. Can you post #xxx links in each PR that relies on the content of other PRs?

**Comment by PhineasFreak** [comment]
Only the engine configs from https://github.com/KSP-RO/RealismOverhaul/pull/915.

**Comment by stratochief66** [comment]
Look alright. You seem to have used a 'kerolox upper' plume on the RS-68, which is a 'hydrolox lower' engine. Could you change that over?

**Comment by PhineasFreak** [comment]
The RS-68 may be a hydrolox engine but the FX is correct because it is an cooled by ablation: https://www.youtube.com/watch?v=ermr2spJYKo

**Comment by stratochief66** [comment]
yeah, good call on the FXs. I watched a few videos of the RS-68, and it definitely glows yellow like a kerolox, but I'm fairly sure the core engine wasn't producing copious amounts of smoke.

**Pull request merged**
