### PR TITLE
Global Configs Squad Continued

### PR DESCRIPTION
**Pull request by SirKeplan**
Do not merge yet.

### CODE REVIEW

**Comment by SirKeplan** [comment]
I re-instated the gimbal on the NERVA, however the engine model doesn't visibly gimbal, am i using the wrong transform??

apart from that, nothing else i need to add to this PR.

**Comment by NathanKell** [comment]
My guess is Ven's model again doesn't support gimbaling since it was removed from the stock NTR in 1.0.

**Comment by NathanKell** [comment]
(Goes on the list of mu's to check I guess, when you have a sec--you have taniwha's blender mu importer, right? )

**Comment by SirKeplan** [comment]
@NathanKell hehe, nope, but i will get it.

**Comment by SirKeplan** [comment]
@NathanKell neither of those Ven's models support gimbal. thrustTransform is an empty node

**Pull request merged**
