### PR TITLE
Space Shuttle  - Mike NZ

### PR DESCRIPTION
**Pull request by winged7**
SRB should be surface attachable exactly like stock SRB but I don't know how to make it, someone could help me? Now it is very hard, almost impossible to attach.

Also RS-25 and OMS require Real Plume config.

### CODE REVIEW

**Comment by FFCJoseEduardo** [comment]
you need to find this line attachRules = 1,0,1,1,0 and change it to 1,1,1,1,0

however I would suggest to increase the node size instead since it needs to be attached to the decoupler, and if you try surface attaching you either will need to use a stock decoupler or will attach to the tank, as it will be even harder to attach to the decoupler from the pack

**Comment by stratochief66** [comment]
@winged7 

Do you want to work on the SRB attachment and engine Plumes in this PR, or will you open another one for that?

**Comment by winged7** [comment]
Wait. I need to change attachRules and check how it works in my game.

Regarding Real Plume: I have seriously no idea how to make proper config so someone else should do it.

**Comment by winged7** [comment]
@FFCJoseEduardo  I think that it's better to make them workable with stock decouplers.

**Comment by stratochief66** [comment]
@winged7 It isn't too hard, come by the IRC sometime and I can walk you through it.

https://github.com/KSP-RO/RealismOverhaul/blob/master/GameData/RealismOverhaul/RealPlume_Configs/SSTU/SSTU_ShipCore_B_ENG4.cfg#L1-L36

For the RS-25 you can basically just copy the code from this, throw it into the proper place and file name, and overwrite with the proper part name and replace the transformName, and that is more than good enough.

**Comment by winged7** [comment]
Ok, now it is ready to merge.

As to Real Plume I will try to make configs, but later, not today.

**Comment by stratochief66** [comment]
Gotcha. Thanks again!

**Pull request merged**
