### PR TITLE
BDB Global Patches

### PR DESCRIPTION
**Pull request by AnticlockwisePropeller**
Create a global config to remove Bluedog Design Bureau part modules that would conflict with RO mods - specifically engine reliability and cryogenic fuel boiloff.

### CODE REVIEW

**Comment by stratochief66** [comment]
This seems reasonable.

@PhineasFreak would it be more efficient to have this patch only run if BDB is installed? Or would we not expect a performance difference, searching every part for these modules?

**Comment by pap1723** [comment]
This should definitely be set as :NEEDS[BluedogDB] as it only needs to run
if that is installed.

**Comment by PhineasFreak** [comment]
@pap1723 @stratochief66 yes, an additional check to see if BDB is both easy to implement and needed (better to skip patching and apply it only when BDB is installed than checking all available parts).

**Comment by AnticlockwisePropeller** [comment]
Added the NEEDS: criterion, as suggested!

**Pull request merged**
