### PR TITLE
Fuji RO configs

### PR DESCRIPTION
**Pull request by mikusingularity**
RO_Tantares_Fuji_New.cfg should replace [KSP install folder]\GameData\RealismOverhaul\RO_SuggestedMods\Tantares\RO_Tantares_Fuji.cfg

Fuji_Kerbalism.cfg requires Kerbalism (obviously), where should this go?

ROS-FujiSolar.cfg and ModelData-FujiSolar.cfg should go in ROSolar, should I make a separate PR for that?

### CODE REVIEW

**Comment by NathanKell** [comment]
I don't know the answer to those questions - @pap1723 is best positioned to address the ROSolar one, but I think if you're configuring static solar panels you shouldn't be touching ROSolar at all, ROSolar is for procedural solar panels. As for ROKerbalism, maybe @Standecco can answer? I don't know anything about kerbalism configs.

**Comment by DRVeyl** [comment]
The ROSolar configs should move directly into ROSolar.
Look up how we did NFS support in terms of requiring NFS to be installed and referencing the model provided by NFS -- I assume that's what you're intending in writing the Fuji config support.
ROSolar will resize whatever kinds of panels, including rescaling static ones, so that is fine.

**Comment by NathanKell** [comment]
Oh, yeah, if you want the solar panels to be resizable then I guess ROSolar it is. I was just thinking in terms of this being a real (if only paper) design, thus with solar panels of set properties.

**Comment by DRVeyl** [comment]
Slightly confused.  Why does <RO_Tantares_Fuji_New.cfg> display as a 50KB binary file?
Ideal way to do this as a PR is, having forked the repo, actually change the file you want.  (Actually edit the file you're proposing to edit, and that way we can easily review changes rather than examine the whole new file.)

Yes, please PR the ROSolar-related configs for the Fuji part to ROSolar directly.

Will leave to @Standecco to advise where exactly in <https://github.com/KSP-RO/ROKerbalism> that file should go.

**Comment by Standecco** [comment]
For better or for worse, so far all kerbalism configs have so far gone into [KSP-RO/ROKerbalism](https://github.com/KSP-RO/ROKerbalism/). So if you want your changes to be included, you should remove the kerbalism file from this PR and make another one to that repo.

Just note, though, that you should also change `:AFTER[KerbalismDefault]` to a different specifier, becase `KerbalismDefault` is the identifier for the stock profile, which we lack; I think ours is `ProfileRealismOverhaul`, but I might be wrong.

**Comment by NathanKell** [comment]
Bumping this. Any progress, @mikusingularity ?

**Comment by DRVeyl** [comment]
<https://github.com/KSP-RO/ROSolar/commit/e206bb38751c2b04042895dafa360fe47a8847e7> implemented the ROSolar end.  (These patches should be removed from this PR.)

**Comment by Capkirk123** [comment]
Superceded by https://github.com/KSP-RO/RealismOverhaul/pull/2935, https://github.com/KSP-RO/ROKerbalism/pull/159, and https://github.com/KSP-RO/ROSolar/commit/e206bb38751c2b04042895dafa360fe47a8847e7

**Pull request closed without merging**
