### PR TITLE
CMES Pod updates/fixes (part II)

### PR DESCRIPTION
**Pull request by PhineasFreak**
Updates and fixes for the CMES "Pod" parts (second pass).

Changelog:
- Place the Orion LAS at the correct "Utility" category.
- Fix the scale of the Orion EFT and MPCV command modules.
- Fix the thrust, Isp, position and orientation of the Orion EFT and MPCV command modules RCS thrusters (they now operate correctly).
- Decrease the electric charge requirements of the Orion EFT command module.
- Increase the amount of Hydrazine carried by the Orion EFT and MPCV command modules for reently control.
- Remove some unneeded Deadly Reentry patches (taken care by the RO global config).
- Improve the RT compatibilty patches.
- Add Connected Living Space support for all parts that should have it.
- Adjust some insane max temperature values.
- Update the part titles and the descriptions.
- Fix formatting (tabs, false spacing).

[Alternate diff ignoring whitespace changes.](https://github.com/KSP-RO/RealismOverhaul/pull/1381/files?w=1)

### CODE REVIEW

**Comment by stratochief66** [comment]
Thanks! I'll be beginning to review these PRs soonish. The ?w=1 addition to see changes ignoring whitespace changes is a super cool feature, thanks for pointing it out for me :)

**Comment by PhineasFreak** [comment]
Just a note for these two specific PRs: they are missing any new parts because it would break a lot the diff. The RO configs for them will be added after the initial PRs have been successfully merged.

**Comment by SirKeplan** [comment]
Hi, wondering what the status of this is? i can see a few issues. The Orion pods are not set as command modules, and i don't seem to have all the parts to make a full Orion CSM (like decouplers)

should we merge these as a WIP?

**Comment by PhineasFreak** [comment]
@SirKeplan i would also tag all these configs as WIP. The mod has not been updated for KSP 1.2 so a lot of things might be misconfigured/broken (like the noted part categories).

The new parts are also missing because it would make the diff impossible to check (well, even more difficult that the current one).

**Comment by stratochief66** [comment]
@SirKeplan if you've tested the parts as best you can, then definitely feel free to merge. There are tons (and tons and tons) of parts in CMES, so as PhineasFreak says, it is definitely best that we configure, review, and merge changes in smallish sets like this.

**Comment by PhineasFreak** [comment]
More specifically, parts like decouplers and other structural parts have a separate "RO_CMES_Structural" config that it has not been 100% updated yet but i am working on it. Now that some of the bigger parts of CMES are RO-ready it will be much easier to do that.

Still, crewed parts will have to be updated for the TAC changes but these changes will be minor.

**Pull request merged**
