### PR TITLE
RO VSR Fuel Tank updates

### PR DESCRIPTION
**Pull request by PhineasFreak**
* Add RO support for the Oscar - A propellant tank.
* Add temperature modifiers.
* Simplify resource removal.

### CODE REVIEW

**Comment by NathanKell** [comment]
I'm a bit confused--why set these temps explicitly when other tanks don't and get the usual 1073K (800C) max temp?

**Comment by PhineasFreak** [comment]
I find that 800 °C are higher than most materials can handle (and especially propellant tanks). No reason other than that (you can ask for veto and i will return the values to the default ones).

**Comment by PhineasFreak** [comment]
@NathanKell i found an old issue for the maximum temperatures (https://github.com/KSP-RO/RealismOverhaul/issues/369) and you seemed to support lower temperatures for many parts. Specifically, you mentioned part/skin temperatures in the range of 600/900 and @stratochief66 also wanted it as a 1.1 feature.

**Comment by NathanKell** [comment]
@PhineasFreak I would definitely support such a change. Though I suggest doing so in RO globals to set the base maxtemp to 923 (650 C) and then changing temps where it should be different.

I am unsettled by patching by category; I would be more comfortable if we instead set up a global patcher where we, e.g., said globalTemp = Aluminum or = Titanium or whatever. Or globalTemp=StructuralLow. Whatever, just something that we are sure we are setting rather than doing a category == foo check, which can often be wrong (LES needs high max temp because it's the tip of the rocket).

**Comment by PhineasFreak** [comment]
OK, i started working on a "Global Materials Config" that will include configs for both the thermal (part & skin temperature) and the physical parameters (breaking force & torque). I have some problems getting the values from inside blocks (like the TF configs) but i am sure i will find the way.

**Comment by NathanKell** [comment]
Sounds good! For now I'll merge this in and temps can be tuned later.

**Pull request merged**
