### PR TITLE
Add manufacturer, title, description to AJ_10_138 config

### PR DESCRIPTION
**Pull request by alimoncul**
stratochief66 gave me a tutorial about manufacturer and description editing.v2

### CODE REVIEW

**Comment by stratochief66** [comment]
Looks good! I will leave this open for a bit as a reference.

**Comment by jwvanderbeck** [comment]
Can we get the diameter added to the description please?  This is something that a lot of people overlook, but is supposed to be there.

**Comment by alimoncul** [comment]
Hello jwvanderbeck. AJ10-138 Diameter is 1.53 meters. Should i write 1.53 or 1.5 ? 
Engine Link : http://www.astronautix.com/engines/aj10138.htm

**Comment by stratochief66** [comment]
I'd go with 1.53 if you're anxious to get started. It is easier to remove the extra digit later if that prove necessary.

**Comment by jwvanderbeck** [comment]
@alimoncul As a general rule anything that can't be resized should usually have a diameter listed in the description and I think 2 significant digits, like 1.53m is fine.

**Pull request merged**
