### PR TITLE
SSTU engines

### PR DESCRIPTION
**Pull request by Zarbizaure**
Support for:

- Merlin 1B (stats from wikipedia.fr)

- Merlin 1B vacuum (a bit guessed stats/calcultated by a ratio between Merlin 1C/1CVac stats)

- XLR81 (Agena engine, the SSTU name was just LR81 but design seems to match)

- Add a correct title for the fictive RD-107X engine (RD-107 withouth verniers)

- Plumes for Merlin 1B and Merlin1B Vacuum (copy/pasted from Merlin 1C/1C vac because same bell size)

Also, two files in this SSTU folder (SSTU-RD-0110 and SSTU-RD-107X) have - instead of _ between "SSTU" and "EngineName"
By the way Github failed to merge because I created a new file; you could delete my own SSTU-RD-107X, the only thing to add in this file is a `@title = RD-107X`

### CODE REVIEW

**Comment by Zarbizaure** [comment]
Rescaling the XLR81 broke the plume (it's way too big). Maybe we should add a realPlume one?

**Comment by Zarbizaure** [comment]
And I just noticed that the one who created the M1 from SSTU's RL10-A3 did a mistake: the name should be `SSTU-SC-ENG-M1-RO` instead of `SSTU-SC-ENG-ENG-M1-RO`. I let those who have the rights modify it, if I do it I'll need to create another pull request.

**Comment by SirKeplan** [comment]
@Zarbizaure er, that M1 bit has already been fixed here. b56a6113

**Comment by Zarbizaure** [comment]
Oh thanks. You're right, I did not see your commit (it's still a bit sad to scale up a model :p I prefer to have dedicated ones).
Are the others changes ok?

**Comment by Temeter** [comment]
Some of the earlier Agenas were apparently called LR81, so your guess is correct. ;)

**Comment by Zarbizaure** [comment]
Yes, and the description helped me a bit ;) shadowmage45 referenced the "modell 8096-39" in the part descrition, which is an Agena engine.

I suppose that this part is still heavily WIP, so we'll have to change some things in the future but at least it's there!

**Comment by Temeter** [comment]
I think it's basically just a copy of the F-1B engines, adjusted in size and put in as a placeholder for an Agena.

Same was done with the M1-engine, which is the generic RL-10-Series engine upscaled.

**Comment by Zarbizaure** [comment]
Excepted that the LR81 is a part created by Shadowmage and not by the RO folks; and he said "part geometry will change". So I suppose a proper 3D model for the XLR81 will be released one day.

**Comment by Temeter** [comment]
Yep, that's what I was assuming. I've actually seen a bunch of placeholder stuff when doing the plumes a while ago.

Definitly good to have it placed! Alone for the multi engine thing, which is just sooooooooo effin good in SSTU.

**Comment by SirKeplan** [comment]
Hmm, if we are adding prototype Merlin engines, probably best to add them by putting them in [here](https://github.com/KSP-RO/RealismOverhaul/blob/master/GameData/RealismOverhaul/Engine_Configs/Merlin1_Config.cfg)
Also there is a way to make git recognise renaming a file, unsure of the method for that if using github interface though. if you can fix the conflicts on your end though it would be appreciated.

**Comment by Zarbizaure** [comment]
I also though adding it as a new engine config. So I'll change it this evening.
I don't know for Github, I think my forked repo wasn't up to date at all and that's why there is so many conflicts (github is trying to replace files instead of just modifying them). Maybe I will just close this PR and do another one properly.

**Comment by Zarbizaure** [comment]
Pffffew. Tons of comits (I'm bad for multiple files editing) but it should be fine now.

**Comment by Temeter** [comment]
Alright, taking a look at this right now.

You've done a lot of stuff, but would you mind taking a look at the RD-108 gimbals? They are incorrectly set up, rotating on the wrong axis.
They move inside/outside, while they should move 'sideways'. Allows you to steer, but clips through the engine and doesn't give you any roll control.

https://github.com/Zarbizaure/RealismOverhaul/blob/master/GameData/RealismOverhaul/RO_SuggestedMods/SSTU/SSTU_RD-10X.cfg

**Comment by Zarbizaure** [comment]
If you say it. I will take a look at it soon; but maybe it's better to notice Shadowmage and to tell him the issue? That's something that could be fixed from his side, and it would be better for the mod.

**Comment by Temeter** [comment]
It does work in stock. RO config is different (incorrectly) set up. I'm checking a fix right now, gonna report back how it works.

**Comment by Temeter** [comment]
Btw, the propellant and thrust information does need to be in the config. The global configs only update when you change to different variants, otherwise the engines show stock values directly after placing, namely KSPs Liquidfuel/Oxidizer.

**Comment by Temeter** [comment]
This are is the correct paragraph for the gimbals. You can use it on RD-108 and RD-107.

```
    {
        %gimbalRange = 35 
        %gimbalRangeYP = 0
		%gimbalRangeYN = 0
		%gimbalRangeXP = 35
		%gimbalRangeXN = 35
        %useGimbalResponseSpeed = True
        %@gimbalResponseSpeed = 16
    }
```

**Comment by SirKeplan** [comment]
@Temeter uh, not in my experience, it seems to automatically select and use the data in ModuleEngineConfigs

**Comment by Temeter** [comment]
So you're telling me my installation is borked again? >_>

**Comment by SirKeplan** [comment]
@Temeter either that or maybe there is some subtlety i am missing, could it depend on if the `ModuleEngineConfigs` has `configuration` defined or something?

**Comment by jwvanderbeck** [comment]
Possibly because yeah the global configs should apply always not just when you change configs.

**Comment by Temeter** [comment]
I'm a bit suspicious that this is a very recent issue for me. Had the same problem with an Aj10 recently, where it would look onto the stock ressources...

**Comment by Zarbizaure** [comment]
with my FRE engines I had the same problem, the config didn't show if I didn't had them directly in the ModuleEngineRF.

@Temeter I'll trust you and add what you said directly in my PR; I have to admitt I have not a lot of time to test right now.

**Comment by Zarbizaure** [comment]
But the RD-108, as a core engine, shouldn't be gimbal-limited, no? It has a set a four verniers, one at each corner; so I suppose we don't have to change anything about this.

**Comment by Temeter** [comment]
@SirKeplan Seems like i got the issue with updating global configs only with your RealFuels.dll with the fixed SSTU pricing. Lets move that discussion into that thread.

@Zarbizaure thanks for the trust, but that's really just a simple modfication. Engines rotate on Y axis, but they needed to rotate on X axis for this model. Checked it ingame, and basically just used the working behaviour from the stock SSTU config.

RD-108 also only gimbals in one axis, its actually very easily visible on the model. Take a look at this picture:
https://upload.wikimedia.org/wikipedia/commons/b/b2/RD-108_Vostok.jpg
You can basically see how these gimbals can move sideways. Moving them inwards would 'clip' them into the main nozzles, which was exactly what happened ingame.

**Comment by Zarbizaure** [comment]
Of course each of them can gimbal on one only axis, but does RO support four different X-axis at the same time? If these axis are related to a particular gimbalTransform object it should work; anyway you tested and told me it works, soI'm changing it again.

**Comment by Temeter** [comment]
It does work. Guess the system was exactly set up to support RD-108 style verniers, they are the most famous vernier supported engines.

**Comment by Zarbizaure** [comment]
Cool! So I think SSTU engines are almost complete on the RO side - until Shadowsmage add new ones, of course.

**Comment by Temeter** [comment]
Took a while, but it was absolutely worth it! Thanks for jumping in and taking care of some more complicated issues. :D

**Comment by Zarbizaure** [comment]
That's nice! SSTU absolutely worth deleting the stock equivalent - I recently restarted a RP-0 career and it's stupid to have a good SSTU model aside a poor model for lots of engine.

**Comment by Temeter** [comment]
Not to mention that my next crewed mars orbit mission is going to be less than 450 parts. Models and functionality are just so good.

I mean, just those engine mounts, they look sooooooo darn good.

**Comment by Zarbizaure** [comment]
Speaking of fuel tanks there is something else we need to do - add these modular fuel tanks to RP-0 (so they won't be fltered as non-RP0).
And maybe we can rename one of them (the Kerolox and Hydrolox are the same in RO) to "SSTU Tak [Procedural][Shielded] and make it a bit more heat-resistant, like what was done with PP? And of course place it later in the tech tree, along the Shielded Procedural Part Tank.

**Comment by Temeter** [comment]
Sorry, got no pictures anymore. :(
To give you a sense of the scale, the departure stage was driven by an M1, and 2xJ2 for correcture burns. 12.000 tons on the pad. Going to Mars is not easy at all. Well, I'm going to go back one day. 

I already thought about adding those tanks, but wondered if they were bugged. Seem to scale fine, tho.

**Comment by Zarbizaure** [comment]
that's sad :p If you fly it back once please do an imgur album :D 

I will probably investigate a bit these (I don't know if they have a correct volume compared to PP) but they still are way better than PP (for straight cones, at least), so they worth a RP-0 config :)

**Comment by Temeter** [comment]
I'll do for sure. Got some nice rocket pics, but sadly nothing of my glorious, oversized mars mission.

Yeah, those thing look much better than proc, even if they aren't as flexible (Mainsailor texture are quite cool tho, got clean historic stuff). Also got Soyuz style tanks with integrated decouplers, which is really clever. Basically a 2 part solution (tank+engine) for strapon boosters!

**Comment by Zarbizaure** [comment]
I think SSTU already wrote a tank size limiter. Anyway I'll look at this later (in the week end maybe?) and I'll try to copy the RP-0 config on PP system. If you have time you can also try doing it, I'll busy for the next two days :p

**Comment by Temeter** [comment]
I also need start actually building rockets for a change, now that SSTU finally works in clusters.^^
Moon first, Mars next.

**Comment by ctiberious** [comment]
There is a slight texture difference between the Kerolox and Hydrolox tanks in SSTU.  Purely esthetic.
I've been working on updates for the lander pods (#1245), all three series of space pods (still to be posted), and the fuel tanks (still to be posted).  I'll get those posted in the next day or two.

**Comment by ctiberious** [comment]
#1276 has all the updates I've been working on with the SSTU pods and fuel tanks.  I ended up closing #1245 and consolidating all my changes into a single PR.

**Comment by Zarbizaure** [comment]
still conflicts...Github, you're making me crazy...

**Comment by SirKeplan** [comment]
@zarbizaure ah i know why it's conflicting.  Should be able to fix anfd merge this later if you haven't already resolved.

**Comment by Zarbizaure** [comment]
Honestly I have no idea what happened (a file modified by another PR maybe?) so I'll let you fix it.

**Comment by SirKeplan** [comment]
Merged, though the Merlin plumes could do with with some more work(Not just the B actually, A and C plumes need looking at too)

**Pull request merged**
