### PR TITLE
SRMs: KW

### PR DESCRIPTION
**Pull request by A1Ch1**

### CODE REVIEW

**Comment by stratochief66** [comment]
Too many changes to one file to allow review by changes, sorry. Could you please make a PR with half of this for review?

**Comment by A1Ch1** [comment]
Yes; I'm on the road this weekend with just my laptop though so it may be a couple of days

**Comment by stratochief66** [comment]
@A1Ch1 
Poke :)

**Comment by A1Ch1** [comment]
Reduced to first third of changes

**Comment by stratochief66** [comment]
Thanks for the breakup. I used these all in game, looking good.

**Pull request merged**
