### PR TITLE
Replace ROKSPedia.ksp

### LINKED ISSUE #2257: 1.8 "The file can not be loaded because it was created for another build target that is not compatible with this platform."
There's a few errors around it.

```
[ERR 23:13:46.504] The file can not be loaded because it was created for another build target that is not compatible with this platform.
Please make sure to build AssetBundles using the build target platform that it is used by.
File's Build target is: 6


[ERR 23:13:46.504] Unknown error occurred while loading 'archive:/CAB-50f8fbe15b4cc1ac99c924902c66acf3/CAB-50f8fbe15b4cc1ac99c924902c66acf3'.

[ERR 23:13:46.504] The AssetBundle 'file://B:\Games\Steam\steamapps\common\RealismOverhaul 1.8\GameData\RealismOverhaul\KSPedia\ROKSPedia.ksp' can't be loaded because it was not built with the right version or build target.

[ERR 23:13:46.504] Error while getting Asset Bundle: The AssetBundle 'file://B:\Games\Steam\steamapps\common\RealismOverhaul 1.8\GameData\RealismOverhaul\KSPedia\ROKSPedia.ksp' can't be loaded because it was not built with the right version or build target.

[ERR 23:13:46.504] AssetLoader: Bundle is null
```

It's a CKAN install of 1.8.1.b

### PR DESCRIPTION
**Pull request by 7ranceaddic7**
FIXES #2257 

This merely replaces the (limited) KSPedia entry for RO.

It will clear the related log error.

I will continue the development from the Wiki and any additional input you would like to see.

The outstanding question is aesthetics. My choices aren't going to be your choices, but all input is welcome.

Next update will include the prefab source files.

(Also, does anyone know if it is against licensing to create a standardized AssetBundle that can be imported and *[poof]* you have an operational KSPedia editor instead of having to slog through the convoluted morass?)

### CODE REVIEW

**Comment by siimav** [comment]
Can confirm that the KSPedia works. I'm curious though why it's now 2 files instead of 1?

**Comment by 7ranceaddic7** [comment]
Mostly because I'm still learning KSPedia ins-and-outs.

**Comment by siimav** [comment]
Are you still working on it or should it get merged now?

**Comment by 7ranceaddic7** [comment]
So here's the deal:

Both files contain the same info.  DELETE one.

That will return RO's KSPedia to the same state as before the problem began.  (Which, I'll add, was minimal at best.)

I was hoping for some feedback on the differences in formatting.

I haven't worked an additional information into it.  I can and will if desired.  I'm not sure what parts of the Wiki, or any other sources, anyone would like to have in there.

I don't play RO, so I really can't make that judgement call.

**Comment by DRVeyl** [comment]
I'm going to go ahead and merge this as-is, to at least get into a working state.  I don't think there is a unified view of aesthetics for the RO team to provide.  Seeing no other comments, I think we'll just take this and see if the wider community has feedback.

**Pull request merged**
