### PR TITLE
Dependency check

### PR DESCRIPTION
**Pull request by PhineasFreak**
* Just a small check for the Vanguard probe when RP-0 is not installed.

### CODE REVIEW

**Comment by NathanKell** [comment]
Should be RP-0 not RP0

**Comment by PhineasFreak** [comment]
Right now i am checking for the DLL. Is the internal name different than the DLL name?

**Comment by NathanKell** [comment]
Nah, but we use the folder name (RP-0) so RP-0 patches run on a later pass. Best to use RP-0 in NEEDS as well.

**Comment by PhineasFreak** [comment]
Done!

**Pull request merged**
