### PR TITLE
Hide the bugged miniLandingLeg

### PR DESCRIPTION
**Pull request by Test-Account-KSP**
Hide the bugged miniLandingLeg from the parts list in VAB/SPH and from R&D building

### CODE REVIEW

**Comment by arrowmaster** [comment]
There is already an RO_Deprecation.cfg that will do the hiding. From some of the other configs I think the right way to do with would be with the following.

`@title = #$/title$ (Deprecated)
%deprecated = True`

**Comment by siimav** [comment]
Deprecating isn't really the correct term here since ideally we would only be temporarily hiding the parts. If Restock finally gets the long-awaited release then we would just revert the changes in this PR.

**Comment by Capkirk123** [comment]
Is this good to merge then?

**Comment by siimav** [comment]
Yes, good enough for a temporary (???!) workaround.

**Pull request merged**
