### PR TITLE
CMES Pod new parts & tweaks

### PR DESCRIPTION
**Pull request by PhineasFreak**
Updates for the CMES Pod parts.

Changelog:

* Update the RCS module patching to be compatible with the new "ModuleRCSFX" module.
* Add RO configs for the following missing parts:
    * Orion main parachute pack
    * Observation cupola
    * NASA docking mechanism
    * RSRM parachute pack
    * Orion forward heat shield

[Alternate diff ignoring whitespace changes](https://github.com/KSP-RO/RealismOverhaul/pull/1453/files?w=1)

### CODE REVIEW

**Comment by SirKeplan** [comment]
Not sure why, but `ModuleCommand` gets lost somewhere on the Orion pods, have to change the `@MODULE[ModuleCommand]` to a new `ModuleCommand` declaration for the pods to work.

**Comment by PhineasFreak** [comment]
Well, that one is really weird! Do you have any previous CMES configs somewhere? Although i do not think that it would make any difference.

* [Orion EFT sample image](https://raw.githubusercontent.com/PhineasFreak/PicBin/master/PicBin/Generic_images/cmes_orion_eft.png)
* [Orion MPCV sample image](https://raw.githubusercontent.com/PhineasFreak/PicBin/master/PicBin/Generic_images/cmes_orion_mpcv.png)

**Comment by SirKeplan** [comment]
Nope, no leftover CMES configs at all. very strange. could be because I tested with 1.1.3?

**Comment by PhineasFreak** [comment]
Then there might be something screw-y with the base part configs. If you open the "Orion_pod" and "Orion_pod-B" part configs cam you confirm that they include the following command modules?

* Orion_pod:

```
MODULE
{
	name = ModuleCommand
	minimumCrew = 0	
}
```

* Orion_pod-B:

```
MODULE
{
	name = ModuleCommand
	minimumCrew = 0	
}
```

Also, can you modify the patches not to use the "%" MM modifier and see if that fixes it?

**Comment by SirKeplan** [comment]
original base part configs are fine, this is what i found fixes it
	diff --git a/GameData/RealismOverhaul/RO_SuggestedMods/CMES-WIP/RO_CMES_Pod.cfg b/GameData/RealismOverhaul/RO_SuggestedMods/CMES-WIP/RO_CMES_Pod.cfg
	index 59dc1aa..4851010 100644
	--- a/GameData/RealismOverhaul/RO_SuggestedMods/CMES-WIP/RO_CMES_Pod.cfg
	+++ b/GameData/RealismOverhaul/RO_SuggestedMods/CMES-WIP/RO_CMES_Pod.cfg
	@@ -1971,11 +1971,10 @@
	 
		 !INTERNAL[MK1-2_ASETInternals]{}
	 
	-    @MODULE[ModuleCommand]
	+    %MODULE[ModuleCommand]
		 {
	-        %RESOURCE
	+        %RESOURCE[ElectricCharge]
			 {
	-            %name = ElectricCharge
				 %rate = 0.85
			 }
		 }
	@@ -2209,11 +2208,10 @@
		 !CoDOffset = NULL
		 %bulkheadProfiles = size2, size3
	 
	-    @MODULE[ModuleCommand]
	+    %MODULE[ModuleCommand]
		 {
	-        %RESOURCE
	+        %RESOURCE[ElectricCharge]
			 {
	-            %name = ElectricCharge
				 %rate = 1.35
			 }
		 }
	@@ -2357,9 +2355,8 @@
	 
	 @PART[XOrionPodXbb31|XOrionPodX]:FOR[RealismOverhaul]:NEEDS[DeadlyReentry]
	 {
	-    %MODULE
	+    %MODULE[ModuleAeroReentry]
		 {
	-        %name = ModuleAeroReentry
			 %skinMaxTemp = 3773.15
			 %skinThicknessFactor = 0.05
		 }

**Comment by PhineasFreak** [comment]
Well yes, DRE does not exist for KSP 1.2 yet. But i find it weid that it explicitly requires the module names to be defined, especially since the base configs already include them.

Does anything change if you remove the separate DRE patch?

**Comment by SirKeplan** [comment]
Haven't tested it yet, but that migth be enough to fix it on it's own, however my fix uses the same MM syntax used in the rest of RO, so is probably the best way.

i noticed before this, that ModuleCommand parameters were ending up in ModuleAeroReentry from looking in the MM cache, so it's got to be a case syntax.

**Comment by PhineasFreak** [comment]
OK, i removed the DRE patch anyway since i noticed it. Can you test the alternate ModuleCommand patching that i pushed?

**Comment by stratochief66** [comment]
Is this PR good to go? Did it test out alright for you guys, @PhineasFreak or @SirKeplan ?

**Comment by PhineasFreak** [comment]
I cannot comment for the DRE patch (it was going to be overhauled anyway for the new DRE release) but i do not think that i have left any issues open. I still need to add the new CMES parts for all the other categories though.

@SirKeplan did the removal of the DRE patch fix the problems that you had?

**Comment by SirKeplan** [comment]
@PhineasFreak Yep, Looks good to me.

**Comment by PhineasFreak** [comment]
In that case @stratochief66 you are good to proceed.

**Pull request merged**
