### PR TITLE
[Maintenance] Coatl Aerospace 0.16 RC

### PR DESCRIPTION
**Pull request by PhineasFreak**
These configs have been in the making for a long time and, due to the large amount of new parts, i will be pushing them to the RO **master branch** ~~(even if not 100% of the parts are configured)~~ for reviews and feedback. So, do not merge this yet.

~~Missing parts include:~~

* ~~all Hyugens lander parts~~
* ~~some STEREO scientific instruments~~
* ~~the Surveyor Orbiter solar array wing~~

**Change Log:**

* Added RO support for all new parts (Cassini, Juno, STEREO, Surveyor Orbiter)
* Updated all generic RCS parts to use the new RCS handling setup.
* Removed some redundant global engine config fields.
* Increased the mass of the 4MV spacecraft bus GNC system from 800 to 840 Kg (accounts for the gross mass of the baseline spacecraft configuration).
* Fixed the mass of the Venera reentry module decoupler (was too high compared to other decouplers of the same size & purpose).
* Fixed the tags of the LM900 Satellite Bus.
* Fixed the CharredAblator multiplier MM patch (using @ instead of % and not applying at all).
* Fixed the mass of the Cassini Radio and Plasma Wave Science (RPWS) instrument.
* Fixed the mass of the CA-DUST-C Dust Sample Collector instrument.
* Fixed the propellant patching of the KTDU-425A engine (although it is overriden by the global engine config).
* Fixed the inert mass of the STAR-37E Voyager 1 & 2 propulsion module (now accounts for the mass of the RCS thrusters and all related hardware).
* Changed the KTDU-425A engine patch to use the global engine config (https://github.com/KSP-RO/RealismOverhaul/pull/1843).
* Reduced the heat production of the KTDU-425A engine to be appropriate for it's size/thrust values.
* Tweaked the length of the Venus Express Solar Array Wing (SAW) to match the IRL size.
* Adjusted the EC rates of the Mars Express Solar Array Wing (SAW) and the CA-E200B Solar Array.
* Decreased the range of the MAVEN parabolic antenna from 5 Tm to 500 Gm for better balancing against similar parts.

**Notes:**

* None of parachute parts have been tested under the stock KSP aero system/parachute setup, considering that RO requires both FAR and RealChute. Still, it would be nice if someone has information on how to set the parameters correctly for the parachutes to work without these mods installed.

### CODE REVIEW

**Comment by raidernick** [comment]
@PhineasFreak is this something you want in the 1.3.1 release, we are really close to that and at that time I'll be merging dev with master anyway.

**Comment by PhineasFreak** [comment]
It would be nice but i am not sure about the timeframes. The STEREO parts will be the most difficult to configure correctly, followed by the Huygens ones. I'd say...about a week or so?

**Comment by raidernick** [comment]
I can wait until next weekend, I am planning to do it that saturday

**Comment by PhineasFreak** [comment]
OK, i will do my best to finish the configs by then.

**Comment by raidernick** [comment]
Sorry I had to edit the comment lol, I posted that while i was being messaged by egg and he said we should not wait, since we will be doing another release soon again anyway.

**Comment by PhineasFreak** [comment]
That's also OK! Maybe even better since i have some RealScaleBoosters config updates that i'd also like to push.

**Comment by PhineasFreak** [comment]
All parts are now configured. I also moved the KTDU-425A engine config to be a global one (dev branch). Huygens parachutes might neeed further tweaking (or the Titan pressure curve is off...) but they can be easily replaced if required.

**Comment by raidernick** [comment]
@PhineasFreak I just merged dev into master, removing the dev branch soon. This now has conflicts due to that merge

**Comment by PhineasFreak** [comment]
Damn, i thought that i had backported all changes...anyway, it is fixed now!

**Pull request merged**
