### PR TITLE
RO-EngineConfigs FASA Atlas Nova Saturn

### PR DESCRIPTION
**Pull request by SirKeplan**

### CODE REVIEW

**Comment by stratochief66** [comment]
I noticed (from the FASA perspective) that the H-1B config changed from 306s of vacuum ISP to 296s. (unheard of! heresy!)

Not a huge deal (entirely expected as various configs are squared) but worth noting. @SirKeplan if you notice engines that you notice differ substantially from part to part, please take note of them and post the info somewhere in association with these PRs. 

And of course, if anybody else notices this while testing, please blow the whistle as well. After this project is done, we probably want to do a thorough pass through the new canonical configs (in EngineConfigs) and ensure we are happy with them and that the values we settle on square with citation.

Also @SirKeplan if it isn't too much, could you try to save the citations you find posted amongst the separate engine configs and attach them to your EngineConfig files? That is probably the Perfect place for us to store engine citations.

**Comment by SirKeplan** [comment]
@stratochief66 ok, i could have made better notes, will do in future then. what i did when i saw discrepancy's was a quick research to find which was the more believable figure.
and yes, the EngineConfig files are a good place for the citations.

**Comment by stratochief66** [comment]
Tested, working. Ready to merge when you want @NathanKell

**Comment by SirKeplan** [comment]
@stratochief66, noted a few parts that had differences here. https://github.com/KSP-RO/RealismOverhaul/pull/829

**Comment by stratochief66** [comment]
@SirKeplan if you can refresh this to resolve conflicts with the master, I can merge it.

Or @NathanKell, do you want to do some Github wizardly?

**Comment by SirKeplan** [comment]
conflicts should be fixed, little tricky when things are changing in different places :D

**Pull request merged**
