### PR TITLE
Fix old Juno IV configs, add new ones

### PR DESCRIPTION
**Pull request by Capkirk123**
Deprecate old Juno 6k and 45k configs and create new, more accurate ones. Also add configs for Juno IV growth options, including ClF3 upper stages and UDMH/LOX S-3D.

Needs https://github.com/KSP-RO/RealismOverhaul/pull/2838

### CODE REVIEW

**Comment by Capkirk123** [comment]
RODeprecation tags applied, should be good to go once #2838 is merged

**Comment by ilmcamam** [comment]
Is there a primary source that explicitly states 150klbf design thrust specifically for Juno IV? Having stumbled upon [two](https://www.si.edu/media/NASM/NASM-NASM.2020.0031-Interim_Report_to_the_Special_Committee_on_Space_Technology_box1_folder4-000002.pdf) [documents](http://libarchstor2.uah.edu/digitalcollections/items/show/11031) that suggest otherwise (165klbf), it seems a little strange to have such a low TWR (~1.1). If this is for Juno IV in particular (rather than Jupiter as a whole), would it make sense to have the higher thrust?

**Comment by Capkirk123** [comment]
It does appear that some performance growth was expected for the Jupiter first stage of Juno IV.

**Comment by arrowmaster** [comment]
I think this and https://github.com/KSP-RO/RP-0/pull/1925 should have been merged to master instead of a PLC branch. This shouldn't be save breaking because new engine configs were created and the old one left in place for any already built crafts.

**Comment by NathanKell** [comment]
Oh, hmm, yeah. It redirects to the new ECM but I think that's ok, RF should treat it as unlocked? (I wasn't worried about the RO side, just the RP-1 side, but I can't merge the RO side to master and the RP-1 side to PLC because that would leave the new configs with no requirement or cost)

**Pull request merged**
