### PR TITLE
Adjust life support resources for Raidernick Soyuz 7K-OK for 20 day/2…

### PR DESCRIPTION
**Pull request by dgeastman**
… crew Soyuz 9 record, 10day/3 crew nominal mission (with 1 day margin)

### CODE REVIEW

**Comment by NathanKell** [comment]
I'm confused why the volume went down despite adding more resources

**Comment by dgeastman** [comment]
The max values for food and water both went down. They were set closer to 14 days than the 11 I have here. The starting values went up however, as they were only like 3 days, not the 10 of a nominal mission.

**Comment by raidernick** [comment]
@NathanKell do not merge this into a RO release without letting me know before you do it. This will require changes to all of the craft files that contain these parts.

@dgeastman Do not make changes to the craft files yourself and PR them, I will test this and do it if/when it needs to be done.

**Comment by NathanKell** [comment]
Yup, that's why I've left it as is--as I said on discord when Squirrel asked, I know you tend to handle your own stuff and leave you to look over such PRs. :)

**Comment by dgeastman** [comment]
To be clear, the patches here are just because as I was balancing out numbers and checking out real mission profiles, this is what I came up with for real mission duration and intent, and it's what I tested against. But if you want to stick with the original values here, I don't really have a problem with that. It's the PR in ROKerbalism to add nitrogen, PotassiumSuperoxide, and LithiumHydroxide that's important.

**Comment by raidernick** [comment]
These fixes were incorporated into this PR: https://github.com/KSP-RO/RealismOverhaul/pull/2791

Thanks for the help here, this will now be closed.

**Pull request closed without merging**
