### PR TITLE
Kestrel-1B Global Config

### PR DESCRIPTION
**Pull request by PhineasFreak**
* Add a global engine configuration for the hypothetical Kestrel-1B engine (a Methalox variant of the kerolox Kestrel engine).

### CODE REVIEW

**Comment by Ravenchant** [comment]
Assuming all other variables kept equal, why would a switch to methalox propellant significantly reduce performance?

**Comment by SirKeplan** [comment]
Assuming all things being equal methalox should give 10-15s more ISP than kerolox. For a hypothetical pressure fed kestrel on methalox, probably about 10s more than the kero one i would think.

http://yarchive.net/space/rocket/fuels/fuel_table.html

**Comment by PhineasFreak** [comment]
I will be completely honest: i have not done any theoretical modelling of the engine since i do not know how to do that. I was hoping that more experienced members would help to fix/improve that (and it seems like it!).

**Comment by SirKeplan** [comment]
Fair enough. If i had some more stats on this engine(oxidiser fuel ratio, nozzle expansion ratio) etc, i could model a good approximation of the stats in [RPA](http://www.propulsion-analysis.com/index.htm). However as this methalox variant is completely hypothetical i believe, then about 330s ISP is fine.

**Comment by PhineasFreak** [comment]
I have the O/F ratio defined in the opening engine notes but not the expansion ratio. I think that it can probably be calculated from the nozzle diameter? The diameter is approximately 0.5 m (50 cm).

That tool seems to be what i need to calculate the actual performance. Thank you for introducing it to me!

**Comment by stratochief66** [comment]
@PhineasFreak that second set (in Edit 3) of numbers appears reasonable compared to SirKeplan's suggestion of 330s vac ISP and my general understanding of Methalox. It can always be adjusted when more information comes in.

Do you want to change this PR to reflect those numbers, then I can merge this?

**Comment by PhineasFreak** [comment]
Yep, no problem. Give me a couple of minutes.

**Comment by SirKeplan** [comment]
These stats in the config look fine to me, though i would note that an O/F Ratio of 2.77 is unusually low. Methalox tends to have a ratio of around 3 - 3.5.

**Comment by PhineasFreak** [comment]
@SirKeplan maybe change it to an O/F ratio similar to the Raptor (3.8)? It is the closest that we have now in terms of methalox flight hardware.

**Comment by SirKeplan** [comment]
Probably nearer 3.0, they are at opposite ends of the spectrum for engine performance.

**Comment by PhineasFreak** [comment]
OK, i will push the changes with the next CMES patch updates.

**Pull request merged**
