### PR TITLE
VSR radial fuel tanks RO support

### PR DESCRIPTION
**Pull request by PhineasFreak**
* Add RO support for the radial fuel tanks.

### CODE REVIEW

**Comment by NathanKell** [comment]
It might be worth doing what we do for the Mk3 parts, i.e. have the LFO and LF parts both ingame, but have one kind set to one tank type, and the other to another. In this case, since radial monoprop tanks already take care of ServiceModule, maybe Default and Cryogenic?

**Comment by PhineasFreak** [comment]
@NathanKell i envisioned the tanks as storage for non - cryogenic type of fuels and/or for life support purposes but now that you mention it, you are right.

Question: should i change the tank type from "Default" to "ServiceModule"?

**Comment by NathanKell** [comment]
I'd suggest leaving the LFO types as "default" and the LF-only types as Cryogenic

**Comment by PhineasFreak** [comment]
Perfect! I will have them ready in a few hours (because i have been awake for too long).

**Comment by NathanKell** [comment]
Awesome! And do please sleep, sleep's important. :)

**Comment by PhineasFreak** [comment]
Batteries full, let's do some modding!

**Comment by PhineasFreak** [comment]
Dang it, i deleted the wrong branch! Stupid me...

**Comment by NathanKell** [comment]
Whew! Glad it's back :)

One last thing--I'd suggest removing (Pressurized) from the type=Default tanks. While it's technically true, we generally reserve talking about a tank as pressurized for when it's _Highly_ Pressurized, i.e. type ServiceModule or Fuselage.

**Comment by PhineasFreak** [comment]
OK, on it!

**Comment by NathanKell** [comment]
Thanks! :)

**Comment by PhineasFreak** [comment]
My pleasure working with you guys & gals!

**Pull request merged**
