### PR TITLE
Update KWRocketry.cfg

### PR DESCRIPTION
**Pull request by John-Long-Silver**
Changed "emission = 0.0 x" to "emission = 0.0 0" and "directThrottleEffectName" to "powerEffectName" as suggested by NathanKell.
I hope this is in any way helpful.

### CODE REVIEW

**Comment by John-Long-Silver** [comment]
Is this better now?

**Comment by NathanKell** [comment]
Yeah, looks good. However, last night @stratochief66  found that these changes _may_ not be necessary after all, so I'll try with and without them and see what happens, and if they're not needed I'll strike it from the todo list. Meanwhile I'd ask if you might look into the other bits on the todo list.

Thanks! :)

**Comment by John-Long-Silver** [comment]
Ok, so let me know if you still need them, in that case I will create a PR for the other files.
Regarding the rest of the todo list I might need some further instructions.

**Comment by NathanKell** [comment]
Sure! Can you pop by #RO on espernet? ( [webchat link if you don't have an IRC client](http://webchat.esper.net/?channels=RO) )
If not can do it here.

**Comment by NathanKell** [comment]
@John-Long-Silver  ?

**Comment by John-Long-Silver** [comment]
Let's do this here for now...

**Pull request closed without merging**
