### PR TITLE
Update RO_AJE.cfg

### PR DESCRIPTION
**Pull request by RedAV8R**
Some better naming and description changes.

Give credit to mod (ex. AJE) as 'manufacturer' per agreement with others.

### CODE REVIEW

**Comment by NathanKell** [comment]
So, after discussing it with part makers, and on the channel, we had a reevaluation--we do, now, use the correct manufacturer name for the given item. So that's one less complication! :)
(That's why there have been some patches to change manufacturer name)

**Comment by RedAV8R** [comment]
Ok, that's fair.

I still believe some naming of the 'title' should be a bit more descriptive, especially for stock items. Like "Fuel Tank - 1.25m", or something like that. Something a bit more standardized, and easy to located. Will also group a whole lot nicer when sorted by part name, etc.

**Comment by NathanKell** [comment]
Ah, sure, I totally agree! That makes good sense.

**Comment by RedAV8R** [comment]
BTW.. I"M BACK!!! :)

**Comment by RedAV8R** [comment]
Leave me be, no need to be a big part, but i'll be attempting to clean some stuff up and make PRs as I go.

**Comment by NathanKell** [comment]
And a hearty welcome back to you! :)

Hope things are well Chez Red, and all! :)

**Comment by NathanKell** [comment]
Will do. Always awesome, always appreciated. :)

**Pull request closed without merging**
