### PR TITLE
RO DECQ Angara pack

### PR DESCRIPTION
**Pull request by PhineasFreak**
* Add RO support for the DECQ Angara pack.

### CODE REVIEW

**Comment by SirKeplan** [comment]
`@MODULE[ModuleGimbal]` shouldn't be necessary on the engines, gimbal settings are already set in the Engine Configs.

**Comment by PhineasFreak** [comment]
Consider it a leftover from the initial testing round. I will remove it in a sec.

**Comment by jwvanderbeck** [comment]
Um , wasn't it removing the gimbals last time that broke tons of engines?  Unless i'm just misunderstanding, @NathanKell  said the gimbals need to be there didn't he? See https://github.com/KSP-RO/RealismOverhaul/pull/1270 for reference.

**Comment by SirKeplan** [comment]
@jwvanderbeck this should be different. The transform names aren't being changed

**Pull request merged**
