### PR TITLE
Tantares Soyuz Fixes and improvements

### PR DESCRIPTION
**Pull request by SirKeplan**
General improvements to the Tantares Soyuz, they now are a closer match to real life. more work/tweaking could be done, but this is quite playable.
fixes some bits in issue #1109 

I've made the 3 person descent module a clone of the 2 person one, but it might make more sense to just have the 3 person one.
COM offset possibly needs tweaking, but is functional.

Should be ready to merge now

### CODE REVIEW

**Comment by stratochief66** [comment]
The Soyuz is unstable during re-entry until you hit ~0.25G, I would recommend lowering the CoM as well, but in and out of re-entry mode, like so:

https://github.com/KSP-RO/RealismOverhaul/blob/master/GameData/RealismOverhaul/RO_SuggestedMods/FASA/RO_FASA_ApolloCSM.cfg#L220

**Comment by stratochief66** [comment]
@SirKeplan 
I tuned the Soyuz CoM & CoM shifter for re-entry stability before & after enabling the mode, and got these (for Tantares_Crew_A)

	MODULE
	{
		name = CoMShifter
		DescentModeCoM = 0, -0.5, -0.1
	}

	@CoMOffset = 0.0, -0.5, 0.0

I find the HTP for roll control either a tad overpowered, or unbalanced. It was entirely functional though. :)

**Comment by stratochief66** [comment]
And if you want to throw a config for the Gemini chute into this PR (for Spica_Parachute_A)

@PART[Spica_Parachute_A]:AFTER[RealChute]
{
	!sound_parachute_open
	!sound_parachute_single = deploy
	!MODULE[ModuleParachute] {}
	!MODULE[ModuleDragModifier],* {}

	%MODULE[RealChuteModule]
	{
		%caseMass = 0.01
		%timer = 0
		%mustGoDown = true
		%cutSpeed = 0.5
		%spareChutes = 1
		%reverseOrientation = true

		%PARACHUTE
		{
			%material = Nylon
			%preDeployedDiameter = 4.25
			%deployedDiameter = 35.5
			%minIsPressure = true
			%minPressure = 0.4
			%deploymentAlt = 4000
			%cutAlt = -1
			%preDeploymentSpeed = 2
			%deploymentSpeed = 6
			%preDeploymentAnimation = Spica_Parachute_A_Semi
			%deploymentAnimation = Spica_Parachute_A_Full
			%parachuteName = Spica_Parachute_A_Canopy
			%capName = Cap
		}
	}
}

Tested and working. Very much needed the %reverseOrientation = true

**Comment by stratochief66** [comment]
Excellent, thanks!

Ready to merge?

**Comment by SirKeplan** [comment]
Yep!

**Pull request merged**
