### PR TITLE
RN b330 add

### PR DESCRIPTION
**Pull request by raidernick**
-add config for b330

### CODE REVIEW

**Comment by stratochief66** [comment]
@raidernick 
The config looks fine. I couldn't find this part anywhere, so I can download and test it. Is it available, or at least available for testing this PR?

**Comment by raidernick** [comment]
no its not yet but i tested it and it works

**Comment by stratochief66** [comment]
@raidernick I was just thinking about this PR yesterday, glad to see you merged it.

Please let me know when the mod is released so I can try it out & test it! :)

Edit:
Ahh, is this it here so I can grab it and try it out?
https://github.com/KSP-RO/RNMisc/tree/master/GameData/RN_Misc/B330

**Comment by raidernick** [comment]
you can try it but the part is sorta in an alpha state at the moment.

**Pull request merged**
