### PR TITLE
configs for SSTU landers, only needs balancing

### PR DESCRIPTION
**Pull request by FFCJoseEduardo**
First pass config for SSTU landers, it works but might need balancing for fuel and masses

### CODE REVIEW

**Comment by stratochief66** [comment]
@FFCJoseEduardo 

This downloaded as .txt for me, did you name it as *.cfg like the rest of the files, or is it currently with no extension or .txt?

**Comment by stratochief66** [comment]
The LC2 variant that doesn't show external fuel tanks probably shouldn't report having MMH & NTO. That is possible with the switchy-tanks, correct?

**Comment by FFCJoseEduardo** [comment]
I probably forgot to add an extension when I created the file... my bad

as for the LC-2, it's the same with the other 2 pods, the version without tanks has NTO and MMH for the RCS, they have small amounts of it (in stock it has 50 mono, I added 50 of each for RO, same thing goes for the tank versions, they have what the rescaled volume can handle+50 each for the monoprop it had in stock)

**Comment by stratochief66** [comment]
Have the ascent (ASCE) engines been scaled up? they appear a bit small.

**Comment by FFCJoseEduardo** [comment]
they all have, same scale for all lander parts, 1.25, same as Orion

it's just that they do look really small

**Comment by stratochief66** [comment]
Perhaps you should get on #RO, we could be talking live :P

**Pull request closed without merging**
