### PR TITLE
Added Procedural Crew Tubes

### PR DESCRIPTION
**Pull request by codepoetpbowden**
This pull request adds the concept of "procedural crew tubes" for Realism Overhaul. crew tubes are structural parts that allow crew to pass through them from a CLS point of view. They are more massive and costly than regular structural parts, and have a minimum size. They add an extra realism consideration to station and base building.
I am not terribly experienced with module manager, but have tested this in both career and sandbox modes and it seems to do what I intended. It is humbly offered to the community, I hope it is seen as an  improvement.

### CODE REVIEW

**Comment by Ravenchant** [comment]
Good idea! I think the 2m minimum diameter is a little on the large side though.

**Comment by codepoetpbowden** [comment]
Yep, I suppose it depends if you are sizing for kerbals or humans to be able to move around inside.
I went for 2m because that is the diameter for the standard size docking ports in RO, so a docking port fits snuggly on the end of one of these tubes, and I assumed that there needed to be some width allowed for sheilding, blankets etc that distinguish these parts from normal structural parts. 
However I am not precious,and was only offering it up - change it as you see fit.

**Comment by NathanKell** [comment]
Looks good to me!
However, could you do the clone on :FISRT (or at least FOR[RealismOverhaul] )? If you clone a part on final, nothing can change it.

**Comment by codepoetpbowden** [comment]
I played around with NEEDS and FOR, but could not figure out how to make it work. I will have another go when I get home tomorrow.

**Comment by NathanKell** [comment]
@codepoetpbowden sent you a PR explaining what I meant; in doing it I realized the original thing I was saying wouldn't quite work, but I think what I sent does.

**Comment by codepoetpbowden** [comment]
Made another change to mark the crew tube parts as RO supported ones. 
Now all tested and ready to be pulled.

**Comment by NathanKell** [comment]
Great! :)

**Pull request merged**
