### PR TITLE
Update Raptor reliability

### PR DESCRIPTION
**Pull request by LuneoLucy**
nerf Raptor with flight test data

### CODE REVIEW

**Comment by Test-Account-KSP** [comment]
Ignition failure is irrelevant if pre-launch failures are off, which is the default setting.
Need to nerf cycleReliabilityStart to match IRL performance even when pre-launch failures are off.

**Comment by LuneoLucy** [comment]
This should be ready for review I think

**Comment by LuneoLucy** [comment]
Modifications have been tested in game on a clean express install, I am unable to troubleshoot the issue with the outer raptor testflight config, it appears correctly in the VAB but changes to 100% succes with 0s of rated burn time in flight

**Comment by LuneoLucy** [comment]
The issue comes from the original config, I don't have enough knowledge to fix it myself so any help is welcome

**Comment by Capkirk123** [comment]
> Ignition failure is irrelevant for first stage engines if pre-launch failures are off, which is the default setting. Need to nerf cycleReliabilityStart to match IRL performance even when pre-launch failures are off.

You should not do this

**Comment by Capkirk123** [comment]
There are a few issues here. Most notably, Superheavy had Raptor 2s installed, not Raptor 1s (citation needed), so these configs are arguably being applied to the wrong engine.

Also, please use the TF engine reliability config tool attached to calculate failure chances.
[KSP Engine Reliability Calculator V2.0 (1).xlsx](https://github.com/KSP-RO/RealismOverhaul/files/11304731/KSP.Engine.Reliability.Calculator.V2.0.1.xlsx)

**Comment by LuneoLucy** [comment]
I tried to fix the original TF config but it requires knowledge that I do not have, so PR is closed

**Pull request closed without merging**
