### PR TITLE
AIES weight/range/power brought in line with stock/RT antennas.

### PR DESCRIPTION
**Pull request by Schnobs**
These things look more modern that the standard set, so I've given them somewhat better data. If/when they get integrated with RP-0, they should be 70s tech and beyond.

### CODE REVIEW

**Comment by NathanKell** [comment]
These should also be done on FOR[RealismOverhaul] not final.

**Comment by NathanKell** [comment]
@Schnobs poke?

**Comment by SirKeplan** [comment]
@Schnobs double poke/what's going on?  It'd be good to have these properly in RO.

**Comment by SirKeplan** [comment]
now in #1108

**Pull request closed without merging**
