### PR TITLE
SOCK shuttle orbiter configs

### PR DESCRIPTION
**Pull request by StonesmileGit**
Configs made by Aviation on the discord server, managed for this PR by me

Things that need work:
- ~Engines get convection heating behind the shuttle, causing them to overheat~
  - This will be addressed through FAR
- ~Investigate if the aerodynamics are correct with FAR~
  - It's good enough

Some parts from the mod are still unconfigured (spacelab + other crew tubes for the payload bay)

### CODE REVIEW

**Comment by sidseth26** [comment]
Hi, 
i tried with RO configs for this mod as well. the main issue for contention was aerodynamics and lateral stability with FAR. Do you experience this as well?

**Comment by StonesmileGit** [comment]
These configs are mostly ready to be merged, except for how FAR is handled. Help regarding FAR configs for especially the rear rudder is needed.

**Comment by NathanKell** [comment]
What exactly is the issue with FAR?

**Comment by StonesmileGit** [comment]
Currently the wings are not using FAR configs, due to them generating different amounts of drag, causing the orbiter to roll. The tail is also unconfigured, since FAR apparently does not like parts with multiple control surfaces, the airbrales are different surfaces on the same part

**Comment by NathanKell** [comment]
I don't understand what you mean about the wings generating different amounts of drag (when FAR-configured).

As for the tail, yeah, you probably can't do the brake-rudder as one part unless dkavolis writes some new code.

**Comment by StonesmileGit** [comment]
When the same config was applied to the left and right delta-wing, the orbiter started to roll, as if they experienced different drag. This was done by Aviation over on Discord, so might have been something in the configs that was wrong.

I guess the issue with the tail can be left as is, since the shuttle can be controlled decently without it, or by attaching stock AIRBRAKES to the aft.

**Comment by NathanKell** [comment]
Are the wings attached by node, or surface attached? FAR doesn't support
wings that aren't surface-attached.

**Comment by StonesmileGit** [comment]
The wings are indeed node-attached (everything in SOCK is node attached)

**Comment by bedve** [comment]
I believe this is an issue due to the fact the wing part is the same part for both the right and the left side. If you take the Shuttle into a flight, and look at the f12 display, you will see that the lift/drag vectors are correct for the left wing, but not the right wing. My guess is that when b9 switches the orientation of the wing, this doesn't switch the FAR calculations as to where the Mid Chord is on the right wing. 

In the DECQ shuttle, which has separate parts for each wing, a similar issue happens. Despite having a separate part for the right wing, the lift/drag vector is shifted sideways (very similar to SOCK when you look at the f12) on the right wing. This was corrected by applying a "rootMidChordOffsetFromOrig" on the right wing part, which is what the current RO configs do - [link](https://github.com/KSP-RO/RealismOverhaul/blob/master/GameData/RealismOverhaul/RO_SuggestedMods/SpaceShuttleSystem/WingSurfaces.cfg).

So I don't think your FAR configs that are commented out are really that FAR off (ha-ha).

**Pull request merged**
