### PR TITLE
[Bugfix] RealEngines updates

### PR DESCRIPTION
**Pull request by PhineasFreak**
**Change Log:**

* Change **all** internal part names to fix compatibility issues with RP-0/1. **WARNING: save & craft-breaking update!**
* Update all engines with integrated tubopump exhausts/vernier engines to use a single engine module in order to fix various TestFlight interop bugs.
* Simplify the RealPlume patches of the A-7 engine.

### CODE REVIEW

**Comment by pap1723** [comment]
@PhineasFreak are you of the opinion that I can remove the duplicates I created in RP-1 for the old parts to save people's crafts? Should we just go with a craft breaking switch like this?

**Comment by PhineasFreak** [comment]
Three considerations that i had in mind before pulling this trigger:

* The craft-breaking changes that will occur anyway for RO in the future to be fully compatible with KSP 1.4+.
* The fact that most parts that RP-1 requires (like the avionics and the custom tanks) are not available under RO, breaking crafts anyway.
* The fact that RP-1 still breaks careers/craft designs almost daily due to other reasons.

Now, part name changing will occur only once in the lifetime of the parts, with or without RP-1 installed.

**Comment by siimav** [comment]
I noticed that the new part names are different to the ones currently used in RP-0. [See here.](https://github.com/KSP-RO/RP-0/blob/master/GameData/RP-0/Parts/RealEnginesFixes.cfg) Wouldn't it be better to use already existing ones so that one less round of craft-breaking updates would happen?

**Comment by PhineasFreak** [comment]
Craft compatibility is already broken, both by the KSP version and the recent RO solids updates (see my notes above). So, i decided to use names that are a better fit (see: various KDTU part clones).

BTW, not all part names break RP-1 but i went and changed them anyway.

**Comment by pap1723** [comment]
Reviewed, waiting to push changes to group together some craft breaking ones at the same time.

**Comment by pap1723** [comment]
I will also need to change all of the RP-1 files to match these.

**Comment by PhineasFreak** [comment]
So, i guess that this PR is now useless and not going to offer anthing, right?

**Comment by pap1723** [comment]
Not necessarily, why?

**Comment by PhineasFreak** [comment]
All these are part of/will be replaced by RO Engines, no?

**Comment by pap1723** [comment]
Oh, yes they will be. Don't know if we want to remove them, I will listen to ideas. ROEngines will not be mandatory.

**Comment by PhineasFreak** [comment]
Then what's the point over having a minum mandatory mod list (as the current situation is)? I though that RO Engines would **replace** all these heavy mods with a more streamlined, 100% RO-curated solution.

**Comment by pap1723** [comment]
That is exactly what it is going to do. It is just not forced on players to download. If players don't want the whole thing, they can just get RealEngines for example. (I do not know why anyone would not want it, but I don't like forcing people to only go one path)

**Comment by raidernick** [comment]
@PhineasFreak RO is not a parts mod and never will be. It can support official RO "approved" packs as replacers but I am NOT adding in any models or meshes to this mod(or approving of anyone else doing it either). The whole point is to keep RO as small as possible with as little overhead as possible. @pap1723 is correct it will be suggested only and not required or packaged or even linked directly as part of the RO download, it will just be listed as recommended along with the rest of the mods that are but not required.

**Pull request merged**
