### PR TITLE
AJ-60A solid rocket motor global engine config

### PR DESCRIPTION
**Pull request by PhineasFreak**
* And a big "thank you" to @A1Ch1 for calculating the thrust curve!

### CODE REVIEW

**Comment by A1Ch1** [comment]
The global config for this should already be included in the KW SRM PR :) Don't have access to a computer right now to check

**Comment by A1Ch1** [comment]
This is good to ahead and merge this though, I'll just remove it from the KW PR so we can merge the RSB PRs :)

**Comment by PhineasFreak** [comment]
I can see it now...i should have looked better. Shall i close this and wait for the KW one?

**Comment by A1Ch1** [comment]
No this is good to merge since it'll let us get the RSB mod in without waiting on the KW SRM configs

**Pull request merged**
