### PR TITLE
RO-EngineConfigs FASA Titan Agena

### PR DESCRIPTION
**Pull request by SirKeplan**

### CODE REVIEW

**Comment by stratochief66** [comment]
Looks good!

The only thing that seems a bit strange is this:
https://github.com/KSP-RO/RealismOverhaul/pull/851/files#diff-4272427f87e810f628186d14c801ef8eR255

I looked, that is certainly the name of the config for the Agena flight pack in FASA. Does anybody else know why? @NathanKell?

That can probably be fixed fairly easily later through a re-naming to something more fitting, no biggy.

**Comment by NathanKell** [comment]
It should be AgenaSPS. The 'flight pack' is a combination of Agena's cold-gas attitude thrusters and the Agena Secondary Propulsion System (SPS). Bladder-fed ullage / in-orbit orbit adjustment rockets.

**Comment by SirKeplan** [comment]
huh, that is weird naming, never saw that, should be fixed.

**Comment by stratochief66** [comment]
@SirKeplan, could you modify the name here to match your new template name on #829? Then, I think it is good to merge.

**Comment by SirKeplan** [comment]
@stratochief66 it's already been changed to `AgenaSPS`

**Comment by stratochief66** [comment]
Yep, indeed. Thanks!

**Pull request merged**
