### PR TITLE
Config cleanup and some more improvements

### PR DESCRIPTION
**Pull request by Capkirk123**
Continue to work on cleaning up engine configs, adding sources, etc. 
Also make improvements to a few of the more neglected configs. Changes include:

- Make Bell Model 117 a little lighter since it has no gimbal
- Use RPA to try to estimate BE-3 performance a little better
- Complete overhaul of E-1 configs. Using the E-1 Dynasoar RBS version, the only config for which comprehensive data exists, create configs of 380, 468, 500 and 575 klbf SL thrust, using RPA and the H-1 to estimate performance data. Old E-1 configs have been deprecated, and the Kolyma's Shadow E-1A is kept mostly the same
- Improve H-1 SL ISP using data from Skylab 2 and the H-1 users manual
- Revise HG-3 SL performance using RPA
- Reduce XLR83 T/W to a sane value by increasing dry mass
- Reduce LR87-LH2 T/W to a sane value by increasing dry mass. Also revise performance a little using RPA
- Correct MR-80/MR-80B SL ISP (it was previously using ISP values from Mars "sea level")
- Completely revise NK-9 engine configs based on better sources
- Completely revise NK-9V engine configs based on better sources
- Completely revise NK-15/33 engine configs based on better sources. Also add AJ26-58 and AJ26-59 configs.
- Completely revise NK-15V/43 engine configs based on better sources. Also add AJ26-60 config.
- Reduce mass of RD-0236
- Use RPA to better estimate SL performance of RL10-CECE configs
- Configure RS-2100 to use subcooled propellants
- Correct RS-68B ISP
- Completely revise RS-88/LAE configs based on better sources

Although many changes are made, this should not be save-breaking. Many changes were made, but most were minor. The only significant performance reductions were to the NK-15, NK-15V, RS-88, and LAE.

### CODE REVIEW

**Comment by NathanKell** [comment]
Nice work!!
Question on the E-1 -- should the Isp really not increase? I would expect some improvement there, in the way that LR89s improved over time.

**Comment by Capkirk123** [comment]
No, not really. I assumed it was a relatively modular design like the H-1, where chamber pressure was increased without making any changes to the injector.

**Comment by NathanKell** [comment]
If you're increasing chamber pressure wouldn't you also increase the nozzle AR? LR87-AJ-5 -> LR87-AJ-9 style.

**Comment by Capkirk123** [comment]
That's a can of worms I didn't really want to open, and besides, the H-1 and F-1 didn't

**Comment by NathanKell** [comment]
Under the (speculative) world where the E-1 remains in regular use, I would expect it to get upgrades like the in-regular-use LR87, rather than the one-and-done H-1 and F-1.

**Comment by NathanKell** [comment]
(one-and-done is slightly unfair to H-1, but the work on them broadly stopped in the early-mid 60s, right? Except for that 250klbf study. The "in regular use" H-1s were remanufactured into RS-27 rather than actually being new engines.)

**Comment by Capkirk123** [comment]
I mean, that was the entire point of the modular design applied to the E-1, F-1, H-1, etc. That it could be upgraded to different roles without significant design changes, unlike first generation engines. And it does get the O/F leaned out in the later versions to help increase performance.

**Comment by Capkirk123** [comment]
Also fwiw, the two datapoints we have on the E-1, the test stand model and the Dynasoar booster proposal, show very similar ISP despite a significant (380 to 468 klbf) increase in thrust

**Comment by NathanKell** [comment]
Well, IMO it sucks for gameplay reasons to have basically no choice as US but to use LR87s if you want a specific impulse above 290 (discounting F-1), but I take your point.

**Comment by NathanKell** [comment]
Also if you're renaming configs, you should use the upgrade tool provided (add entries to UpgradeData.cfg )

**Comment by NathanKell** [comment]
@Capkirk123  More E-1 partisanship: since it unlocks later than the H-1, would we expect its in-service Isp to be comparable (or higher) to H-1? Or would there be too many losses from the gas generator? Because it has a higher chamber pressure and a higher AR nozzle, and yet a worse vacuum Isp. So I'm confused.

And does the UpgradeData.cfg file make sense?

**Comment by Capkirk123** [comment]
Well, the one reliable source, dated May 1960, states an expected performance of 256/291. 

Throwing it into RPA, that seems to suggest a combustion efficiency similar to the F-1. The Rocketdyne baffled injectors that they used to deal with combustion stability at that scale really hurt efficiency. The F-1 just ran at higher pressure and had the film-cooled nozzle extension.

Although such a nozzle extension could also be fitted to the E-1, since it runs at lower pressure, this also hurts sea level ISP. That opens the can of worms as to what the E-1 would be used for. In a Titan-like role, with an airlit core, that tradeoff makes sense. In a more Kolyma's Shadow role, with a monolithic E-1 core (also suggested by the USAF study), this would likely not be performed.

I'm not sure using the upgrade cfg is a great idea. The old configs are still there, just deprecated, and the new configs are relatively dissimilar.

**Comment by Capkirk123** [comment]
Obviously, with 1.5 reliable sources, this leaves a lot of latitude for creative config work. I chose the conservative approach, simply mirroring the upgrades applied to the H-1.

**Comment by NathanKell** [comment]
Sorry, somehow I missed the notifications on these. Yeah, all that makes sense. Likely (as OTL for F-1 and H-1) E-1 upgrades would focus on thrust for a larger LV, rather than squeezing out extra performance. It's possible something like RS-27A might be done, as you surmise (either groundlit with a few UA1207s and a long-burning core, or airlit with many, many UA1207s).

Ok, at any rate I'm satisfied with the E-1. Thanks for humoring me. :) Consider this PR reviewed on my account, merge when ready!

**Comment by Capkirk123** [comment]
Unless any further objections exist, I would like to merge this so I can get on with RD-0106/0107/0108 changes without fear of conflicts

**Pull request merged**
