### PR TITLE
Corrected Bobcat Soviet Engine Plumes

### PR DESCRIPTION
**Pull request by JandCandO**
Corrected positions for plumes, and tweaked other parameters to make the plumes look like they belong to their engine. All Bobcat Soviet engines covered. It might not be 100% accurate, but it is definitely better than it was before and I wanted to get this out there.

I uploaded some sample screenshots here:
http://imgur.com/a/BFxSy

### CODE REVIEW

**Comment by Felger** [comment]
Update your fork to the newest set of plumes, I've ported the hydrolox plume to a more blue particle, though I think I'll need to create a second, more red Hydrolox plume effect for ablative nozzles like the Delta IV.

**Comment by JandCandO** [comment]
Alright, I'll get onto that tonight!

**Comment by Felger** [comment]
Ooh, that'd be awesome!  It's been on my to-do list for a bit, so it'd be a great help!

**Comment by JandCandO** [comment]
I could use a little clarification on something: is the flare intended to be the fire deep inside the bell, or the light that stays no matter how thin the atmosphere is?

**Comment by Felger** [comment]
It's supposed to more or less fill the bell.  the Hydrolox flare should start out bright towards the top of the bell, and thin as it get towards the nozzle (might have to tweak that one a bit).

**Comment by Felger** [comment]
If you have any tweaks you'd like to see, shoot me some reference photos and I'll see what I can do. I was working off of some launch video from later STS and Delta 4 heavies.

**Comment by JandCandO** [comment]
For some of these it would be nice if I could set the plume and flare positions independently. I'm not sure how that would work with the current prefab system, though. I'm not that great with module manager.

**Comment by JandCandO** [comment]
Ok so how does this look?
http://imgur.com/a/0wHML

**Comment by NathanKell** [comment]
You can change the prefab AFTER[] the prefab is applied

Sent by my thumbs, slowly.

**Comment by JandCandO** [comment]
Thanks, NathanKell! Also, I noticed something wrong with the smoke position for the Kerolox-Upper prefab. It isn't where it is supposed to be.
http://i.imgur.com/7t0wlQy.png

**Comment by Felger** [comment]
The plumes are applied `:AFTER[zRealPlume]`, so you'd probably need to do it in `:FOR[zzRealPlume]` to put it after `:AFTER[zRealPlume]` or just do it in :FINAL

What you'd want to do is something like:
```
@PART[partname]:FOR[zzRealPlume]
{
    @EFFECTS
    {
         @Solid-Lower
         {
            @MODEL_MULTI_PARTICLE_PERSIST[plume]
            {
                @localPosition = 0,0,1
                @fixedScale = 1
            }
            @MODEL_MULTI_PARTICLE_PERSIST[flare]
            {
                @localPosition = 0,0,-10
                @fixedScale = 200
            }
        }
    }
}
```

I'll add that to the guide, it'll allow you to adjust the parameters separately if desired. Stupid conic nozzles messin' up my plumes.

On the Kerolox-Upper, I'm just about to commit a fix for that. Going through the smoke effects in the prefabs right now.

**Comment by JandCandO** [comment]
Thanks for help, Felger. I await the smoke fix!

**Comment by Felger** [comment]
Smoke fix is up.  Some dummy (read: @Felger) set the smoke offset in a few plumes to 25, a holdover from the original plume effects they were pulled from.

**Pull request merged**
